package gogen

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/cachegen"
	"github.com/Lumos-Labs-HQ/flash/internal/config"
	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

type Generator struct {
	Config       *config.Config
	schema       *parser.Schema
	schemaParser *parser.SchemaParser
	queryParser  *parser.QueryParser
	cache        *gencommon.GenerationCache
	enumTypeMap  map[string]string // MySQL inline ENUM type -> generated enum name
	expander     *gencommon.SchemaExpander
}

func New(cfg *config.Config) *Generator {
	cache := gencommon.NewGenerationCacheWithDir(cfg.Gen.Go.Out)
	return &Generator{
		Config:       cfg,
		schemaParser: parser.NewSchemaParser(cfg),
		queryParser:  parser.NewQueryParser(cfg),
		cache:        cache,
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Config.Gen.Go.Out, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Parse schema
	schema, err := g.schemaParser.Parse()
	if err != nil {
		return fmt.Errorf("failed to parse schema: %w", err)
	}
	g.schema = schema
	g.expander = gencommon.NewSchemaExpander(schema)
	g.enumTypeMap = g.extractInlineEnums()

	// Compute current checksums for incremental generation
	schemaHash, err := g.cache.ComputeSchemaChecksum(g.Config.SchemaDir)
	if err != nil {
		schemaHash = "" // Fallback: regenerate all
	}

	configHash := g.computeConfigChecksum()

	// Check if full regeneration is needed
	fullRegen := g.Config.ForceRegen || g.cache.ShouldRegenerateAll(schemaHash, configHash)

	// Parse queries
	queries, err := g.queryParser.Parse(schema)
	if err != nil {
		return fmt.Errorf("failed to parse queries: %w", err)
	}

	// Remove cache entries and generated files for query sources that no
	// longer exist (deleted or renamed .sql/.cql files). Without this, stale
	// entries survive forever and orphaned .go files keep compiling against
	// types that may no longer exist.
	pruned := g.cache.PruneStaleQueryEntries(g.Config.Queries)
	for _, source := range pruned {
		base := strings.TrimSuffix(filepath.Base(source), filepath.Ext(source))
		orphan := filepath.Join(g.Config.Gen.Go.Out, base+".go")
		if err := os.Remove(orphan); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove orphaned output %s: %w", orphan, err)
		}
	}

	// Generate models (only if schema changed). A shared cache file (same out
	// dir, multiple languages) can carry a matching schema checksum from
	// another generator — force regen when our own models file is missing.
	if _, err := os.Stat(filepath.Join(g.Config.Gen.Go.Out, "models.go")); os.IsNotExist(err) {
		fullRegen = true
	}
	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateModels(); err != nil {
			return err
		}
	}

	// Generate DB interface (only if needed)
	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateDB(); err != nil {
			return err
		}
	}

	// Generate queries with incremental support
	if err := g.generateQueriesIncremental(queries, fullRegen); err != nil {
		return err
	}

	// Always regenerate the embedded migration runner because migration files
	// can change independently of the schema and query generation cache.
	if err := g.generateMigrations(); err != nil {
		return err
	}

	// Generate cache layer if enabled
	if g.Config.Cache.Enabled {
		if err := g.generateCacheFiles(queries); err != nil {
			return err
		}
	}

	// Update cache
	g.cache.UpdateSchemaChecksum(schemaHash)
	g.cache.UpdateConfigChecksum(configHash)
	g.cache.MarkGeneration()

	// Save cache to disk
	if err := g.cache.Save(); err != nil {
		// Non-fatal: just log and continue
		fmt.Printf("Warning: failed to save generation cache: %v\n", err)
	}

	return nil
}

func (g *Generator) generateCacheFiles(queries []*parser.Query) error {
	pkgName := filepath.Base(g.Config.Gen.Go.Out)

	// Generate cache.go
	cacheCode := cachegen.GenerateGoCache(&g.Config.Cache, pkgName)
	cachePath := filepath.Join(g.Config.Gen.Go.Out, "cache.go")
	if err := os.WriteFile(cachePath, []byte(cacheCode), 0644); err != nil {
		return fmt.Errorf("failed to write cache.go: %w", err)
	}

	// Resolve cache annotations
	caches := cachegen.ResolveCacheQueries(queries, &g.Config.Cache)

	// Validate dep references
	if warnings := cachegen.ValidateDeps(caches, queries); len(warnings) > 0 {
		for _, w := range warnings {
			fmt.Printf("⚠️  %s\n", w)
		}
	}

	// Generate cache_accessors.go
	accessorCode := cachegen.GenerateGoCacheAccessors(caches, pkgName, g.Config.Cache.Prefix)
	if accessorCode == "" {
		accessorCode = fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\n\npackage %s\n\n// No @cache annotations found.\n", pkgName)
	}
	accessorPath := filepath.Join(g.Config.Gen.Go.Out, "cache_accessors.go")
	if err := os.WriteFile(accessorPath, []byte(accessorCode), 0644); err != nil {
		return fmt.Errorf("failed to write cache_accessors.go: %w", err)
	}

	// Generate cached_queries.go — cache-wrapped queries + auto-purge mutations
	cachedCode := g.generateCachedQueries(queries, caches, pkgName)
	cachedPath := filepath.Join(g.Config.Gen.Go.Out, "cached_queries.go")
	if err := os.WriteFile(cachedPath, []byte(cachedCode), 0644); err != nil {
		return fmt.Errorf("failed to write cached_queries.go: %w", err)
	}

	return nil
}

// generateCachedQueries produces cache-wrapped query methods and auto-purge mutation wrappers for Go
func (g *Generator) generateCachedQueries(queries []*parser.Query, caches []*cachegen.CacheInfo, pkgName string) string {
	var w strings.Builder

	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	w.WriteString("import (\n\t\"fmt\"\n\t\"time\"\n)\n\n")

	hasContent := false
	for _, q := range queries {
		if cachegen.IsCachedQuery(q) && !cachegen.IsMutationQuery(q) {
			g.writeGoCachedQuery(&w, q, caches)
			hasContent = true
		} else if cachegen.IsMutationQuery(q) {
			purges := cachegen.ResolveDependencyPurges(q.Name, caches, q.Params)
			if len(purges) > 0 {
				g.writeGoPurgingMutation(&w, q, purges)
				hasContent = true
			}
		}
	}

	if !hasContent {
		w.Reset()
		w.WriteString(fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\n\npackage %s\n\n// No cached queries or auto-purge mutations.\n", pkgName))
	}

	return w.String()
}

func (g *Generator) writeGoCachedQuery(w *strings.Builder, q *parser.Query, caches []*cachegen.CacheInfo) {
	cacheInfo := cachegen.GetCacheInfoForQuery(q.Name, caches)
	if cacheInfo == nil {
		return
	}

	methodName := utils.ToPascalCase(q.Name)
	fnName := methodName + "Cached"
	ttlSec := cachegen.ParseTTL(cacheInfo.TTL)
	useStruct := len(q.Params) > 2

	// Build key expression
	var keyParts []string
	for _, p := range q.Params {
		if useStruct {
			keyParts = append(keyParts, "arg."+utils.ToPascalCase(p.Name))
		} else {
			keyParts = append(keyParts, utils.SafeGoIdent(p.Name))
		}
	}
	var keyExpr string
	if len(keyParts) == 0 {
		keyExpr = fmt.Sprintf(`"%s"`, cacheInfo.CacheName)
	} else {
		fmtVerbs := make([]string, len(keyParts))
		for i := range fmtVerbs {
			fmtVerbs[i] = "%v"
		}
		keyExpr = fmt.Sprintf(`fmt.Sprintf("%s:%s", %s)`, cacheInfo.CacheName, strings.Join(fmtVerbs, ":"), strings.Join(keyParts, ", "))
	}

	tagsLiteral := ""
	if len(cacheInfo.Tags) > 0 {
		quoted := make([]string, len(cacheInfo.Tags))
		for i, t := range cacheInfo.Tags {
			quoted[i] = fmt.Sprintf(`"%s"`, t)
		}
		tagsLiteral = strings.Join(quoted, ", ")
	}

	w.WriteString(fmt.Sprintf("// %s queries with cache-first (TTL: %s)\n", fnName, cacheInfo.TTL))
	w.WriteString(fmt.Sprintf("func (q *Queries) %s(", fnName))

	// Use same params as the underlying method
	if useStruct {
		w.WriteString(fmt.Sprintf("arg %sParams", methodName))
	} else {
		for i, p := range q.Params {
			if i > 0 {
				w.WriteString(", ")
			}
			goType := g.mapParamTypeToGo(p.Type)
			w.WriteString(fmt.Sprintf("%s %s", utils.SafeGoIdent(p.Name), goType))
		}
	}
	w.WriteString(") (interface{}, error) {\n")
	w.WriteString(fmt.Sprintf("\tkey := %s\n\n", keyExpr))
	w.WriteString("\t// Check cache first\n")
	w.WriteString("\tvar cached interface{}\n")
	w.WriteString("\tif Cache.Get(key, &cached) {\n")
	w.WriteString("\t\treturn cached, nil\n")
	w.WriteString("\t}\n\n")
	w.WriteString("\t// Cache miss — query database\n")

	// Call underlying method with proper args
	w.WriteString(fmt.Sprintf("\tresult, err := q.%s(", methodName))
	if useStruct {
		w.WriteString("arg")
	} else {
		for i, p := range q.Params {
			if i > 0 {
				w.WriteString(", ")
			}
			w.WriteString(utils.SafeGoIdent(p.Name))
		}
	}
	w.WriteString(")\n")
	w.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")
	w.WriteString(fmt.Sprintf("\t// Store in cache (TTL: %s)\n", cacheInfo.TTL))
	if tagsLiteral != "" {
		w.WriteString(fmt.Sprintf("\tCache.Set(key, result, %d*time.Second, %s)\n\n", ttlSec, tagsLiteral))
	} else {
		w.WriteString(fmt.Sprintf("\tCache.Set(key, result, %d*time.Second)\n\n", ttlSec))
	}
	w.WriteString("\treturn result, nil\n")
	w.WriteString("}\n\n")
}

func (g *Generator) writeGoPurgingMutation(w *strings.Builder, q *parser.Query, purges []cachegen.DependencyPurge) {
	methodName := utils.ToPascalCase(q.Name)
	fnName := methodName + "AndPurge"
	useStruct := len(q.Params) > 2

	w.WriteString(fmt.Sprintf("// %s executes the mutation and auto-purges dependent caches\n", fnName))
	w.WriteString(fmt.Sprintf("func (q *Queries) %s(", fnName))

	if useStruct {
		w.WriteString(fmt.Sprintf("arg %sParams", methodName))
	} else {
		for i, p := range q.Params {
			if i > 0 {
				w.WriteString(", ")
			}
			goType := g.mapParamTypeToGo(p.Type)
			w.WriteString(fmt.Sprintf("%s %s", utils.SafeGoIdent(p.Name), goType))
		}
	}
	w.WriteString(") error {\n")

	// Call the real mutation
	w.WriteString(fmt.Sprintf("\terr := q.%s(", methodName))
	if useStruct {
		w.WriteString("arg")
	} else {
		for i, p := range q.Params {
			if i > 0 {
				w.WriteString(", ")
			}
			w.WriteString(utils.SafeGoIdent(p.Name))
		}
	}
	w.WriteString(")\n")
	w.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n\n")

	// Inject purge calls
	w.WriteString("\t// Auto-purge dependent caches\n")
	for _, purge := range purges {
		if purge.PurgePrefix {
			w.WriteString(fmt.Sprintf("\tCache.PurgeByPrefix(\"%s:\")\n", purge.CacheName))
		} else {
			paramRef := utils.SafeGoIdent(purge.KeyParam)
			if useStruct {
				paramRef = "arg." + utils.ToPascalCase(purge.KeyParam)
			}
			w.WriteString(fmt.Sprintf("\tCache.Del(fmt.Sprintf(\"%s:%%v\", %s))\n", purge.CacheName, paramRef))
		}
	}
	w.WriteString("\n\treturn nil\n")
	w.WriteString("}\n\n")
}

// computeConfigChecksum computes hash of relevant config fields
func (g *Generator) computeConfigChecksum() string {
	// Hash relevant config fields that affect generation
	configStr := fmt.Sprintf("%s|%s|%s|%v|%v|%v|%s",
		g.Config.SchemaDir,
		g.Config.Queries,
		g.Config.Database.Provider,
		g.Config.Gen.Go.Enabled,
		g.Config.Gen.JS.Enabled,
		g.Config.Gen.Python.Enabled,
		g.Config.Gen.Go.Driver,
	)
	hash := sha256.Sum256([]byte(configStr))
	return fmt.Sprintf("%x", hash)
}

func (g *Generator) generateModels() error {
	// Ensure inline MySQL ENUMs are extracted (idempotent if already done)
	if g.enumTypeMap == nil {
		g.enumTypeMap = g.extractInlineEnums()
	}
	enumTypeMap := g.enumTypeMap

	needsTime := false
	needsSQL := false
	needsGocql := false
	needsUUID := false
	isScyllaProvider := g.Config.Database.Provider == "scylla" || g.Config.Database.Provider == "scylladb" || g.Config.Database.Provider == "cassandra"

	for _, table := range g.schema.Tables {
		for _, col := range table.Columns {
			goType := g.mapSQLTypeToGoWithEnumMap(col.Type, col.Nullable, enumTypeMap)
			if strings.Contains(goType, "time.Time") {
				needsTime = true
			}
			if strings.Contains(goType, "sql.Null") {
				needsSQL = true
			}
			if strings.Contains(goType, "gocql.UUID") {
				needsGocql = true
			}
			if strings.Contains(goType, "uuid.UUID") {
				needsUUID = true
			}
		}
	}

	estimatedSize := 200 + (len(g.schema.Tables) * 150) + (len(g.schema.Enums) * 100)
	var code strings.Builder
	code.Grow(estimatedSize)

	code.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	code.WriteString(fmt.Sprintf("package %s\n\n", filepath.Base(g.Config.Gen.Go.Out)))

	if needsTime || needsSQL || needsGocql || needsUUID {
		code.WriteString("import (\n")
		if needsSQL {
			code.WriteString("\t\"database/sql\"\n")
		}
		if needsTime {
			code.WriteString("\t\"time\"\n")
		}
		if needsUUID {
			code.WriteString("\t\"github.com/google/uuid\"\n")
		}
		if needsGocql && isScyllaProvider {
			if g.Config.Gen.Go.Driver == "gocql" {
				code.WriteString("\t\"github.com/gocql/gocql\"\n")
			} else {
				code.WriteString("\t\"github.com/apache/cassandra-gocql-driver/v2\"\n")
			}
		}
		code.WriteString(")\n\n")
	}

	for _, enum := range g.schema.Enums {
		enumName := utils.ToPascalCase(enum.Name)
		code.WriteString(fmt.Sprintf("type %s string\n\n", enumName))
		code.WriteString("const (\n")
		for _, val := range enum.Values {
			constName := fmt.Sprintf("%s%s", enumName, utils.ToPascalCase(val))
			code.WriteString(fmt.Sprintf("\t%s %s = \"%s\"\n", constName, enumName, val))
		}
		code.WriteString(")\n\n")
	}

	// Generate CQL UDT structs (ScyllaDB/Cassandra)
	isScylla := g.Config.Database.Provider == "scylla" || g.Config.Database.Provider == "scylladb" || g.Config.Database.Provider == "cassandra"
	if isScylla && g.schema != nil {
		for _, udt := range g.schema.UDTs {
			// Use bare name (without keyspace prefix) for struct naming
			bareName := udt.Name
			if _, after, ok := strings.CutLast(udt.Name, "."); ok {
				bareName = after
			}
			structName := utils.ToPascalCase(bareName)
			code.WriteString(fmt.Sprintf("type %s struct {\n", structName))
			for _, f := range udt.Fields {
				fieldName := utils.ToPascalCase(f.Name)
				goType := g.mapSQLTypeToGoWithEnumMap(f.Type, false, enumTypeMap)
				code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, utils.ToSnakeCase(f.Name)))
			}
			code.WriteString("}\n\n")
		}
	}

	for _, table := range g.schema.Tables {
		structName := utils.ToPascalCase(table.Name)
		code.WriteString(fmt.Sprintf("type %s struct {\n", structName))

		// Resolve wildcard SELECT * views against the source table
		cols := table.Columns
		if len(cols) == 1 && cols[0].Name == "*" {
			cols = g.resolveWildcardViewColumns(table.Name)
		}

		for _, col := range cols {
			// Skip wildcard placeholders and view marker columns
			if col.Name == "*" || strings.HasPrefix(col.Name, "/*") {
				continue
			}
			fieldName := utils.ToPascalCase(col.Name)
			goType := g.mapSQLTypeToGoWithEnumMap(col.Type, col.Nullable, enumTypeMap)
			jsonTag := utils.ToSnakeCase(col.Name)
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\" db:\"%s\"`\n", fieldName, goType, jsonTag, col.Name))
		}
		code.WriteString("}\n\n")
	}

	modelsPath := filepath.Join(g.Config.Gen.Go.Out, "models.go")
	return os.WriteFile(modelsPath, []byte(code.String()), 0644)
}

func (g *Generator) generateDB() error {
	var code strings.Builder
	code.Grow(500)

	code.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	code.WriteString(fmt.Sprintf("package %s\n\n", filepath.Base(g.Config.Gen.Go.Out)))

	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	if isScylla {
		isGocql := g.Config.Gen.Go.Driver == "gocql"
		importPath := "github.com/apache/cassandra-gocql-driver/v2"
		execBody := "return q.db.Query(query, args...).ExecContext(ctx)"
		if isGocql {
			importPath = "github.com/gocql/gocql"
			execBody = "return q.db.Query(query, args...).WithContext(ctx).Exec()"
		}

		code.WriteString(fmt.Sprintf("import (\n\t\"context\"\n\n\t%q\n)\n\n", importPath))
		code.WriteString("type DBTX interface {\n")
		code.WriteString("\tQuery(stmt string, values ...interface{}) *gocql.Query\n")
		code.WriteString("}\n\n")
		code.WriteString("func Newq(db DBTX) *Queries {\n")
		code.WriteString("\treturn &Queries{db: db}\n")
		code.WriteString("}\n\n")
		code.WriteString("type Queries struct {\n")
		code.WriteString("\tdb DBTX\n")
		code.WriteString("}\n\n")
		code.WriteString("func (q *Queries) exec(ctx context.Context, query string, args ...interface{}) error {\n")
		code.WriteString(fmt.Sprintf("\t%s\n", execBody))
		code.WriteString("}\n\n")
	} else {
		isPGX := g.Config.Gen.Go.Driver == "pgx"
		if isPGX {
			code.WriteString("import (\n")
			code.WriteString("\t\"context\"\n\n")
			code.WriteString("\t\"github.com/jackc/pgx/v5\"\n")
			code.WriteString("\t\"github.com/jackc/pgx/v5/pgconn\"\n")
			code.WriteString(")\n\n")
			code.WriteString("type DBTX interface {\n")
			code.WriteString("\tExec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)\n")
			code.WriteString("\tQuery(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)\n")
			code.WriteString("\tQueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row\n")
			code.WriteString("}\n\n")
			code.WriteString("func Newq(db DBTX) *Queries {\n")
			code.WriteString("\treturn &Queries{db: db}\n")
			code.WriteString("}\n\n")
			code.WriteString("type Queries struct {\n")
			code.WriteString("\tdb DBTX\n")
			code.WriteString("}\n\n")
		} else {
			code.WriteString("import (\n")
			code.WriteString("\t\"database/sql\"\n")
			code.WriteString(")\n\n")
			code.WriteString("type DBTX interface {\n")
			code.WriteString("\tExec(query string, args ...interface{}) (sql.Result, error)\n")
			code.WriteString("\tPrepare(query string) (*sql.Stmt, error)\n")
			code.WriteString("\tQuery(query string, args ...interface{}) (*sql.Rows, error)\n")
			code.WriteString("\tQueryRow(query string, args ...interface{}) *sql.Row\n")
			code.WriteString("}\n\n")
			code.WriteString("func Newq(db DBTX) *Queries {\n")
			code.WriteString("\treturn &Queries{\n")
			code.WriteString("\t\tdb:    db,\n")
			code.WriteString("\t\tstmts: make(map[string]*sql.Stmt),\n")
			code.WriteString("\t}\n")
			code.WriteString("}\n\n")
			code.WriteString("type Queries struct {\n")
			code.WriteString("\tdb    DBTX\n")
			code.WriteString("\tstmts map[string]*sql.Stmt\n")
			code.WriteString("}\n\n")
			code.WriteString("func (q *Queries) Close() error {\n")
			code.WriteString("\tfor _, stmt := range q.stmts {\n")
			code.WriteString("\t\tif err := stmt.Close(); err != nil {\n")
			code.WriteString("\t\t\treturn err\n")
			code.WriteString("\t\t}\n")
			code.WriteString("\t}\n")
			code.WriteString("\tq.stmts = make(map[string]*sql.Stmt)\n")
			code.WriteString("\treturn nil\n")
			code.WriteString("}\n\n")
		}
	}

	dbPath := filepath.Join(g.Config.Gen.Go.Out, "db.go")
	return os.WriteFile(dbPath, []byte(code.String()), 0644)
}

func (g *Generator) expandWildcardColumns(query *parser.Query) []*parser.QueryColumn {
	if g.expander == nil {
		g.expander = gencommon.NewSchemaExpander(g.schema)
	}
	cols := g.expander.ExpandWildcardColumns(query)
	return cols
}

func (g *Generator) generateQueryMethod(code *strings.Builder, query *parser.Query) error {
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"
	if isScylla {
		return g.generateGocqlQueryMethod(code, query)
	}
	if g.Config.Gen.Go.Driver == "pgx" {
		return g.generatePGXQueryMethod(code, query)
	}
	return g.generateSQLQueryMethod(code, query)
}

// modelTypeForQuery returns the model struct name if the query columns exactly match
// a table in the schema — enabling reuse of the model type instead of a duplicate *Row struct.
func (g *Generator) modelTypeForQuery(query *parser.Query, columns []*parser.QueryColumn) string {
	return g.expander.ModelTypeForQuery(query, columns)
}

func (g *Generator) generateSQLQueryMethod(code *strings.Builder, query *parser.Query) error {
	columns := g.expandWildcardColumns(query)
	methodName := utils.ToPascalCase(query.Name)
	rowTypeName := methodName + "Row"
	if mt := g.modelTypeForQuery(query, columns); mt != "" {
		rowTypeName = mt
	}

	useStructParams := len(query.Params) > 2

	if useStructParams && len(query.Params) > 0 {
		code.WriteString(fmt.Sprintf("type %sParams struct {\n", methodName))
		for _, param := range query.Params {
			fieldName := utils.ToPascalCase(param.Name)
			goType := g.mapParamTypeToGo(param.Type)
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, utils.SafeGoIdent(utils.ToSnakeCase(param.Name))))
		}
		code.WriteString("}\n\n")
	}

	cmd := strings.ToLower(query.Cmd)
	isModifying := utils.IsModifyingQuery(query.SQL)

	code.WriteString(fmt.Sprintf("func (q *Queries) %s(", methodName))

	if len(query.Params) > 0 {
		if useStructParams {
			code.WriteString(fmt.Sprintf("arg %sParams", methodName))
		} else {
			paramList := []string{}
			for _, param := range query.Params {
				paramName := utils.SafeGoIdent(utils.ToSnakeCase(param.Name))
				goType := g.mapParamTypeToGo(param.Type)
				paramList = append(paramList, fmt.Sprintf("%s %s", paramName, goType))
			}
			code.WriteString(strings.Join(paramList, ", "))
		}
	}

	code.WriteString(") (")

	switch {
	case cmd == ":one":
		if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("%s, error", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
		} else {
			code.WriteString(fmt.Sprintf("%s, error", rowTypeName))
		}
	case cmd == ":many":
		if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("[]%s, error", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
		} else {
			code.WriteString(fmt.Sprintf("[]%s, error", rowTypeName))
		}
	case cmd == ":exec" || isModifying:
		code.WriteString("error")
	case cmd == ":execresult":
		code.WriteString("sql.Result, error")
	default:
		code.WriteString("error")
	}

	code.WriteString(") {\n")

	cleanSQL := strings.TrimSpace(query.SQL)
	// Handle backticks in SQL by splitting the raw string literal
	if strings.Contains(cleanSQL, "`") {
		parts := strings.Split(cleanSQL, "`")
		code.WriteString("\tconst query = `")
		for i, part := range parts {
			if i > 0 {
				code.WriteString("` + \"`\" + `")
			}
			code.WriteString(part)
		}
		code.WriteString("`\n")
	} else {
		code.WriteString(fmt.Sprintf("\tconst query = `%s`\n", cleanSQL))
	}

	isHotQuery := len(query.Params) <= 3 && !strings.Contains(strings.ToUpper(query.SQL), "UNION")
	stmtKey := fmt.Sprintf("%s_stmt", methodName)

	if isHotQuery {
		code.WriteString(fmt.Sprintf("\tstmt := q.stmts[\"%s\"]\n", stmtKey))
		code.WriteString("\tif stmt == nil {\n")
		code.WriteString("\t\tvar err error\n")
		code.WriteString("\t\tstmt, err = q.db.Prepare(query)\n")
		code.WriteString("\t\tif err != nil {\n")

		// Return appropriate zero value based on return type
		if len(columns) > 0 {
			// Query returns data (SELECT or INSERT RETURNING)
			if cmd == ":one" {
				if len(columns) == 1 {
					code.WriteString("\t\t\treturn ")
					code.WriteString(g.getZeroValue(g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
					code.WriteString(", err\n")
				} else {
					code.WriteString(fmt.Sprintf("\t\t\treturn %s{}, err\n", rowTypeName))
				}
			} else {
				// :many or default (returns slice)
				code.WriteString("\t\t\treturn nil, err\n")
			}
		} else if cmd == ":execresult" {
			code.WriteString("\t\t\treturn nil, err\n")
		} else {
			// :exec or modifying query without RETURNING
			code.WriteString("\t\t\treturn err\n")
		}

		code.WriteString("\t\t}\n")
		code.WriteString(fmt.Sprintf("\t\tq.stmts[\"%s\"] = stmt\n", stmtKey))
		code.WriteString("\t}\n")
	}

	if len(query.Params) > 0 {
		code.WriteString("\targs := []interface{}{")
		for i, param := range query.Params {
			if i > 0 {
				code.WriteString(", ")
			}
			if useStructParams {
				code.WriteString(fmt.Sprintf("arg.%s", utils.ToPascalCase(param.Name)))
			} else {
				code.WriteString(utils.SafeGoIdent(utils.ToSnakeCase(param.Name)))
			}
		}
		code.WriteString("}\n")
	}

	switch {
	case cmd == ":one":
		if len(columns) == 0 {
			code.WriteString("\n\treturn nil, fmt.Errorf(\"query has no return columns\")\n")
		} else if len(columns) > 1 {
			code.WriteString(fmt.Sprintf("\n\tvar result %s\n", rowTypeName))
			if isHotQuery {
				code.WriteString("\trows, err := stmt.Query(")
				if len(query.Params) > 0 {
					code.WriteString("args...")
				}
			} else {
				code.WriteString("\trows, err := q.db.Query(query")
				if len(query.Params) > 0 {
					code.WriteString(", args...")
				}
			}
			code.WriteString(")\n")
			code.WriteString("\tif err != nil {\n")
			code.WriteString("\t\treturn result, err\n")
			code.WriteString("\t}\n")
			code.WriteString("\tdefer rows.Close()\n")
			code.WriteString("\tif !rows.Next() {\n")
			code.WriteString("\t\tif err := rows.Err(); err != nil {\n")
			code.WriteString("\t\t\treturn result, err\n")
			code.WriteString("\t\t}\n")
			code.WriteString("\t\treturn result, sql.ErrNoRows\n")
			code.WriteString("\t}\n")
			code.WriteString("\terr = rows.Scan(")
			for i, col := range columns {
				if i > 0 {
					code.WriteString(", ")
				}
				code.WriteString(fmt.Sprintf("&result.%s", utils.ToPascalCase(col.Name)))
			}
			code.WriteString(")\n")
			code.WriteString("\treturn result, err\n")
		} else {
			code.WriteString("\n\tvar result ")
			code.WriteString(g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable))
			if isHotQuery {
				code.WriteString("\n\trows, err := stmt.Query(")
				if len(query.Params) > 0 {
					code.WriteString("args...")
				}
			} else {
				code.WriteString("\n\trows, err := q.db.Query(query")
				if len(query.Params) > 0 {
					code.WriteString(", args...")
				}
			}
			code.WriteString(")\n")
			code.WriteString("\tif err != nil {\n")
			code.WriteString("\t\treturn result, err\n")
			code.WriteString("\t}\n")
			code.WriteString("\tdefer rows.Close()\n")
			code.WriteString("\tif !rows.Next() {\n")
			code.WriteString("\t\tif err := rows.Err(); err != nil {\n")
			code.WriteString("\t\t\treturn result, err\n")
			code.WriteString("\t\t}\n")
			code.WriteString("\t\treturn result, sql.ErrNoRows\n")
			code.WriteString("\t}\n")
			code.WriteString("\terr = rows.Scan(&result)\n")
			code.WriteString("\treturn result, err\n")
		}

	case cmd == ":many":
		if len(columns) == 0 {
			code.WriteString("\n\treturn nil, fmt.Errorf(\"query has no return columns\")\n")
		} else {
			if isHotQuery {
				code.WriteString("\n\trows, err := stmt.Query(")
				if len(query.Params) > 0 {
					code.WriteString("args...")
				}
			} else {
				code.WriteString("\n\trows, err := q.db.Query(query")
				if len(query.Params) > 0 {
					code.WriteString(", args...")
				}
			}
			code.WriteString(")\n")
			code.WriteString("\tif err != nil {\n")
			code.WriteString("\t\treturn nil, err\n")
			code.WriteString("\t}\n")
			code.WriteString("\tdefer rows.Close()\n\n")

			if len(columns) > 1 {
				code.WriteString(fmt.Sprintf("\titems := make([]%s, 0, 8) \n", rowTypeName))
			} else {
				code.WriteString(fmt.Sprintf("\titems := make([]%s, 0, 8) \n", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
			}

			code.WriteString("\tfor rows.Next() {\n")
			if len(columns) > 1 {
				code.WriteString(fmt.Sprintf("\t\tvar item %s\n", rowTypeName))
				code.WriteString("\t\tif err := rows.Scan(")
				for i, col := range columns {
					if i > 0 {
						code.WriteString(", ")
					}
					code.WriteString(fmt.Sprintf("&item.%s", utils.ToPascalCase(col.Name)))
				}
				code.WriteString("); err != nil {\n")
				code.WriteString("\t\t\treturn nil, err\n")
				code.WriteString("\t\t}\n")
				code.WriteString("\t\titems = append(items, item)\n")
			} else {
				code.WriteString("\t\tvar item ")
				code.WriteString(g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable))
				code.WriteString("\n\t\tif err := rows.Scan(&item); err != nil {\n")
				code.WriteString("\t\t\treturn nil, err\n")
				code.WriteString("\t\t}\n")
				code.WriteString("\t\titems = append(items, item)\n")
			}
			code.WriteString("\t}\n")
			code.WriteString("\treturn items, rows.Err()\n")
		}

	case cmd == ":execresult":
		if isHotQuery {
			code.WriteString("\n\treturn stmt.Exec(")
			if len(query.Params) > 0 {
				code.WriteString("args...")
			}
		} else {
			code.WriteString("\n\treturn q.db.Exec(query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
		}
		code.WriteString(")\n")

	default:
		if isHotQuery {
			code.WriteString("\n\t_, err := stmt.Exec(")
			if len(query.Params) > 0 {
				code.WriteString("args...")
			}
		} else {
			code.WriteString("\n\t_, err := q.db.Exec(query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
		}
		code.WriteString(")\n")
		code.WriteString("\treturn err\n")
	}

	code.WriteString("}\n\n")

	if (cmd == ":one" || cmd == ":many") && len(columns) > 1 && rowTypeName == methodName+"Row" {
		code.WriteString(fmt.Sprintf("type %sRow struct {\n", methodName))
		for _, col := range columns {
			if col.Name == "*" || strings.HasPrefix(col.Name, "/*") {
				continue
			}
			fieldName := utils.ToPascalCase(col.Name)
			// Gocql Row types use value types not pointers (assigned via fmt.Sprint)
			goType := g.mapSQLTypeToGo(col.Type, false)
			if col.JsonDef != nil {
				goType = "*" + col.JsonDef.Name
			}
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, utils.ToSnakeCase(col.Name)))
		}
		code.WriteString("}\n\n")
	}

	return nil
}

func (g *Generator) mapSQLTypeToGo(sqlType string, nullable bool) string {
	sqlTypeLower := strings.ToLower(sqlType)

	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sqlTypeLower {
				enumType := utils.ToPascalCase(enum.Name)
				if nullable {
					if isScylla {
						return "*" + enumType
					}
					return "sql.NullString"
				}
				return enumType
			}
		}
	}

	if strings.HasPrefix(sqlTypeLower, "enum(") {
		if nullable {
			if isScylla {
				return "*string"
			}
			return "sql.NullString"
		}
		return "string"
	}

	baseType := ""
	switch {
	// ScyllaDB/Cassandra CQL types — check before generic contains-based cases
	case sqlTypeLower == "uuid":
		if isScylla {
			baseType = "gocql.UUID"
		} else {
			baseType = "uuid.UUID"
		}
	case sqlTypeLower == "timeuuid":
		if isScylla {
			baseType = "gocql.UUID"
		} else {
			baseType = "uuid.UUID"
		}
	case sqlTypeLower == "inet":
		baseType = "string"
	case sqlTypeLower == "varint":
		baseType = "int64"
	case sqlTypeLower == "counter":
		baseType = "int64"
	case sqlTypeLower == "duration":
		baseType = "int64"
	// ScyllaDB/Cassandra collection types — must be before generic string/int checks
	case strings.HasPrefix(sqlTypeLower, "set<"), strings.HasPrefix(sqlTypeLower, "list<"):
		// Extract element type and map to []GoType
		inner := gencommon.ExtractCollectionInner(sqlTypeLower)
		elemGo := g.mapSQLTypeToGo(inner, false)
		if nullable && isScylla {
			return "*[]" + elemGo
		}
		return "[]" + elemGo
	case strings.HasPrefix(sqlTypeLower, "map<"):
		// map<key,value> → map[KeyType]ValueType
		k, v := gencommon.ExtractMapTypes(sqlTypeLower)
		kGo := g.mapSQLTypeToGo(k, false)
		vGo := g.mapSQLTypeToGo(v, false)
		if nullable && isScylla {
			return fmt.Sprintf("*map[%s]%s", kGo, vGo)
		}
		return fmt.Sprintf("map[%s]%s", kGo, vGo)
	case strings.HasPrefix(sqlTypeLower, "frozen<"):
		// frozen<type> — unwrap and check for UDT
		inner := gencommon.ExtractCollectionInner(sqlTypeLower)
		if isScylla && g.schema != nil {
			for _, udt := range g.schema.UDTs {
				bareName := udt.Name
				if _, after, ok := strings.CutLast(udt.Name, "."); ok {
					bareName = after
				}
				if strings.EqualFold(bareName, inner) || strings.EqualFold(udt.Name, inner) {
					goName := utils.ToPascalCase(bareName)
					if nullable {
						return "*" + goName
					}
					return goName
				}
			}
		}
		// frozen<tuple<...>> or other frozen types → string
		baseType = "string"
	case strings.HasPrefix(sqlTypeLower, "tuple<"):
		baseType = "string"
	case strings.Contains(sqlTypeLower, "int"):
		baseType = "int64"
	case strings.Contains(sqlTypeLower, "serial"):
		baseType = "int64"
	// PostgreSQL range types — must be before contains("int")
	case strings.HasSuffix(sqlTypeLower, "range"):
		baseType = "string" // int4range, int8range, numrange, tsrange etc. serialize as "[a,b)"
	case sqlTypeLower == "inet" || sqlTypeLower == "cidr" || sqlTypeLower == "macaddr":
		baseType = "string"
	case sqlTypeLower == "bytea":
		baseType = "[]byte"
	case strings.Contains(sqlTypeLower, "float") || strings.Contains(sqlTypeLower, "double") || strings.Contains(sqlTypeLower, "numeric") || strings.Contains(sqlTypeLower, "decimal"):
		baseType = "float64"
	case strings.Contains(sqlTypeLower, "bool"):
		baseType = "bool"
	case strings.Contains(sqlTypeLower, "time") || strings.Contains(sqlTypeLower, "date"):
		baseType = "time.Time"
	case sqlTypeLower == "interval":
		baseType = "time.Duration"
	case strings.Contains(sqlTypeLower, "jsonb") || strings.Contains(sqlTypeLower, "json"):
		if g.Config.Gen.Go.Driver == "pgx" {
			baseType = "map[string]interface{}"
		} else {
			baseType = "[]byte"
		}
	// ─── PostgreSQL Extension Types ───────────────────────────────────────
	case sqlTypeLower == "vector" || strings.HasPrefix(sqlTypeLower, "vector("):
		baseType = "[]float32" // pgvector
	case sqlTypeLower == "halfvec" || strings.HasPrefix(sqlTypeLower, "halfvec("):
		baseType = "[]float32"
	case sqlTypeLower == "hstore":
		baseType = "map[string]string"
	case sqlTypeLower == "tsvector" || sqlTypeLower == "tsquery":
		baseType = "string"
	case sqlTypeLower == "ltree" || sqlTypeLower == "lquery" || sqlTypeLower == "ltxtquery":
		baseType = "string"
	case sqlTypeLower == "money":
		baseType = "string"
	case sqlTypeLower == "xml":
		baseType = "string"
	case sqlTypeLower == "pg_lsn":
		baseType = "string"
	case sqlTypeLower == "bit" || strings.HasPrefix(sqlTypeLower, "bit(") ||
		sqlTypeLower == "varbit" || strings.HasPrefix(sqlTypeLower, "varbit(") ||
		strings.HasPrefix(sqlTypeLower, "bit varying"):
		baseType = "string"
	case sqlTypeLower == "point" || sqlTypeLower == "line" || sqlTypeLower == "lseg" ||
		sqlTypeLower == "box" || sqlTypeLower == "path" || sqlTypeLower == "polygon" || sqlTypeLower == "circle":
		baseType = "string"
	case sqlTypeLower == "geometry" || strings.HasPrefix(sqlTypeLower, "geometry(") ||
		sqlTypeLower == "geography" || strings.HasPrefix(sqlTypeLower, "geography("):
		baseType = "string" // PostGIS WKT/WKB
	case strings.HasSuffix(sqlTypeLower, "[]"):
		// Array types: TEXT[], INTEGER[], etc.
		elemType := strings.TrimSuffix(sqlTypeLower, "[]")
		elemGo := g.mapSQLTypeToGo(elemType, false)
		return "[]" + elemGo
	case strings.Contains(sqlTypeLower, "uuid"):
		if isScylla {
			baseType = "gocql.UUID"
		} else {
			baseType = "uuid.UUID" // github.com/google/uuid
		}
	// ClickHouse-specific types
	case sqlTypeLower == "uint8", sqlTypeLower == "uint16", sqlTypeLower == "uint32", sqlTypeLower == "uint64":
		baseType = "uint64"
	case sqlTypeLower == "int8", sqlTypeLower == "int16", sqlTypeLower == "int32", sqlTypeLower == "int64":
		baseType = "int64"
	case sqlTypeLower == "float32":
		baseType = "float32"
	case sqlTypeLower == "float64":
		baseType = "float64"
	case sqlTypeLower == "string", strings.HasPrefix(sqlTypeLower, "fixedstring"):
		baseType = "string"
	case strings.HasPrefix(sqlTypeLower, "nullable("):
		inner := sqlTypeLower[9 : len(sqlTypeLower)-1]
		return g.mapSQLTypeToGo(inner, true)
	default:
		// Check if bare CQL UDT name (not wrapped in frozen<>)
		if isScylla && g.schema != nil {
			for _, udt := range g.schema.UDTs {
				bareName := udt.Name
				if _, after, ok := strings.CutLast(udt.Name, "."); ok {
					bareName = after
				}
				if strings.EqualFold(bareName, sqlTypeLower) || strings.EqualFold(udt.Name, sqlTypeLower) {
					goName := utils.ToPascalCase(bareName)
					if nullable {
						return "*" + goName
					}
					return goName
				}
			}
		}
		baseType = "string"
	}
	provider = g.Config.Database.Provider
	isScylla = provider == "scylla" || provider == "scylladb" || provider == "cassandra"
	if nullable {
		if isScylla {
			// gocql uses pointer types for nullable columns, not sql.Null*
			return "*" + baseType
		}
		switch baseType {
		case "int64":
			return "sql.NullInt64"
		case "float64":
			return "sql.NullFloat64"
		case "bool":
			return "sql.NullBool"
		case "string":
			return "sql.NullString"
		case "time.Time":
			return "sql.NullTime"
		default:
			return "*" + baseType
		}
	}
	return baseType
}

func (g *Generator) mapParamTypeToGo(paramType string) string {
	if strings.Contains(paramType, "|") {
		parts := strings.Split(paramType, "|")
		paramType = strings.TrimSpace(parts[0])
	}

	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.EqualFold(enum.Name, paramType) {
				return utils.ToPascalCase(enum.Name)
			}
		}
	}

	// For gocql, collection types map to []ElemType
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"
	if isScylla {
		lower := strings.ToLower(paramType)
		if strings.HasPrefix(lower, "set<") || strings.HasPrefix(lower, "list<") {
			inner := gencommon.ExtractCollectionInner(lower)
			elemGo := g.mapSQLTypeToGo(inner, false)
			return "[]" + elemGo
		}
	}

	return g.mapSQLTypeToGo(paramType, false)
}

func (g *Generator) mapColumnTypeToGo(colType string, nullable bool) string {
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"
	if g.enumTypeMap != nil {
		if enumName, ok := g.enumTypeMap[strings.ToLower(colType)]; ok {
			typeName := utils.ToPascalCase(enumName)
			if nullable {
				if isScylla {
					return "*" + typeName
				}
				return "sql.NullString"
			}
			return typeName
		}
	}
	return g.mapSQLTypeToGo(colType, nullable)
}

// mapSQLTypeToGoWithEnumMap maps SQL types to Go types using enum type map for MySQL inline ENUMs
func (g *Generator) mapSQLTypeToGoWithEnumMap(sqlType string, nullable bool, enumTypeMap map[string]string) string {
	sqlTypeLower := strings.ToLower(sqlType)

	if enumName, ok := enumTypeMap[sqlTypeLower]; ok {
		typeName := utils.ToPascalCase(enumName)
		if nullable {
			provider := g.Config.Database.Provider
			if provider == "scylla" || provider == "scylladb" || provider == "cassandra" {
				return "*" + typeName
			}
			return "sql.NullString"
		}
		return typeName
	}

	return g.mapSQLTypeToGo(sqlType, nullable)
}

// getZeroValue returns the zero value for a given Go type
func (g *Generator) getZeroValue(goType string) string {
	switch {
	case strings.HasPrefix(goType, "[]"):
		return "nil"
	case strings.Contains(goType, "sql.Null"):
		return goType + "{}"
	case goType == "string":
		return `""`
	case goType == "int", goType == "int32", goType == "int64", goType == "float32", goType == "float64":
		return "0"
	case goType == "bool":
		return "false"
	case strings.Contains(goType, "time.Time"):
		return "time.Time{}"
	default:
		return goType + "{}"
	}
}

// extractInlineEnums extracts MySQL inline ENUM types and adds them to schema
func (g *Generator) extractInlineEnums() map[string]string {
	enumTypeMap := make(map[string]string)

	if g.schema == nil {
		return enumTypeMap
	}

	for _, table := range g.schema.Tables {
		for _, col := range table.Columns {
			colTypeLower := strings.ToLower(col.Type)
			if strings.HasPrefix(colTypeLower, "enum(") {
				values := gencommon.ExtractEnumValues(col.Type)
				if len(values) > 0 {
					enumName := fmt.Sprintf("%s_%s", table.Name, col.Name)

					enumTypeMap[colTypeLower] = enumName

					g.schema.Enums = append(g.schema.Enums, &parser.Enum{
						Name:   enumName,
						Values: values,
					})
				}
			}
		}
	}

	return enumTypeMap
}

// resolveWildcardViewColumns returns nil for SELECT * views — the struct will be empty
// but won't generate an invalid `* *string` field.
func (g *Generator) resolveWildcardViewColumns(viewName string) []*parser.Column {
	return nil
}

func (g *Generator) generateGocqlQueryMethod(code *strings.Builder, query *parser.Query) error {
	columns := g.expandWildcardColumns(query)
	methodName := utils.ToPascalCase(query.Name)
	rowTypeName := methodName + "Row"
	if mt := g.modelTypeForQuery(query, columns); mt != "" {
		rowTypeName = mt
	}
	useStructParams := len(query.Params) > 2

	cmd := strings.ToLower(query.Cmd)
	hasReturning := strings.Contains(strings.ToUpper(query.SQL), "RETURNING")

	// CQL does not support RETURNING — treat as :exec but return the inserted row
	// by re-reading params (we know what we inserted).
	if hasReturning {
		cmd = ":exec"
	}

	if useStructParams && len(query.Params) > 0 {
		code.WriteString(fmt.Sprintf("type %sParams struct {\n", methodName))
		for _, param := range query.Params {
			fieldName := utils.ToPascalCase(param.Name)
			goType := g.mapParamTypeToGo(param.Type)
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, utils.SafeGoIdent(utils.ToSnakeCase(param.Name))))
		}
		code.WriteString("}\n\n")
	}

	// Signature
	code.WriteString(fmt.Sprintf("func (q *Queries) %s(ctx context.Context, ", methodName))
	if len(query.Params) > 0 {
		if useStructParams {
			code.WriteString(fmt.Sprintf("arg %sParams", methodName))
		} else {
			var parts []string
			for _, param := range query.Params {
				parts = append(parts, fmt.Sprintf("%s %s", utils.SafeGoIdent(utils.ToSnakeCase(param.Name)), g.mapParamTypeToGo(param.Type)))
			}
			code.WriteString(strings.Join(parts, ", "))
		}
	}
	code.WriteString(") (")
	switch cmd {
	case ":one":
		if len(columns) == 0 {
			code.WriteString("error")
		} else if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("%s, error", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
		} else {
			code.WriteString(fmt.Sprintf("%s, error", rowTypeName))
		}
	case ":many":
		if len(columns) == 0 {
			code.WriteString("error")
		} else if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("[]%s, error", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
		} else {
			code.WriteString(fmt.Sprintf("[]%s, error", rowTypeName))
		}
	default:
		code.WriteString("error")
	}
	code.WriteString(") {\n")

	// SQL constant — strip RETURNING, handle BATCH for multi-statement
	cleanSQL := strings.TrimSpace(query.SQL)
	if idx := strings.LastIndex(strings.ToUpper(cleanSQL), "RETURNING"); idx >= 0 {
		cleanSQL = strings.TrimSpace(cleanSQL[:idx])
	}
	// Multi-statement → BATCH
	stmts := splitCQLStatements(cleanSQL)
	if len(stmts) > 1 {
		var batch strings.Builder
		batch.WriteString("BEGIN BATCH\n")
		for _, s := range stmts {
			batch.WriteString("\t" + strings.TrimSpace(s) + ";\n")
		}
		batch.WriteString("APPLY BATCH")
		cleanSQL = batch.String()
	}

	code.WriteString(fmt.Sprintf("\tconst query = `%s`\n", cleanSQL))

	// Args
	// Only declare args if we'll actually use them (not in zero-column :many fallback)
	needsArgs := len(query.Params) > 0 && !(cmd == ":many" && len(columns) == 0)
	if needsArgs {
		code.WriteString("\targs := []interface{}{")
		for i, param := range query.Params {
			if i > 0 {
				code.WriteString(", ")
			}
			if useStructParams {
				code.WriteString("arg." + utils.ToPascalCase(param.Name))
			} else {
				code.WriteString(utils.SafeGoIdent(utils.ToSnakeCase(param.Name)))
			}
		}
		code.WriteString("}\n")
	}

	// Body
	switch cmd {
	case ":one":
		if len(columns) == 0 {
			// No columns — fallback exec
			code.WriteString("\treturn q.exec(ctx, query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(")\n")
		} else if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("\n\tvar result %s\n", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
			code.WriteString("\tif err := q.db.Query(query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(").WithContext(ctx).Scan(&result); err != nil {\n")
			code.WriteString(fmt.Sprintf("\t\treturn %s, err\n", gocqlZero(g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable))))
			code.WriteString("\t}\n\treturn result, nil\n")
		} else {
			code.WriteString(fmt.Sprintf("\n\tvar result %s\n", rowTypeName))
			code.WriteString("\terr := q.db.Query(query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(").WithContext(ctx).Scan(\n")
			for _, col := range columns {
				code.WriteString(fmt.Sprintf("\t\t&result.%s,\n", utils.ToPascalCase(col.Name)))
			}
			code.WriteString("\t)\n")
			code.WriteString("\tif err != nil {\n\t\treturn result, err\n\t}\n")
			code.WriteString("\treturn result, nil\n")
		}
	case ":many":
		if len(columns) == 0 {
			code.WriteString("\treturn q.exec(ctx, query)\n")
		} else if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("\n\tvar items []%s\n", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
			code.WriteString("\titer := q.db.Query(query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(").WithContext(ctx).Iter()\n")
			code.WriteString(fmt.Sprintf("\tvar v %s\n", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
			code.WriteString("\tfor iter.Scan(&v) {\n\t\titems = append(items, v)\n\t}\n")
			code.WriteString("\treturn items, iter.Close()\n")
		} else {
			code.WriteString(fmt.Sprintf("\n\tvar items []%s\n", rowTypeName))
			code.WriteString("\titer := q.db.Query(query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(").WithContext(ctx).Iter()\n")
			code.WriteString(fmt.Sprintf("\tvar item %s\n", rowTypeName))
			code.WriteString("\tfor iter.Scan(\n")
			for _, col := range columns {
				code.WriteString(fmt.Sprintf("\t\t&item.%s,\n", utils.ToPascalCase(col.Name)))
			}
			code.WriteString("\t) {\n\t\titems = append(items, item)\n\t}\n")
			code.WriteString("\treturn items, iter.Close()\n")
		}
	default:
		code.WriteString("\n\treturn q.exec(ctx, query")
		if len(query.Params) > 0 {
			code.WriteString(", args...")
		}
		code.WriteString(")\n")
	}
	code.WriteString("}\n\n")

	// Row struct
	if (cmd == ":one" || cmd == ":many") && len(columns) > 1 && rowTypeName == methodName+"Row" {
		code.WriteString(fmt.Sprintf("type %sRow struct {\n", methodName))
		for _, col := range columns {
			goType := g.mapSQLTypeToGo(col.Type, false)
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", utils.ToPascalCase(col.Name), goType, utils.ToSnakeCase(col.Name)))
		}
		code.WriteString("}\n\n")
	}

	return nil
}

// splitCQLStatements splits multiple CQL statements (separated by ;) for BATCH wrapping.
func splitCQLStatements(sql string) []string {
	var stmts []string
	for s := range strings.SplitSeq(sql, ";") {
		if s = strings.TrimSpace(s); s != "" {
			stmts = append(stmts, s)
		}
	}
	return stmts
}

// gocqlZero returns the zero value expression for a Go type (for early-return on error).
func gocqlZero(goType string) string {
	switch {
	case goType == "string":
		return `""`
	case goType == "bool":
		return "false"
	case strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") || strings.HasPrefix(goType, "*"):
		return "nil"
	case goType == "int64" || goType == "float64":
		return "0"
	case goType == "time.Time":
		return "time.Time{}"
	default:
		return goType + "{}"
	}
}

func (g *Generator) generatePGXQueryMethod(code *strings.Builder, query *parser.Query) error {
	columns := g.expandWildcardColumns(query)
	methodName := utils.ToPascalCase(query.Name)
	rowTypeName := methodName + "Row"
	if mt := g.modelTypeForQuery(query, columns); mt != "" {
		rowTypeName = mt
	}
	useStructParams := len(query.Params) > 2

	if useStructParams && len(query.Params) > 0 {
		code.WriteString(fmt.Sprintf("type %sParams struct {\n", methodName))
		for _, param := range query.Params {
			fieldName := utils.ToPascalCase(param.Name)
			goType := g.mapParamTypeToGo(param.Type)
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, utils.SafeGoIdent(utils.ToSnakeCase(param.Name))))
		}
		code.WriteString("}\n\n")
	}

	cmd := strings.ToLower(query.Cmd)
	isModifying := utils.IsModifyingQuery(query.SQL)

	code.WriteString(fmt.Sprintf("func (q *Queries) %s(ctx context.Context, ", methodName))

	if len(query.Params) > 0 {
		if useStructParams {
			code.WriteString(fmt.Sprintf("arg %sParams", methodName))
		} else {
			paramList := []string{}
			for _, param := range query.Params {
				paramName := utils.SafeGoIdent(utils.ToSnakeCase(param.Name))
				goType := g.mapParamTypeToGo(param.Type)
				paramList = append(paramList, fmt.Sprintf("%s %s", paramName, goType))
			}
			code.WriteString(strings.Join(paramList, ", "))
		}
	}

	code.WriteString(") (")

	switch {
	case cmd == ":one":
		if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("%s, error", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
		} else {
			code.WriteString(fmt.Sprintf("%s, error", rowTypeName))
		}
	case cmd == ":many":
		if len(columns) == 1 {
			code.WriteString(fmt.Sprintf("[]%s, error", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
		} else {
			code.WriteString(fmt.Sprintf("[]%s, error", rowTypeName))
		}
	case cmd == ":exec" || isModifying:
		code.WriteString("error")
	case cmd == ":execresult":
		code.WriteString("(pgconn.CommandTag, error)")
	default:
		code.WriteString("error")
	}

	code.WriteString(") {\n")

	cleanSQL := strings.TrimSpace(query.SQL)
	if strings.Contains(cleanSQL, "`") {
		parts := strings.Split(cleanSQL, "`")
		code.WriteString("\tconst query = `")
		for i, part := range parts {
			if i > 0 {
				code.WriteString("` + \"`\" + `")
			}
			code.WriteString(part)
		}
		code.WriteString("`\n")
	} else {
		code.WriteString(fmt.Sprintf("\tconst query = `%s`\n", cleanSQL))
	}

	if len(query.Params) > 0 {
		code.WriteString("\targs := []interface{}{")
		for i, param := range query.Params {
			if i > 0 {
				code.WriteString(", ")
			}
			if useStructParams {
				code.WriteString(fmt.Sprintf("arg.%s", utils.ToPascalCase(param.Name)))
			} else {
				code.WriteString(utils.SafeGoIdent(utils.ToSnakeCase(param.Name)))
			}
		}
		code.WriteString("}\n")
	}

	switch {
	case cmd == ":one":
		if len(columns) == 0 {
			code.WriteString("\n\treturn nil, fmt.Errorf(\"query has no return columns\")\n")
		} else if len(columns) > 1 {
			code.WriteString(fmt.Sprintf("\n\tvar result %s\n", rowTypeName))
			code.WriteString("\trow := q.db.QueryRow(ctx, query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(")\n")
			code.WriteString("\terr := row.Scan(")
			for i, col := range columns {
				if i > 0 {
					code.WriteString(", ")
				}
				code.WriteString(fmt.Sprintf("&result.%s", utils.ToPascalCase(col.Name)))
			}
			code.WriteString(")\n")
			code.WriteString("\treturn result, err\n")
		} else {
			code.WriteString("\n\tvar result ")
			code.WriteString(g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable))
			code.WriteString("\n\trow := q.db.QueryRow(ctx, query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(")\n")
			code.WriteString("\terr := row.Scan(&result)\n")
			code.WriteString("\treturn result, err\n")
		}

	case cmd == ":many":
		if len(columns) == 0 {
			code.WriteString("\n\treturn nil, fmt.Errorf(\"query has no return columns\")\n")
		} else {
			code.WriteString("\n\trows, err := q.db.Query(ctx, query")
			if len(query.Params) > 0 {
				code.WriteString(", args...")
			}
			code.WriteString(")\n")
			code.WriteString("\tif err != nil {\n")
			code.WriteString("\t\treturn nil, err\n")
			code.WriteString("\t}\n")
			code.WriteString("\tdefer rows.Close()\n\n")

			if len(columns) > 1 {
				code.WriteString(fmt.Sprintf("\titems := make([]%s, 0, 8) \n", rowTypeName))
			} else {
				code.WriteString(fmt.Sprintf("\titems := make([]%s, 0, 8) \n", g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable)))
			}

			code.WriteString("\tfor rows.Next() {\n")
			if len(columns) > 1 {
				code.WriteString(fmt.Sprintf("\t\tvar item %s\n", rowTypeName))
				code.WriteString("\t\tif err := rows.Scan(")
				for i, col := range columns {
					if i > 0 {
						code.WriteString(", ")
					}
					code.WriteString(fmt.Sprintf("&item.%s", utils.ToPascalCase(col.Name)))
				}
				code.WriteString("); err != nil {\n")
				code.WriteString("\t\t\treturn nil, err\n")
				code.WriteString("\t\t}\n")
				code.WriteString("\t\titems = append(items, item)\n")
			} else {
				code.WriteString("\t\tvar item ")
				code.WriteString(g.mapColumnTypeToGo(columns[0].Type, columns[0].Nullable))
				code.WriteString("\n\t\tif err := rows.Scan(&item); err != nil {\n")
				code.WriteString("\t\t\treturn nil, err\n")
				code.WriteString("\t\t}\n")
				code.WriteString("\t\titems = append(items, item)\n")
			}
			code.WriteString("\t}\n")
			code.WriteString("\treturn items, rows.Err()\n")
		}

	case cmd == ":execresult":
		code.WriteString("\n\treturn q.db.Exec(ctx, query")
		if len(query.Params) > 0 {
			code.WriteString(", args...")
		}
		code.WriteString(")\n")

	default:
		code.WriteString("\n\t_, err := q.db.Exec(ctx, query")
		if len(query.Params) > 0 {
			code.WriteString(", args...")
		}
		code.WriteString(")\n")
		code.WriteString("\treturn err\n")
	}

	code.WriteString("}\n\n")

	if (cmd == ":one" || cmd == ":many") && len(columns) > 1 && rowTypeName == methodName+"Row" {
		code.WriteString(fmt.Sprintf("type %sRow struct {\n", methodName))
		for _, col := range columns {
			if col.Name == "*" || strings.HasPrefix(col.Name, "/*") {
				continue
			}
			fieldName := utils.ToPascalCase(col.Name)
			goType := g.mapColumnTypeToGo(col.Type, col.Nullable)
			code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, utils.ToSnakeCase(col.Name)))
		}
		code.WriteString("}\n\n")
	}

	return nil
}
