package gogen

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

// generateQueriesIncremental generates queries with incremental support
func (g *Generator) generateQueriesIncremental(queries []*parser.Query, fullRegen bool) error {
	queryGroups := make(map[string][]*parser.Query)
	for _, query := range queries {
		sourceFile := query.SourceFile
		if sourceFile == "" {
			sourceFile = "queries"
		}
		queryGroups[sourceFile] = append(queryGroups[sourceFile], query)
	}

	// Convert map to slice for parallel processing
	type fileGroup struct {
		sourceFile string
		queries    []*parser.Query
	}

	fileGroups := make([]fileGroup, 0, len(queryGroups))
	for sourceFile, fileQueries := range queryGroups {
		fileGroups = append(fileGroups, fileGroup{sourceFile, fileQueries})
	}

	// Track used names across parallel workers (thread-safe)
	usedNames := make(map[string]int)
	var usedNamesMu sync.Mutex

	// Parallel code generation with worker pool
	numWorkers := min(runtime.NumCPU(), len(fileGroups))

	type generateResult struct {
		err error
	}

	workChan := make(chan fileGroup, len(fileGroups))
	resultChan := make(chan generateResult, len(fileGroups))

	var wg sync.WaitGroup
	for i := 0; i < numWorkers; i++ {
		wg.Go(func() {
			for fg := range workChan {
				err := g.generateSingleFile(fg.sourceFile, fg.queries, fullRegen, &usedNamesMu, usedNames)
				resultChan <- generateResult{err: err}
			}
		})
	}

	// Send work to workers
	for _, fg := range fileGroups {
		workChan <- fg
	}
	close(workChan)

	// Wait for completion
	go func() {
		wg.Wait()
		close(resultChan)
	}()

	// Collect results and check for errors
	for result := range resultChan {
		if result.err != nil {
			return result.err
		}
	}

	return nil
}

// generateSingleFile generates code for a single query file (thread-safe)
func (g *Generator) generateSingleFile(sourceFile string, fileQueries []*parser.Query, fullRegen bool, usedNamesMu *sync.Mutex, usedNames map[string]int) error {
	queryFile := filepath.Join(g.Config.Queries, sourceFile+".sql")
	currentHash, _ := gencommon.ComputeFileChecksum(queryFile)

	// The skip decision must consider this generator's own output file so a
	// shared cache entry from another language cannot suppress generation.
	primaryOutput := filepath.Join(g.Config.Gen.Go.Out, strings.TrimSuffix(sourceFile, ".sql")+".go")
	if !gencommon.ShouldRegenerateFileForOutput(g.cache, queryFile, currentHash, fullRegen, primaryOutput) {
		gencommon.PrintSkipMessage(sourceFile, ".go")
		return nil
	}

	gencommon.PrintGenerateMessage(sourceFile, ".go")

	// Use pooled string builder
	code := gencommon.GetBuilder()
	defer gencommon.PutBuilder(code)

	code.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	code.WriteString(fmt.Sprintf("package %s\n\n", filepath.Base(g.Config.Gen.Go.Out)))

	needsTime, needsSQL, needsPGConn := false, false, false
	isPGX := g.Config.Gen.Go.Driver == "pgx"
	isScylla := g.Config.Database.Provider == "scylla" || g.Config.Database.Provider == "scylladb" || g.Config.Database.Provider == "cassandra"
	isGocql := g.Config.Gen.Go.Driver == "gocql"
	needsGocqlImport := false
	needsUUIDImport := false
	for _, query := range fileQueries {
		for _, col := range query.Columns {
			colType := g.mapColumnTypeToGo(col.Type, col.Nullable)
			if strings.Contains(colType, "time.Time") {
				needsTime = true
			}
			if strings.Contains(colType, "sql.Null") {
				needsSQL = true
			}
			if strings.Contains(colType, "gocql.UUID") {
				needsGocqlImport = true
			}
			if strings.Contains(colType, "uuid.UUID") {
				needsUUIDImport = true
			}
		}
		for _, param := range query.Params {
			pt := g.mapParamTypeToGo(param.Type)
			if strings.Contains(pt, "time.Time") {
				needsTime = true
			}
			if strings.Contains(pt, "gocql.UUID") {
				needsGocqlImport = true
			}
			if strings.Contains(pt, "uuid.UUID") {
				needsUUIDImport = true
			}
		}
		if strings.ToLower(query.Cmd) == ":one" && !isPGX && !isScylla {
			needsSQL = true
		}
		if strings.ToLower(query.Cmd) == ":execresult" && isPGX {
			needsPGConn = true
		}
	}

	imports := []string{}
	if isScylla {
		imports = append(imports, "\"context\"")
		if needsGocqlImport {
			if isGocql {
				imports = append(imports, "\"github.com/gocql/gocql\"")
			} else {
				imports = append(imports, "\"github.com/apache/cassandra-gocql-driver/v2\"")
			}
		}
	} else if isPGX {
		imports = append(imports, "\"context\"")
	}
	if needsSQL {
		imports = append(imports, "\"database/sql\"")
	}
	if needsTime {
		imports = append(imports, "\"time\"")
	}
	if needsUUIDImport {
		imports = append(imports, "\"github.com/google/uuid\"")
	}
	if needsPGConn {
		imports = append(imports, "\"github.com/jackc/pgx/v5/pgconn\"")
	}

	if len(imports) > 0 {
		code.WriteString("import (\n")
		for _, imp := range imports {
			code.WriteString(fmt.Sprintf("\t%s\n", imp))
		}
		code.WriteString(")\n\n")
	}

	// Generate JSON type structs from @json annotations
	emittedJsonTypes := make(map[string]bool)
	for _, query := range fileQueries {
		for _, jt := range query.JsonTypes {
			if emittedJsonTypes[jt.Name] {
				continue
			}
			emittedJsonTypes[jt.Name] = true
			code.WriteString(fmt.Sprintf("// %s represents the JSON structure for the '%s' column.\n", jt.Name, jt.Column))
			code.WriteString(fmt.Sprintf("// Unmarshal with: json.Unmarshal([]byte(row.%s), &obj)\n", utils.ToPascalCase(jt.Column)))
			code.WriteString(fmt.Sprintf("type %s struct {\n", jt.Name))
			for _, field := range jt.Fields {
				goType := jsonFieldToGoType(field)
				code.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", utils.ToPascalCase(field.Name), goType, field.Name))
			}
			code.WriteString("}\n\n")
		}
	}

	for _, query := range fileQueries {
		if err := g.generateQueryMethod(code, query); err != nil {
			return err
		}
	}

	baseName := strings.TrimSuffix(strings.TrimSuffix(sourceFile, ".sql"), ".cql")

	// Thread-safe name deduplication
	usedNamesMu.Lock()
	outputFile := baseName + ".go"
	if count, exists := usedNames[baseName]; exists {
		usedNames[baseName] = count + 1
		outputFile = fmt.Sprintf("%s_%d.go", baseName, count+1)
	} else {
		usedNames[baseName] = 1
	}
	usedNamesMu.Unlock()

	queriesPath := filepath.Join(g.Config.Gen.Go.Out, outputFile)
	if err := os.WriteFile(queriesPath, []byte(code.String()), 0644); err != nil {
		return err
	}

	tableDeps := gencommon.ExtractTableDependencies(fileQueries)
	gencommon.UpdateCacheForFile(g.cache, queryFile, currentHash, tableDeps, queriesPath)

	return nil
}

// jsonFieldToGoType converts a JsonField type to its Go representation.
func jsonFieldToGoType(field *parser.JsonField) string {
	prefix := "*" // nullable pointer
	if !field.Nullable {
		prefix = ""
	}
	switch field.Type {
	case "string":
		return prefix + "string"
	case "int":
		return prefix + "int64"
	case "float":
		return prefix + "float64"
	case "boolean":
		return prefix + "bool"
	case "string[]":
		return "[]string"
	case "int[]":
		return "[]int64"
	case "float[]":
		return "[]float64"
	case "boolean[]":
		return "[]bool"
	case "any":
		return "interface{}"
	default:
		return prefix + field.Type
	}
}
