// Code generated by FlashORM. DO NOT EDIT.

package flash_gen

import (
	"database/sql"
)

type DBTX interface {
	Exec(query string, args ...interface{}) (sql.Result, error)
	Prepare(query string) (*sql.Stmt, error)
	Query(query string, args ...interface{}) (*sql.Rows, error)
	QueryRow(query string, args ...interface{}) *sql.Row
}

func Newq(db DBTX) *Queries {
	return &Queries{
		db:    db,
		stmts: make(map[string]*sql.Stmt),
	}
}

type Queries struct {
	db    DBTX
	stmts map[string]*sql.Stmt
}

func (q *Queries) Close() error {
	for _, stmt := range q.stmts {
		if err := stmt.Close(); err != nil {
			return err
		}
	}
	q.stmts = make(map[string]*sql.Stmt)
	return nil
}
