// Code generated by FlashORM. DO NOT EDIT.

package flash_gen

import (
	"database/sql"
	"time"
)

// Preferences represents the JSON structure for the 'preferences' column.
// Unmarshal with: json.Unmarshal([]byte(row.Preferences), &obj)
type Preferences struct {
	Notifications *bool   `json:"notifications"`
	Language      *string `json:"language"`
	FontSize      *int64  `json:"font_size"`
	Theme         *string `json:"theme"`
}

// Metadata represents the JSON structure for the 'metadata' column.
// Unmarshal with: json.Unmarshal([]byte(row.Metadata), &obj)
type Metadata struct {
	Views       *int64   `json:"views"`
	Shares      *int64   `json:"shares"`
	Bookmarks   *int64   `json:"bookmarks"`
	AvgReadTime *float64 `json:"avg_read_time"`
	TagsUsed    []string `json:"tags_used"`
}

func (q *Queries) Getuserprefs(id int64) (GetuserprefsRow, error) {
	const query = `SELECT id, name, email, preferences FROM users WHERE id = $1;`
	stmt := q.stmts["Getuserprefs_stmt"]
	if stmt == nil {
		var err error
		stmt, err = q.db.Prepare(query)
		if err != nil {
			return GetuserprefsRow{}, err
		}
		q.stmts["Getuserprefs_stmt"] = stmt
	}
	args := []interface{}{id}

	var result GetuserprefsRow
	rows, err := stmt.Query(args...)
	if err != nil {
		return result, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, err
		}
		return result, sql.ErrNoRows
	}
	err = rows.Scan(&result.Id, &result.Name, &result.Email, &result.Preferences)
	return result, err
}

type GetuserprefsRow struct {
	Id          int64        `json:"id"`
	Name        string       `json:"name"`
	Email       string       `json:"email"`
	Preferences *Preferences `json:"preferences"`
}

func (q *Queries) Setuserprefs(preferences []byte, id int64) (SetuserprefsRow, error) {
	const query = `UPDATE users SET preferences = $1, updated_at = NOW() WHERE id = $2 RETURNING id, name, preferences, updated_at;`
	stmt := q.stmts["Setuserprefs_stmt"]
	if stmt == nil {
		var err error
		stmt, err = q.db.Prepare(query)
		if err != nil {
			return SetuserprefsRow{}, err
		}
		q.stmts["Setuserprefs_stmt"] = stmt
	}
	args := []interface{}{preferences, id}

	var result SetuserprefsRow
	rows, err := stmt.Query(args...)
	if err != nil {
		return result, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, err
		}
		return result, sql.ErrNoRows
	}
	err = rows.Scan(&result.Id, &result.Name, &result.Preferences, &result.UpdatedAt)
	return result, err
}

type SetuserprefsRow struct {
	Id          int64        `json:"id"`
	Name        string       `json:"name"`
	Preferences *Preferences `json:"preferences"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

func (q *Queries) Getpostmeta(id int64) (GetpostmetaRow, error) {
	const query = `SELECT id, title, status, metadata, user_id, created_at FROM posts WHERE id = $1;`
	stmt := q.stmts["Getpostmeta_stmt"]
	if stmt == nil {
		var err error
		stmt, err = q.db.Prepare(query)
		if err != nil {
			return GetpostmetaRow{}, err
		}
		q.stmts["Getpostmeta_stmt"] = stmt
	}
	args := []interface{}{id}

	var result GetpostmetaRow
	rows, err := stmt.Query(args...)
	if err != nil {
		return result, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, err
		}
		return result, sql.ErrNoRows
	}
	err = rows.Scan(&result.Id, &result.Title, &result.Status, &result.Metadata, &result.UserId, &result.CreatedAt)
	return result, err
}

type GetpostmetaRow struct {
	Id        int64      `json:"id"`
	Title     string     `json:"title"`
	Status    PostStatus `json:"status"`
	Metadata  *Metadata  `json:"metadata"`
	UserId    int64      `json:"user_id"`
	CreatedAt time.Time  `json:"created_at"`
}

func (q *Queries) Listuserswithprefs(limit int64) ([]ListuserswithprefsRow, error) {
	const query = `SELECT id, name, email, preferences, created_at FROM users ORDER BY created_at DESC LIMIT $1;`
	stmt := q.stmts["Listuserswithprefs_stmt"]
	if stmt == nil {
		var err error
		stmt, err = q.db.Prepare(query)
		if err != nil {
			return nil, err
		}
		q.stmts["Listuserswithprefs_stmt"] = stmt
	}
	args := []interface{}{limit}

	rows, err := stmt.Query(args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]ListuserswithprefsRow, 0, 8)
	for rows.Next() {
		var item ListuserswithprefsRow
		if err := rows.Scan(&item.Id, &item.Name, &item.Email, &item.Preferences, &item.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

type ListuserswithprefsRow struct {
	Id          int64        `json:"id"`
	Name        string       `json:"name"`
	Email       string       `json:"email"`
	Preferences *Preferences `json:"preferences"`
	CreatedAt   time.Time    `json:"created_at"`
}

func (q *Queries) Listpostswithmeta(user_id int64) ([]ListpostswithmetaRow, error) {
	const query = `SELECT id, title, status, view_count, metadata, created_at FROM posts WHERE user_id = $1 AND status = 'published' ORDER BY created_at DESC;`
	stmt := q.stmts["Listpostswithmeta_stmt"]
	if stmt == nil {
		var err error
		stmt, err = q.db.Prepare(query)
		if err != nil {
			return nil, err
		}
		q.stmts["Listpostswithmeta_stmt"] = stmt
	}
	args := []interface{}{user_id}

	rows, err := stmt.Query(args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]ListpostswithmetaRow, 0, 8)
	for rows.Next() {
		var item ListpostswithmetaRow
		if err := rows.Scan(&item.Id, &item.Title, &item.Status, &item.ViewCount, &item.Metadata, &item.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

type ListpostswithmetaRow struct {
	Id        int64      `json:"id"`
	Title     string     `json:"title"`
	Status    PostStatus `json:"status"`
	ViewCount int64      `json:"view_count"`
	Metadata  *Metadata  `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
}
