package javagen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/cachegen"
	"github.com/Lumos-Labs-HQ/flash/internal/config"
	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

type Generator struct {
	Config       *config.Config
	schema       *parser.Schema
	schemaParser *parser.SchemaParser
	queryParser  *parser.QueryParser
	cache        *gencommon.GenerationCache
	expander     *gencommon.SchemaExpander
}

func New(cfg *config.Config) *Generator {
	cache := gencommon.NewGenerationCacheWithDir(cfg.Gen.Java.Out)
	return &Generator{
		Config:       cfg,
		schemaParser: parser.NewSchemaParser(cfg),
		queryParser:  parser.NewQueryParser(cfg),
		cache:        cache,
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Config.Gen.Java.Out, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	schema, err := g.schemaParser.Parse()
	if err != nil {
		return fmt.Errorf("failed to parse schema: %w", err)
	}
	g.schema = schema
	g.expander = gencommon.NewSchemaExpander(schema)

	schemaHash, _ := g.cache.ComputeSchemaChecksum(g.Config.SchemaDir)
	configHash := fmt.Sprintf("%x", []byte(fmt.Sprintf("%s|%s|%s", g.Config.Database.Provider, g.Config.Gen.Java.Out, g.Config.Gen.Java.Driver)))
	fullRegen := g.Config.ForceRegen || g.cache.ShouldRegenerateAll(schemaHash, configHash)

	queries, err := g.queryParser.Parse(schema)
	if err != nil {
		return fmt.Errorf("failed to parse queries: %w", err)
	}

	// Remove cache entries and generated files for query sources that no
	// longer exist (deleted or renamed .sql/.cql files), mirroring gogen.
	// Java per-source output files are named PascalCase(base) + "Queries.java";
	// Row/Params classes are keyed off query names, not the source file, so
	// they are handled by the normal regeneration path.
	pruned := g.cache.PruneStaleQueryEntries(g.Config.Queries)
	for _, source := range pruned {
		base := strings.TrimSuffix(filepath.Base(source), filepath.Ext(source))
		orphan := filepath.Join(g.Config.Gen.Java.Out, utils.ToPascalCase(base)+"Queries.java")
		if err := os.Remove(orphan); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove orphaned output %s: %w", orphan, err)
		}
	}

	// Models/DB regen must also fire when this generator's own canonical
	// output is missing — a shared cache file (same out dir, multiple
	// languages) can otherwise carry a matching schema checksum written by
	// another generator, suppressing model generation entirely.
	if _, err := os.Stat(filepath.Join(g.Config.Gen.Java.Out, "Queries.java")); os.IsNotExist(err) {
		fullRegen = true
	}
	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateModels(); err != nil {
			return err
		}
		if err := g.generateDB(queries); err != nil {
			return err
		}
	}

	if err := g.generateQueriesIncremental(queries, fullRegen); err != nil {
		return err
	}
	if err := g.generateMigrations(); err != nil {
		return err
	}

	// Generate cache layer if enabled
	if g.Config.Cache.Enabled {
		if err := g.generateCacheFiles(queries); err != nil {
			return err
		}
	}

	g.cache.UpdateSchemaChecksum(schemaHash)
	g.cache.UpdateConfigChecksum(configHash)
	g.cache.MarkGeneration()
	_ = g.cache.Save()
	return nil
}

func (g *Generator) generateCacheFiles(queries []*parser.Query) error {
	pkgName := g.Config.Gen.Java.Package
	if pkgName == "" {
		pkgName = "flashgen"
	}

	// Generate FlashCache.java
	cacheCode := cachegen.GenerateJavaCache(&g.Config.Cache, pkgName)
	cachePath := filepath.Join(g.Config.Gen.Java.Out, "FlashCache.java")
	if err := os.WriteFile(cachePath, []byte(cacheCode), 0644); err != nil {
		return fmt.Errorf("failed to write FlashCache.java: %w", err)
	}

	// Resolve cache annotations
	caches := cachegen.ResolveCacheQueries(queries, &g.Config.Cache)

	// Validate dep references
	if warnings := cachegen.ValidateDeps(caches, queries); len(warnings) > 0 {
		for _, w := range warnings {
			fmt.Printf("⚠️  %s\n", w)
		}
	}

	// Generate CacheAccessors.java
	accessorCode := cachegen.GenerateJavaCacheAccessors(caches, pkgName)
	if accessorCode == "" {
		accessorCode = fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\npackage %s;\n\n// No @cache annotations found.\n", pkgName)
	}
	accessorPath := filepath.Join(g.Config.Gen.Java.Out, "CacheAccessors.java")
	if err := os.WriteFile(accessorPath, []byte(accessorCode), 0644); err != nil {
		return fmt.Errorf("failed to write CacheAccessors.java: %w", err)
	}

	// Generate CachedQueries.java
	cachedCode := g.generateCachedQueries(queries, caches, pkgName)
	cachedPath := filepath.Join(g.Config.Gen.Java.Out, "CachedQueries.java")
	if err := os.WriteFile(cachedPath, []byte(cachedCode), 0644); err != nil {
		return fmt.Errorf("failed to write CachedQueries.java: %w", err)
	}

	return nil
}

func (g *Generator) generateCachedQueries(queries []*parser.Query, caches []*cachegen.CacheInfo, pkgName string) string {
	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString(fmt.Sprintf("package %s;\n\n", pkgName))
	w.WriteString("import java.sql.Connection;\n\n")
	w.WriteString("/**\n * Cache-wrapped queries and auto-purge mutations.\n */\n")
	w.WriteString("public class CachedQueries {\n")
	w.WriteString("    private final Queries queries;\n\n")
	w.WriteString("    public CachedQueries(Connection conn) {\n")
	w.WriteString("        this.queries = Queries.newq(conn);\n")
	w.WriteString("    }\n\n")

	hasContent := false
	for _, q := range queries {
		if cachegen.IsCachedQuery(q) && !cachegen.IsMutationQuery(q) {
			g.writeJavaCachedQuery(&w, q, caches)
			hasContent = true
		} else if cachegen.IsMutationQuery(q) {
			purges := cachegen.ResolveDependencyPurges(q.Name, caches, q.Params)
			if len(purges) > 0 {
				g.writeJavaPurgingMutation(&w, q, purges)
				hasContent = true
			}
		}
	}

	w.WriteString("}\n")

	if !hasContent {
		return fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\npackage %s;\n\n// No cached queries or auto-purge mutations.\n", pkgName)
	}
	return w.String()
}

func (g *Generator) writeJavaCachedQuery(w *strings.Builder, q *parser.Query, caches []*cachegen.CacheInfo) {
	cacheInfo := cachegen.GetCacheInfoForQuery(q.Name, caches)
	if cacheInfo == nil {
		return
	}
	ttlSec := cachegen.ParseTTL(cacheInfo.TTL)

	var params, callArgs []string
	for _, p := range q.Params {
		params = append(params, fmt.Sprintf("Object %s", p.Name))
		callArgs = append(callArgs, p.Name)
	}
	paramStr := strings.Join(params, ", ")

	var keyExpr string
	if len(callArgs) == 0 {
		keyExpr = fmt.Sprintf("\"%s\"", cacheInfo.CacheName)
	} else {
		keyExpr = fmt.Sprintf("\"%s:\" + %s", cacheInfo.CacheName, strings.Join(callArgs, " + \":\" + "))
	}

	fnName := q.Name + "Cached"
	w.WriteString(fmt.Sprintf("    /** %s (cached, TTL: %s) */\n", q.Name, cacheInfo.TTL))
	w.WriteString(fmt.Sprintf("    public <T> T %s(%s, Class<T> clazz) {\n", fnName, paramStr))
	w.WriteString(fmt.Sprintf("        String key = %s;\n", keyExpr))
	w.WriteString("        T cached = FlashCache.get(key, clazz);\n")
	w.WriteString("        if (cached != null) return cached;\n\n")
	w.WriteString(fmt.Sprintf("        Object result = queries.%s(%s);\n", q.Name, strings.Join(callArgs, ", ")))
	w.WriteString(fmt.Sprintf("        FlashCache.set(key, result, %d);\n", ttlSec))
	w.WriteString("        @SuppressWarnings(\"unchecked\")\n")
	w.WriteString("        T typed = (T) result;\n")
	w.WriteString("        return typed;\n")
	w.WriteString("    }\n\n")
}

func (g *Generator) writeJavaPurgingMutation(w *strings.Builder, q *parser.Query, purges []cachegen.DependencyPurge) {
	var params, callArgs []string
	for _, p := range q.Params {
		params = append(params, fmt.Sprintf("Object %s", p.Name))
		callArgs = append(callArgs, p.Name)
	}
	paramStr := strings.Join(params, ", ")

	fnName := q.Name + "AndPurge"
	w.WriteString(fmt.Sprintf("    /** %s (auto-purges dependent caches) */\n", q.Name))
	w.WriteString(fmt.Sprintf("    public void %s(%s) {\n", fnName, paramStr))
	w.WriteString(fmt.Sprintf("        queries.%s(%s);\n\n", q.Name, strings.Join(callArgs, ", ")))
	w.WriteString("        // Auto-purge dependent caches\n")
	for _, purge := range purges {
		if purge.PurgePrefix {
			w.WriteString(fmt.Sprintf("        FlashCache.purgeByPrefix(\"%s:\");\n", purge.CacheName))
		} else {
			w.WriteString(fmt.Sprintf("        FlashCache.del(\"%s:\" + %s);\n", purge.CacheName, purge.KeyParam))
		}
	}
	w.WriteString("    }\n\n")
}

// javaPackage returns the package name: config value takes priority over dir name.
func javaPackage(cfg *config.JavaGen) string {
	if cfg.Package != "" {
		return cfg.Package
	}
	base := filepath.Base(cfg.Out)
	return strings.ReplaceAll(strings.ToLower(base), "-", "_")
}

func (g *Generator) generateModels() error {
	pkg := javaPackage(&g.Config.Gen.Java)
	header := fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\n\npackage %s;\n\n", pkg)

	needsUUID := func(cols []*parser.Column) bool {
		for _, c := range cols {
			if g.sqlTypeToJava(c.Type, false) == "UUID" {
				return true
			}
		}
		return false
	}
	needsLDT := func(cols []*parser.Column) bool {
		for _, c := range cols {
			if g.sqlTypeToJava(c.Type, false) == "LocalDateTime" {
				return true
			}
		}
		return false
	}

	// One file per enum
	for _, enum := range g.schema.Enums {
		name := utils.ToPascalCase(enum.Name)
		var w strings.Builder
		w.WriteString(header)
		w.WriteString(fmt.Sprintf("public enum %s {\n", name))
		for i, v := range enum.Values {
			sep := ","
			if i == len(enum.Values)-1 {
				sep = ";"
			}
			w.WriteString(fmt.Sprintf("    %s%s\n", strings.ToUpper(v), sep))
		}
		w.WriteString("}\n")
		if err := os.WriteFile(filepath.Join(g.Config.Gen.Java.Out, name+".java"), []byte(w.String()), 0644); err != nil {
			return err
		}
		if genHash, err := gencommon.ComputeFileChecksum(filepath.Join(g.Config.Gen.Java.Out, name+".java")); err == nil {
			g.cache.UpdateGeneratedFileChecksum(filepath.Join(g.Config.Gen.Java.Out, name+".java"), genHash)
		}
	}

	// One file per record
	for _, table := range g.schema.Tables {
		tableName := table.Name
		if _, after, ok := strings.CutLast(tableName, "."); ok {
			tableName = after
		}
		name := utils.ToPascalCase(tableName)
		var w strings.Builder
		w.WriteString(header)
		if needsUUID(table.Columns) {
			w.WriteString("import java.util.UUID;\n")
		}
		if needsLDT(table.Columns) {
			w.WriteString("import java.time.LocalDateTime;\n")
		}
		w.WriteString("\n")
		w.WriteString(fmt.Sprintf("public record %s(\n", name))
		cols := table.Columns
		for i, col := range cols {
			if col.Name == "*" {
				continue
			}
			jt := g.sqlTypeToJava(col.Type, col.Nullable)
			sep := ","
			if i == len(cols)-1 {
				sep = ""
			}
			w.WriteString(fmt.Sprintf("    %s %s%s\n", jt, col.Name, sep))
		}
		w.WriteString(") {}\n")
		if err := os.WriteFile(filepath.Join(g.Config.Gen.Java.Out, name+".java"), []byte(w.String()), 0644); err != nil {
			return err
		}
		if genHash, err := gencommon.ComputeFileChecksum(filepath.Join(g.Config.Gen.Java.Out, name+".java")); err == nil {
			g.cache.UpdateGeneratedFileChecksum(filepath.Join(g.Config.Gen.Java.Out, name+".java"), genHash)
		}
	}

	return nil
}

func (g *Generator) generateDB(queries []*parser.Query) error {
	pkg := javaPackage(&g.Config.Gen.Java)
	driver := g.Config.Gen.Java.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	// Collect unique source files
	seen := map[string]bool{}
	var files []string
	for _, q := range queries {
		src := q.SourceFile
		if src == "" {
			src = "queries"
		}
		base := strings.TrimSuffix(src, ".sql")
		if !seen[base] {
			seen[base] = true
			files = append(files, base)
		}
	}

	var connType, connParam, connImport string
	switch {
	case isScylla:
		connImport = "import com.datastax.oss.driver.api.core.CqlSession;\n"
		connType = "CqlSession"
		connParam = "session"
	case driver == "jooq":
		connImport = "import org.jooq.DSLContext;\n"
		connType = "DSLContext"
		connParam = "ctx"
	case driver == "hibernate":
		connImport = "import jakarta.persistence.EntityManager;\n"
		connType = "EntityManager"
		connParam = "em"
	default:
		connImport = "import java.sql.Connection;\n"
		connType = "Connection"
		connParam = "conn"
	}

	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s;\n\n", pkg))
	// Scan all queries for types needing imports
	needsUUID, needsLDT := false, false
	for _, q := range queries {
		for _, p := range q.Params {
			jt := g.sqlTypeToJava(p.Type, false)
			if jt == "UUID" {
				needsUUID = true
			}
			if jt == "LocalDateTime" {
				needsLDT = true
			}
		}
	}
	if needsUUID {
		w.WriteString("import java.util.UUID;\n")
	}
	if needsLDT {
		w.WriteString("import java.time.LocalDateTime;\n")
	}
	w.WriteString(connImport + "\n")
	w.WriteString("/**\n * Unified query interface. Use {@code DB.newq(conn)} to obtain an instance.\n */\n")
	w.WriteString("public class Queries {\n")
	// Delegate fields — one per query file class
	for _, base := range files {
		className := utils.ToPascalCase(base) + "Queries"
		w.WriteString(fmt.Sprintf("    private final %s %s;\n", className, base))
	}
	w.WriteString("\n")
	w.WriteString(fmt.Sprintf("    Queries(%s %s) {\n", connType, connParam))
	for _, base := range files {
		className := utils.ToPascalCase(base) + "Queries"
		w.WriteString(fmt.Sprintf("        this.%s = new %s(%s);\n", base, className, connParam))
	}
	w.WriteString("    }\n\n")
	// Expose newq factory
	w.WriteString(fmt.Sprintf("    public static Queries newq(%s %s) {\n", connType, connParam))
	w.WriteString(fmt.Sprintf("        return new Queries(%s);\n", connParam))
	w.WriteString("    }\n\n")
	// Delegate all query methods
	seenMethods := make(map[string]bool)
	for _, q := range queries {
		methodName := gencommon.ToCamelCase(q.Name)
		if seenMethods[methodName] {
			continue
		}
		seenMethods[methodName] = true
		src := q.SourceFile
		if src == "" {
			src = "queries"
		}
		base := strings.TrimSuffix(src, ".sql")
		columns := g.expandWildcardColumns(q)
		cmd := strings.ToLower(q.Cmd)

		rowType := gencommon.QueryPascal(q.Name) + "Row"
		if mt := g.modelTypeForQuery(q, columns); mt != "" {
			rowType = mt
		}

		var retType string
		switch cmd {
		case ":one":
			if len(columns) == 1 {
				retType = g.sqlTypeToJava(columns[0].Type, true)
			} else if len(columns) > 1 {
				retType = rowType
			} else {
				retType = "void"
			}
		case ":many":
			if len(columns) == 1 {
				retType = fmt.Sprintf("java.util.List<%s>", g.sqlTypeToJava(columns[0].Type, false))
			} else if len(columns) > 1 {
				retType = fmt.Sprintf("java.util.List<%s>", rowType)
			} else {
				retType = "java.util.List<java.util.Map<String, Object>>"
			}
		case ":execresult":
			retType = "long"
		default:
			retType = "void"
		}

		params := make([]string, len(q.Params))
		args := make([]string, len(q.Params))
		useStructParams := len(q.Params) > 2
		for i, p := range q.Params {
			params[i] = fmt.Sprintf("%s %s", g.sqlTypeToJava(p.Type, false), p.Name)
			args[i] = p.Name
		}
		methodName = gencommon.ToCamelCase(q.Name)
		throwsClause := " throws java.sql.SQLException"
		if isScylla {
			throwsClause = ""
		}

		// Generate params record for 3+ params in the proxy class
		var paramStr, argStr string
		if useStructParams && len(q.Params) > 0 {
			recordName := gencommon.QueryPascal(q.Name) + "Params"
			paramStr = recordName + " args"
			argStr = "args"
		} else {
			paramStr = strings.Join(params, ", ")
			argStr = strings.Join(args, ", ")
		}

		retStmt := ""
		if retType != "void" {
			retStmt = "return "
		}
		w.WriteString(fmt.Sprintf("    public %s %s(%s)%s {\n",
			retType, methodName, paramStr, throwsClause))
		w.WriteString(fmt.Sprintf("        %sthis.%s.%s(%s);\n",
			retStmt, base, methodName, argStr))
		w.WriteString("    }\n\n")
	}

	w.WriteString("}\n")

	queriesPath := filepath.Join(g.Config.Gen.Java.Out, "Queries.java")
	if err := os.WriteFile(queriesPath, []byte(w.String()), 0644); err != nil {
		return err
	}
	if genHash, err := gencommon.ComputeFileChecksum(queriesPath); err == nil {
		g.cache.UpdateGeneratedFileChecksum(queriesPath, genHash)
	}
	return nil
}

func (g *Generator) generateQueryMethod(w *strings.Builder, query *parser.Query) {
	methodName := gencommon.ToCamelCase(query.Name)
	columns := g.expandWildcardColumns(query)
	cmd := strings.ToLower(query.Cmd)
	driver := g.Config.Gen.Java.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	rowType := gencommon.QueryPascal(query.Name) + "Row"
	if mt := g.modelTypeForQuery(query, columns); mt != "" {
		rowType = mt
	}

	// Return type
	var retType string
	switch cmd {
	case ":one":
		if len(columns) == 1 {
			retType = g.sqlTypeToJava(columns[0].Type, true)
		} else if len(columns) > 1 {
			retType = rowType
		} else {
			retType = "void"
		}
	case ":many":
		if len(columns) == 1 {
			retType = fmt.Sprintf("java.util.List<%s>", g.sqlTypeToJava(columns[0].Type, false))
		} else if len(columns) > 1 {
			retType = fmt.Sprintf("java.util.List<%s>", rowType)
		} else {
			retType = "java.util.List<java.util.Map<String, Object>>"
		}
	case ":execresult":
		retType = "long"
	default:
		retType = "void"
	}

	// Params
	params := make([]string, len(query.Params))
	useStructParams := len(query.Params) > 2
	paramTypeName := gencommon.QueryPascal(query.Name) + "Params"
	for i, p := range query.Params {
		params[i] = fmt.Sprintf("%s %s", g.sqlTypeToJava(p.Type, false), p.Name)
	}

	throwsClause := " throws java.sql.SQLException"
	if isScylla {
		throwsClause = ""
	}

	var paramStr string
	if useStructParams {
		paramStr = paramTypeName + " args"
	} else {
		paramStr = strings.Join(params, ", ")
	}

	w.WriteString(fmt.Sprintf("    public %s %s(%s)%s {\n", retType, methodName, paramStr, throwsClause))

	sql := strings.TrimSpace(query.SQL)
	if isScylla || driver == "" || driver == "jdbc" || driver == "jooq" || driver == "hibernate" {
		for i := 20; i >= 1; i-- {
			sql = strings.ReplaceAll(sql, fmt.Sprintf("$%d", i), "?")
		}
	}
	w.WriteString(fmt.Sprintf("        final String sql = \"\"\"\n                %s\n                \"\"\";\n", sql))

	if isScylla {
		g.generateJavaScyllaBody(w, query, columns, cmd, rowType, useStructParams)
	} else if driver == "jooq" {
		g.generateJooqBody(w, query, columns, cmd, rowType, useStructParams)
	} else if driver == "hibernate" {
		g.generateHibernateBody(w, query, columns, cmd, rowType, useStructParams)
	} else {
		g.generateJavaJDBCBody(w, query, columns, cmd, rowType, useStructParams)
	}

	w.WriteString("    }\n\n")
}

// javaTypedGetter returns the typed ResultSet getter for a SQL type, reading by column name.
func (g *Generator) javaTypedGetter(colName, sqlType string) string {
	sl := strings.ToLower(sqlType)
	// Check schema enums first
	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sl {
				javaType := utils.ToPascalCase(enum.Name)
				return fmt.Sprintf("%s.valueOf(rs.getString(\"%s\"))", javaType, colName)
			}
		}
	}
	switch {
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "uint64":
		return fmt.Sprintf("rs.getLong(\"%s\")", colName)
	case strings.Contains(sl, "int") || strings.Contains(sl, "serial") || sl == "uint8" || sl == "uint16" || sl == "uint32":
		return fmt.Sprintf("rs.getInt(\"%s\")", colName)
	case sl == "float32":
		return fmt.Sprintf("rs.getFloat(\"%s\")", colName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "numeric") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("rs.getDouble(\"%s\")", colName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("rs.getBoolean(\"%s\")", colName)
	case sl == "timeuuid" || strings.Contains(sl, "uuid"):
		return fmt.Sprintf("rs.getObject(\"%s\", java.util.UUID.class)", colName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("rs.getTimestamp(\"%s\") != null ? rs.getTimestamp(\"%s\").toLocalDateTime() : null", colName, colName)
	case sl == "bytea" || strings.Contains(sl, "blob"):
		return fmt.Sprintf("rs.getBytes(\"%s\")", colName)
	case strings.HasSuffix(sl, "[]") || strings.HasPrefix(sl, "set<") || strings.HasPrefix(sl, "list<"):
		return fmt.Sprintf("rs.getArray(\"%s\") != null ? java.util.Arrays.asList((String[]) rs.getArray(\"%s\").getArray()) : null", colName, colName)
	case strings.Contains(sl, "json"):
		return fmt.Sprintf("rs.getString(\"%s\")", colName)
	default:
		return fmt.Sprintf("rs.getString(\"%s\")", colName)
	}
}

// javaParamRef returns the parameter reference, prefixing with "args." for struct params.
func javaParamRef(name string, useStruct bool) string {
	if useStruct {
		return "args." + name + "()"
	}
	return name
}

// javaTypedSetter returns a typed PreparedStatement setter.
func javaTypedSetter(idx int, paramName, sqlType string) string {
	sl := strings.ToLower(sqlType)
	// Any SQL array type → createArrayOf
	if before, ok := strings.CutSuffix(sl, "[]"); ok {
		baseType := before
		pgType := "text"
		switch {
		case strings.Contains(baseType, "int") || strings.Contains(baseType, "serial"):
			pgType = "integer"
		case strings.Contains(baseType, "uuid"):
			pgType = "uuid"
		case strings.Contains(baseType, "bool"):
			pgType = "boolean"
		case strings.Contains(baseType, "float") || strings.Contains(baseType, "real") || strings.Contains(baseType, "double"):
			pgType = "float8"
		}
		return fmt.Sprintf("stmt.setArray(%d, conn.createArrayOf(\"%s\", %s.toArray()));", idx, pgType, paramName)
	}
	switch {
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "uint64":
		return fmt.Sprintf("stmt.setLong(%d, %s);", idx, paramName)
	case strings.Contains(sl, "int") || strings.Contains(sl, "serial") || sl == "uint8" || sl == "uint16" || sl == "uint32":
		return fmt.Sprintf("stmt.setInt(%d, %s);", idx, paramName)
	case sl == "float32":
		return fmt.Sprintf("stmt.setFloat(%d, %s);", idx, paramName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "numeric") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("stmt.setDouble(%d, %s);", idx, paramName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("stmt.setBoolean(%d, %s);", idx, paramName)
	case strings.Contains(sl, "uuid") || sl == "timeuuid":
		return fmt.Sprintf("stmt.setObject(%d, %s);", idx, paramName)
	case sl == "bytea" || strings.Contains(sl, "blob"):
		return fmt.Sprintf("stmt.setBytes(%d, %s);", idx, paramName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("stmt.setObject(%d, java.sql.Timestamp.valueOf(%s));", idx, paramName)
	case strings.Contains(sl, "text") || strings.Contains(sl, "varchar") || strings.Contains(sl, "char") || sl == "string":
		return fmt.Sprintf("stmt.setString(%d, %s);", idx, paramName)
	default:
		// enums, json, arrays — use setObject
		return fmt.Sprintf("stmt.setObject(%d, %s);", idx, paramName)
	}
}

// cqlJavaGetter returns the DataStax Java typed getter by column name.
func cqlJavaGetter(colName, sqlType string) string {
	sl := strings.ToLower(sqlType)
	switch {
	case sl == "uuid" || sl == "timeuuid":
		return fmt.Sprintf("row.getUuid(\"%s\")", colName)
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "varint" || sl == "counter":
		return fmt.Sprintf("row.getLong(\"%s\")", colName)
	case strings.Contains(sl, "int"):
		return fmt.Sprintf("row.getInt(\"%s\")", colName)
	case sl == "float32":
		return fmt.Sprintf("row.getFloat(\"%s\")", colName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("row.getDouble(\"%s\")", colName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("row.getBoolean(\"%s\")", colName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("row.getInstant(\"%s\")", colName)
	case strings.HasPrefix(sl, "set<"):
		inner, _ := gencommon.ParseCQLInner(sl)
		return fmt.Sprintf("row.getSet(\"%s\", %s.class)", colName, cqlInnerJavaClass(inner))
	case strings.HasPrefix(sl, "list<"):
		inner, _ := gencommon.ParseCQLInner(sl)
		return fmt.Sprintf("row.getList(\"%s\", %s.class)", colName, cqlInnerJavaClass(inner))
	case strings.HasPrefix(sl, "map<"):
		k, v := gencommon.ParseCQLInner(sl)
		return fmt.Sprintf("row.getMap(\"%s\", %s.class, %s.class)", colName, cqlInnerJavaClass(k), cqlInnerJavaClass(v))
	default:
		return fmt.Sprintf("row.getString(\"%s\")", colName)
	}
}

// cqlInnerJavaClass maps a CQL element type to its Java class name.
func cqlInnerJavaClass(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "uuid", "timeuuid":
		return "java.util.UUID"
	case "bigint", "counter", "varint", "int8":
		return "Long"
	case "int":
		return "Integer"
	case "float":
		return "Float"
	case "double", "decimal":
		return "Double"
	case "boolean":
		return "Boolean"
	case "timestamp", "date", "time":
		return "java.time.Instant"
	default:
		return "String"
	}
}

func (g *Generator) generateJavaJDBCBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string, useStructParams bool) {
	w.WriteString("        try (java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {\n")
	for i, p := range query.Params {
		w.WriteString("            " + javaTypedSetter(i+1, javaParamRef(p.Name, useStructParams), p.Type) + "\n")
	}
	switch cmd {
	case ":one":
		w.WriteString("            try (java.sql.ResultSet rs = stmt.executeQuery()) {\n")
		if len(columns) == 0 {
			w.WriteString("                return;\n")
		} else if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("                return rs.next() ? %s : null;\n", g.javaTypedGetter(columns[0].Name, columns[0].Type)))
		} else {
			w.WriteString("                if (!rs.next()) return null;\n")
			w.WriteString(fmt.Sprintf("                return new %s(\n", rowType))
			for i, col := range columns {
				sep := ","
				if i == len(columns)-1 {
					sep = ""
				}
				w.WriteString(fmt.Sprintf("                    %s%s\n", g.javaTypedGetter(col.Name, col.Type), sep))
			}
			w.WriteString("                );\n")
		}
		w.WriteString("            }\n")
	case ":many":
		if len(columns) == 0 {
			w.WriteString("            stmt.executeUpdate();\n")
			w.WriteString("            return java.util.Collections.emptyList();\n")
		} else if len(columns) == 1 {
			jt := g.sqlTypeToJava(columns[0].Type, false)
			w.WriteString(fmt.Sprintf("            var items = new java.util.ArrayList<%s>();\n", jt))
			w.WriteString("            try (java.sql.ResultSet rs = stmt.executeQuery()) {\n")
			w.WriteString(fmt.Sprintf("                while (rs.next()) items.add(%s);\n", g.javaTypedGetter(columns[0].Name, columns[0].Type)))
			w.WriteString("            }\n")
			w.WriteString("            return items;\n")
		} else {
			w.WriteString(fmt.Sprintf("            var items = new java.util.ArrayList<%s>();\n", rowType))
			w.WriteString("            try (java.sql.ResultSet rs = stmt.executeQuery()) {\n")
			w.WriteString("                while (rs.next()) {\n")
			w.WriteString(fmt.Sprintf("                    items.add(new %s(\n", rowType))
			for i, col := range columns {
				sep := ","
				if i == len(columns)-1 {
					sep = ""
				}
				w.WriteString(fmt.Sprintf("                        %s%s\n", g.javaTypedGetter(col.Name, col.Type), sep))
			}
			w.WriteString("                    ));\n")
			w.WriteString("                }\n")
			w.WriteString("            }\n")
			w.WriteString("            return items;\n")
		}
	case ":execresult":
		w.WriteString("            stmt.executeUpdate();\n")
		w.WriteString("            try (var gk = stmt.getGeneratedKeys()) {\n")
		w.WriteString("                return gk.next() ? gk.getLong(1) : 0L;\n")
		w.WriteString("            }\n")
	default:
		w.WriteString("            stmt.executeUpdate();\n")
	}
	w.WriteString("        }\n")
}

func (g *Generator) generateJavaScyllaBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string, useStructParams bool) {
	paramRefs := make([]string, len(query.Params))
	for i, p := range query.Params {
		paramRefs[i] = javaParamRef(p.Name, useStructParams)
	}

	execLine := "        session.execute(sql);\n"
	rsLine := "        var rs = session.execute(sql);\n"
	if len(paramRefs) > 0 {
		argsStr := strings.Join(paramRefs, ", ")
		execLine = fmt.Sprintf("        session.execute(com.datastax.oss.driver.api.core.cql.SimpleStatement.newInstance(sql, %s));\n", argsStr)
		rsLine = fmt.Sprintf("        var rs = session.execute(com.datastax.oss.driver.api.core.cql.SimpleStatement.newInstance(sql, %s));\n", argsStr)
	}

	switch cmd {
	case ":exec", ":execresult":
		w.WriteString(execLine)
	case ":one":
		w.WriteString(rsLine)
		w.WriteString("        var row = rs.one();\n")
		w.WriteString("        if (row == null) return null;\n")
		if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("        return %s;\n", cqlJavaGetter(columns[0].Name, columns[0].Type)))
		} else if len(columns) > 1 {
			w.WriteString(fmt.Sprintf("        return new %s(\n", rowType))
			for i, col := range columns {
				sep := ","
				if i == len(columns)-1 {
					sep = ""
				}
				w.WriteString(fmt.Sprintf("            %s%s\n", cqlJavaGetter(col.Name, col.Type), sep))
			}
			w.WriteString("        );\n")
		}
	case ":many":
		w.WriteString(rsLine)
		if len(columns) == 1 {
			jt := g.sqlTypeToJava(columns[0].Type, false)
			w.WriteString(fmt.Sprintf("        var items = new java.util.ArrayList<%s>();\n", jt))
			w.WriteString(fmt.Sprintf("        for (var row : rs) items.add(%s);\n", cqlJavaGetter(columns[0].Name, columns[0].Type)))
			w.WriteString("        return items;\n")
		} else if len(columns) > 1 {
			w.WriteString(fmt.Sprintf("        var items = new java.util.ArrayList<%s>();\n", rowType))
			w.WriteString("        for (var row : rs) {\n")
			w.WriteString(fmt.Sprintf("            items.add(new %s(\n", rowType))
			for i, col := range columns {
				sep := ","
				if i == len(columns)-1 {
					sep = ""
				}
				w.WriteString(fmt.Sprintf("                %s%s\n", cqlJavaGetter(col.Name, col.Type), sep))
			}
			w.WriteString("            ));\n")
			w.WriteString("        }\n")
			w.WriteString("        return items;\n")
		} else {
			w.WriteString("        return java.util.Collections.emptyList();\n")
		}
	}
}

func (g *Generator) generateJooqBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string, useStructParams bool) {
	paramRefs := make([]string, len(query.Params))
	for i, p := range query.Params {
		paramRefs[i] = javaParamRef(p.Name, useStructParams)
	}
	bindingsStr := ""
	if len(paramRefs) > 0 {
		bindingsStr = ", " + strings.Join(paramRefs, ", ")
	}
	switch cmd {
	case ":one":
		w.WriteString(fmt.Sprintf("        return ctx.fetchOne(sql%s) != null ? ctx.fetchOne(sql%s).into(%s.class) : null;\n", bindingsStr, bindingsStr, rowType))
	case ":many":
		w.WriteString(fmt.Sprintf("        return ctx.fetch(sql%s).into(%s.class);\n", bindingsStr, rowType))
	case ":execresult":
		w.WriteString(fmt.Sprintf("        return ctx.execute(sql%s);\n", bindingsStr))
	default:
		w.WriteString(fmt.Sprintf("        ctx.execute(sql%s);\n", bindingsStr))
	}
}

func (g *Generator) generateHibernateBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string, useStructParams bool) {
	w.WriteString(fmt.Sprintf("        var q = em.createNativeQuery(sql, %s.class);\n", rowType))
	for i, p := range query.Params {
		w.WriteString(fmt.Sprintf("        q.setParameter(%d, %s);\n", i+1, javaParamRef(p.Name, useStructParams)))
	}
	switch cmd {
	case ":one":
		w.WriteString(fmt.Sprintf("        return (%s) q.getSingleResult();\n", rowType))
	case ":many":
		w.WriteString("        return q.getResultList();\n")
	case ":execresult":
		w.WriteString("        return q.executeUpdate();\n")
	default:
		w.WriteString("        q.executeUpdate();\n")
	}
}

func (g *Generator) sqlTypeToJava(sqlType string, nullable bool) string {
	sqlLower := strings.ToLower(sqlType)

	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sqlLower {
				return utils.ToPascalCase(enum.Name)
			}
		}
	}

	var jt string
	switch {
	// SQL array types — must be before contains("int"), contains("uuid"), etc.
	case strings.HasSuffix(sqlLower, "[]"):
		inner := g.sqlTypeToJava(strings.TrimSuffix(sqlLower, "[]"), false)
		jt = fmt.Sprintf("java.util.List<%s>", inner)
	// CQL collections
	case strings.HasPrefix(sqlLower, "set<"):
		inner, _ := gencommon.ParseCQLInner(sqlLower)
		return fmt.Sprintf("java.util.Set<%s>", cqlInnerJavaClass(inner))
	case strings.HasPrefix(sqlLower, "list<"):
		inner, _ := gencommon.ParseCQLInner(sqlLower)
		return fmt.Sprintf("java.util.List<%s>", cqlInnerJavaClass(inner))
	case strings.HasPrefix(sqlLower, "map<"):
		k, v := gencommon.ParseCQLInner(sqlLower)
		return fmt.Sprintf("java.util.Map<%s, %s>", cqlInnerJavaClass(k), cqlInnerJavaClass(v))
	// ClickHouse exact unsigned types — must be before contains("int")
	case sqlLower == "uint8" || sqlLower == "uint16" || sqlLower == "uint32" || sqlLower == "uint64":
		if nullable {
			jt = "Long"
		} else {
			jt = "long"
		}
	// ClickHouse exact float types — must be before contains("float")
	case sqlLower == "float32":
		if nullable {
			jt = "Float"
		} else {
			jt = "float"
		}
	case sqlLower == "float64":
		if nullable {
			jt = "Double"
		} else {
			jt = "double"
		}
	case sqlLower == "string" || strings.HasPrefix(sqlLower, "fixedstring"):
		jt = "String"
	case strings.Contains(sqlLower, "bigint") || sqlLower == "int8":
		if nullable {
			jt = "Long"
		} else {
			jt = "long"
		}
	case strings.Contains(sqlLower, "int") || strings.Contains(sqlLower, "serial"):
		if nullable {
			jt = "Integer"
		} else {
			jt = "int"
		}
	case strings.Contains(sqlLower, "float"):
		if nullable {
			jt = "Float"
		} else {
			jt = "float"
		}
	case strings.Contains(sqlLower, "double") || strings.Contains(sqlLower, "numeric") || strings.Contains(sqlLower, "decimal"):
		if nullable {
			jt = "Double"
		} else {
			jt = "double"
		}
	case strings.Contains(sqlLower, "bool"):
		if nullable {
			jt = "Boolean"
		} else {
			jt = "boolean"
		}
	case sqlLower == "timeuuid":
		jt = "UUID"
	case strings.Contains(sqlLower, "timestamp") || strings.Contains(sqlLower, "date") || strings.Contains(sqlLower, "time"):
		provider := g.Config.Database.Provider
		if provider == "scylla" || provider == "scylladb" || provider == "cassandra" {
			jt = "java.time.Instant"
		} else {
			jt = "LocalDateTime"
		}
	case strings.Contains(sqlLower, "uuid"):
		jt = "UUID"
	case strings.Contains(sqlLower, "json"):
		jt = "java.util.Map<String, Object>"
	case sqlLower == "bytea" || strings.Contains(sqlLower, "blob"):
		jt = "byte[]"
	// ─── PostgreSQL Extension Types ───────────────────────────────────────
	case sqlLower == "vector" || strings.HasPrefix(sqlLower, "vector(") ||
		sqlLower == "halfvec" || strings.HasPrefix(sqlLower, "halfvec("):
		jt = "float[]" // pgvector
	case sqlLower == "hstore":
		jt = "java.util.Map<String, String>"
	case sqlLower == "interval":
		jt = "java.time.Duration"
	case sqlLower == "tsvector", sqlLower == "tsquery":
		jt = "String"
	case sqlLower == "ltree", sqlLower == "lquery", sqlLower == "ltxtquery":
		jt = "String"
	case sqlLower == "money":
		jt = "java.math.BigDecimal"
	case sqlLower == "xml":
		jt = "String"
	case sqlLower == "pg_lsn":
		jt = "String"
	case sqlLower == "bit" || strings.HasPrefix(sqlLower, "bit(") ||
		sqlLower == "varbit" || strings.HasPrefix(sqlLower, "varbit(") ||
		strings.HasPrefix(sqlLower, "bit varying"):
		jt = "String"
	case sqlLower == "inet", sqlLower == "cidr":
		jt = "String"
	case sqlLower == "macaddr", sqlLower == "macaddr8":
		jt = "String"
	case sqlLower == "point", sqlLower == "line", sqlLower == "lseg",
		sqlLower == "box", sqlLower == "path", sqlLower == "polygon", sqlLower == "circle":
		jt = "String"
	case sqlLower == "geometry" || strings.HasPrefix(sqlLower, "geometry(") ||
		sqlLower == "geography" || strings.HasPrefix(sqlLower, "geography("):
		jt = "String" // PostGIS WKT
	case strings.HasSuffix(sqlLower, "range") || strings.HasSuffix(sqlLower, "multirange"):
		jt = "String"
	default:
		jt = "String"
	}
	return jt
}

func (g *Generator) expandWildcardColumns(query *parser.Query) []*parser.QueryColumn {
	if g.expander == nil {
		g.expander = gencommon.NewSchemaExpander(g.schema)
	}
	cols := g.expander.ExpandWildcardColumns(query)
	return cols
}

func (g *Generator) modelTypeForQuery(query *parser.Query, columns []*parser.QueryColumn) string {
	if g.expander == nil {
		g.expander = gencommon.NewSchemaExpander(g.schema)
	}
	return g.expander.ModelTypeForQuery(query, columns)
}
