package javagen

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

func (g *Generator) generateQueriesIncremental(queries []*parser.Query, fullRegen bool) error {
	queryGroups := make(map[string][]*parser.Query)
	for _, query := range queries {
		src := query.SourceFile
		if src == "" {
			src = "queries"
		}
		queryGroups[src] = append(queryGroups[src], query)
	}

	type fileGroup struct {
		src     string
		queries []*parser.Query
	}
	groups := make([]fileGroup, 0, len(queryGroups))
	for src, qs := range queryGroups {
		groups = append(groups, fileGroup{src, qs})
	}

	usedNames := make(map[string]int)
	var mu sync.Mutex

	numWorkers := min(runtime.NumCPU(), len(groups))

	workCh := make(chan fileGroup, len(groups))
	errCh := make(chan error, len(groups))
	var wg sync.WaitGroup

	for i := 0; i < numWorkers; i++ {
		wg.Go(func() {
			for fg := range workCh {
				errCh <- g.generateSingleJavaFile(fg.src, fg.queries, fullRegen, &mu, usedNames)
			}
		})
	}
	for _, fg := range groups {
		workCh <- fg
	}
	close(workCh)
	go func() { wg.Wait(); close(errCh) }()
	for err := range errCh {
		if err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateSingleJavaFile(src string, queries []*parser.Query, fullRegen bool, mu *sync.Mutex, usedNames map[string]int) error {
	queryFile := filepath.Join(g.Config.Queries, src+".sql")
	currentHash, _ := gencommon.ComputeFileChecksum(queryFile)

	// The skip decision must consider this generator's own output file so a
	// shared cache entry from another language cannot suppress generation.
	primaryOutput := filepath.Join(g.Config.Gen.Java.Out, utils.ToPascalCase(strings.TrimSuffix(src, ".sql"))+"Queries.java")
	if !gencommon.ShouldRegenerateFileForOutput(g.cache, queryFile, currentHash, fullRegen, primaryOutput) {
		gencommon.PrintSkipMessage(src, ".java")
		return nil
	}
	gencommon.PrintGenerateMessage(src, ".java")

	w := gencommon.GetBuilder()
	defer gencommon.PutBuilder(w)

	pkg := javaPackage(&g.Config.Gen.Java)
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s;\n\n", pkg))

	needsUUID, needsLocalDateTime := false, false
	for _, q := range queries {
		for _, col := range q.Columns {
			jt := g.sqlTypeToJava(col.Type, false)
			if jt == "UUID" {
				needsUUID = true
			}
			if jt == "LocalDateTime" {
				needsLocalDateTime = true
			}
		}
		for _, param := range q.Params {
			jt := g.sqlTypeToJava(param.Type, false)
			if jt == "UUID" {
				needsUUID = true
			}
			if jt == "LocalDateTime" {
				needsLocalDateTime = true
			}
		}
	}
	if needsUUID {
		w.WriteString("import java.util.UUID;\n")
	}
	if needsLocalDateTime {
		w.WriteString("import java.time.LocalDateTime;\n")
	}

	driver := g.Config.Gen.Java.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	var connImport, connType, connParam string
	switch {
	case isScylla:
		connImport = "import com.datastax.oss.driver.api.core.CqlSession;\n"
		connType = "CqlSession"
		connParam = "session"
	case driver == "jooq":
		connImport = "import org.jooq.DSLContext;\n"
		connType = "DSLContext"
		connParam = "ctx"
	case driver == "hibernate":
		connImport = "import jakarta.persistence.EntityManager;\n"
		connType = "EntityManager"
		connParam = "em"
	default:
		connImport = "import java.sql.Connection;\n"
		connType = "Connection"
		connParam = "conn"
	}
	w.WriteString(connImport + "\n")

	// Generate JSON type record files from @json annotations
	emittedJsonTypes := make(map[string]bool)
	for _, q := range queries {
		for _, jt := range q.JsonTypes {
			if emittedJsonTypes[jt.Name] {
				continue
			}
			emittedJsonTypes[jt.Name] = true
			var jw strings.Builder
			jw.WriteString(fmt.Sprintf("package %s;\n\n", javaPackage(&g.Config.Gen.Java)))
			jw.WriteString(fmt.Sprintf("/**\n * JSON type for column '%s'.\n", jt.Column))
			jw.WriteString(fmt.Sprintf(" * Parse with: new Gson().fromJson(jsonString, %s.class)\n */\n", jt.Name))
			jw.WriteString(fmt.Sprintf("public record %s(\n", jt.Name))
			for i, field := range jt.Fields {
				javaType := jsonFieldToJavaType(field)
				sep := ","
				if i == len(jt.Fields)-1 {
					sep = ""
				}
				jw.WriteString(fmt.Sprintf("    %s %s%s\n", javaType, gencommon.ToCamelCase(field.Name), sep))
			}
			jw.WriteString(") {}\n")
			jsonFile := filepath.Join(g.Config.Gen.Java.Out, jt.Name+".java")
			if err := os.WriteFile(jsonFile, []byte(jw.String()), 0644); err != nil {
				return err
			}
		}
	}

	// Emit each Row type as its own top-level .java file
	for _, q := range queries {
		columns := g.expandWildcardColumns(q)
		cmd := strings.ToLower(q.Cmd)
		rowType := gencommon.QueryPascal(q.Name) + "Row"
		if mt := g.modelTypeForQuery(q, columns); mt != "" {
			continue // uses existing model type, no Row file needed
		}
		if !((cmd == ":one" || cmd == ":many") && len(columns) > 1) {
			continue
		}
		var rw strings.Builder
		rw.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
		rw.WriteString(fmt.Sprintf("package %s;\n\n", pkg))
		needsU, needsLDT := false, false
		realCols := make([]*parser.QueryColumn, 0, len(columns))
		for _, col := range columns {
			if col.Name == "*" {
				continue
			}
			realCols = append(realCols, col)
			jt := g.sqlTypeToJava(col.Type, false)
			if jt == "UUID" {
				needsU = true
			}
			if jt == "LocalDateTime" {
				needsLDT = true
			}
		}
		if len(realCols) == 0 {
			continue
		}
		if needsU {
			rw.WriteString("import java.util.UUID;\n")
		}
		if needsLDT {
			rw.WriteString("import java.time.LocalDateTime;\n")
		}
		rw.WriteString(fmt.Sprintf("\npublic record %s(\n", rowType))
		for i, col := range realCols {
			sep := ","
			if i == len(realCols)-1 {
				sep = ""
			}
			rw.WriteString(fmt.Sprintf("    %s %s%s\n", g.sqlTypeToJava(col.Type, col.Nullable), col.Name, sep))
		}
		rw.WriteString(") {}\n")
		rowFile := filepath.Join(g.Config.Gen.Java.Out, rowType+".java")
		if err := os.WriteFile(rowFile, []byte(rw.String()), 0644); err != nil {
			return err
		}
	}

	// Emit each Args type as its own top-level .java file
	emittedArgs := make(map[string]bool)
	for _, q := range queries {
		if len(q.Params) <= 2 {
			continue
		}
		argsName := gencommon.QueryPascal(q.Name) + "Params"
		if emittedArgs[argsName] {
			continue
		}
		emittedArgs[argsName] = true
		var aw strings.Builder
		aw.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
		aw.WriteString(fmt.Sprintf("package %s;\n\n", pkg))
		needsU, needsLDT := false, false
		for _, p := range q.Params {
			jt := g.sqlTypeToJava(p.Type, false)
			if jt == "UUID" {
				needsU = true
			}
			if jt == "LocalDateTime" {
				needsLDT = true
			}
		}
		if needsU {
			aw.WriteString("import java.util.UUID;\n")
		}
		if needsLDT {
			aw.WriteString("import java.time.LocalDateTime;\n")
		}
		aw.WriteString(fmt.Sprintf("\npublic record %s(\n", argsName))
		for i, p := range q.Params {
			sep := ","
			if i == len(q.Params)-1 {
				sep = ""
			}
			aw.WriteString(fmt.Sprintf("    %s %s%s\n", g.sqlTypeToJava(p.Type, false), p.Name, sep))
		}
		aw.WriteString(") {}\n")
		argsFile := filepath.Join(g.Config.Gen.Java.Out, argsName+".java")
		if err := os.WriteFile(argsFile, []byte(aw.String()), 0644); err != nil {
			return err
		}
	}

	className := utils.ToPascalCase(strings.TrimSuffix(src, ".sql")) + "Queries"
	w.WriteString(fmt.Sprintf("public class %s {\n", className))
	w.WriteString(fmt.Sprintf("    private final %s %s;\n", connType, connParam))
	w.WriteString(fmt.Sprintf("    public %s(%s %s) { this.%s = %s; }\n\n", className, connType, connParam, connParam, connParam))

	for _, q := range queries {
		g.generateQueryMethod(w, q)
	}
	w.WriteString("}\n")

	baseName := strings.TrimSuffix(src, ".sql")

	mu.Lock()
	outputFile := utils.ToPascalCase(baseName) + "Queries.java"
	if count, exists := usedNames[baseName]; exists {
		usedNames[baseName] = count + 1
		outputFile = fmt.Sprintf("%sQueries_%d.java", utils.ToPascalCase(baseName), count+1)
	} else {
		usedNames[baseName] = 1
	}
	mu.Unlock()

	path := filepath.Join(g.Config.Gen.Java.Out, outputFile)
	if err := os.WriteFile(path, []byte(w.String()), 0644); err != nil {
		return err
	}

	deps := gencommon.ExtractTableDependencies(queries)
	gencommon.UpdateCacheForFile(g.cache, queryFile, currentHash, deps, path)
	return nil
}

// jsonFieldToJavaType converts a JsonField type to its Java representation.
func jsonFieldToJavaType(field *parser.JsonField) string {
	var jt string
	switch field.Type {
	case "string":
		jt = "String"
	case "int":
		jt = "Integer"
	case "float":
		jt = "Double"
	case "boolean":
		jt = "Boolean"
	case "string[]":
		jt = "java.util.List<String>"
	case "int[]":
		jt = "java.util.List<Integer>"
	case "float[]":
		jt = "java.util.List<Double>"
	case "boolean[]":
		jt = "java.util.List<Boolean>"
	case "any":
		jt = "Object"
	default:
		jt = field.Type
	}
	return jt
}
