package kotlingen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/cachegen"
	"github.com/Lumos-Labs-HQ/flash/internal/config"
	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

type Generator struct {
	Config       *config.Config
	schema       *parser.Schema
	schemaParser *parser.SchemaParser
	queryParser  *parser.QueryParser
	cache        *gencommon.GenerationCache
	expander     *gencommon.SchemaExpander
}

func New(cfg *config.Config) *Generator {
	cache := gencommon.NewGenerationCacheWithDir(cfg.Gen.Kotlin.Out)
	return &Generator{
		Config:       cfg,
		schemaParser: parser.NewSchemaParser(cfg),
		queryParser:  parser.NewQueryParser(cfg),
		cache:        cache,
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Config.Gen.Kotlin.Out, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	schema, err := g.schemaParser.Parse()
	if err != nil {
		return fmt.Errorf("failed to parse schema: %w", err)
	}
	g.schema = schema
	g.expander = gencommon.NewSchemaExpander(schema)

	schemaHash, _ := g.cache.ComputeSchemaChecksum(g.Config.SchemaDir)
	configHash := fmt.Sprintf("%x", []byte(fmt.Sprintf("%s|%s|%s", g.Config.Database.Provider, g.Config.Gen.Kotlin.Out, g.Config.Gen.Kotlin.Driver)))
	fullRegen := g.Config.ForceRegen || g.cache.ShouldRegenerateAll(schemaHash, configHash)

	queries, err := g.queryParser.Parse(schema)
	if err != nil {
		return fmt.Errorf("failed to parse queries: %w", err)
	}

	// Remove cache entries and generated files for query sources that no
	// longer exist (deleted or renamed .sql/.cql files), mirroring gogen.
	// Kotlin output files are named PascalCase(base) + ".kt".
	pruned := g.cache.PruneStaleQueryEntries(g.Config.Queries)
	for _, source := range pruned {
		base := strings.TrimSuffix(filepath.Base(source), filepath.Ext(source))
		orphan := filepath.Join(g.Config.Gen.Kotlin.Out, utils.ToPascalCase(base)+".kt")
		if err := os.Remove(orphan); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove orphaned output %s: %w", orphan, err)
		}
	}

	// A shared cache file (same out dir, multiple languages) can carry a
	// matching schema checksum from another generator — force regen when our
	// own canonical outputs are missing.
	if _, err := os.Stat(filepath.Join(g.Config.Gen.Kotlin.Out, "Models.kt")); os.IsNotExist(err) {
		fullRegen = true
	}
	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateModels(); err != nil {
			return err
		}
		if err := g.generateDB(queries); err != nil {
			return err
		}
	}

	if err := g.generateQueriesIncremental(queries, fullRegen); err != nil {
		return err
	}
	if err := g.generateMigrations(); err != nil {
		return err
	}

	// Generate shared JSON types file (if any @json annotations exist)
	if err := g.generateJsonTypes(queries); err != nil {
		return err
	}

	// Generate cache layer if enabled
	if g.Config.Cache.Enabled {
		if err := g.generateCacheFiles(queries); err != nil {
			return err
		}
	}

	g.cache.UpdateSchemaChecksum(schemaHash)
	g.cache.UpdateConfigChecksum(configHash)
	g.cache.MarkGeneration()
	_ = g.cache.Save()
	return nil
}

func (g *Generator) generateModels() error {
	var w strings.Builder
	w.Grow(200 + len(g.schema.Tables)*200)

	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	needsUUID := false
	needsLDT := false
	needsInstant := false
	for _, t := range g.schema.Tables {
		for _, c := range t.Columns {
			kt := g.sqlTypeToKotlin(c.Type, false)
			if strings.Contains(kt, "UUID") {
				needsUUID = true
			}
			if strings.Contains(kt, "LocalDateTime") {
				needsLDT = true
			}
			if strings.Contains(kt, "Instant") {
				needsInstant = true
			}
		}
	}
	if needsUUID {
		w.WriteString("import java.util.UUID\n")
	}
	if needsLDT {
		w.WriteString("import java.time.LocalDateTime\n")
	}
	if needsInstant {
		w.WriteString("import java.time.Instant\n")
	}
	if needsUUID || needsLDT || needsInstant {
		w.WriteString("\n")
	}

	for _, enum := range g.schema.Enums {
		name := utils.ToPascalCase(enum.Name)
		w.WriteString(fmt.Sprintf("enum class %s {\n", name))
		for i, v := range enum.Values {
			if i < len(enum.Values)-1 {
				w.WriteString(fmt.Sprintf("    %s,\n", strings.ToUpper(v)))
			} else {
				w.WriteString(fmt.Sprintf("    %s\n", strings.ToUpper(v)))
			}
		}
		w.WriteString("}\n\n")
	}

	for _, table := range g.schema.Tables {
		tableName := table.Name
		if _, after, ok := strings.CutLast(tableName, "."); ok {
			tableName = after
		}
		name := utils.ToPascalCase(tableName)
		w.WriteString(fmt.Sprintf("data class %s(\n", name))
		for i, col := range table.Columns {
			if col.Name == "*" {
				continue
			}
			kt := g.sqlTypeToKotlin(col.Type, col.Nullable)
			comma := ","
			if i == len(table.Columns)-1 {
				comma = ""
			}
			w.WriteString(fmt.Sprintf("    val %s: %s%s\n", gencommon.ToCamelCase(col.Name), kt, comma))
		}
		w.WriteString(")\n\n")
	}

	modelsPath := filepath.Join(g.Config.Gen.Kotlin.Out, "Models.kt")
	if err := os.WriteFile(modelsPath, []byte(w.String()), 0644); err != nil {
		return err
	}
	if genHash, err := gencommon.ComputeFileChecksum(modelsPath); err == nil {
		g.cache.UpdateGeneratedFileChecksum(modelsPath, genHash)
	}
	return nil
}

func (g *Generator) generateDB(queries []*parser.Query) error {
	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	driver := g.Config.Gen.Kotlin.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	// Collect unique source file base names
	seen := map[string]bool{}
	var files []string
	for _, q := range queries {
		src := q.SourceFile
		if src == "" {
			src = "queries"
		}
		base := strings.TrimSuffix(src, ".sql")
		if !seen[base] {
			seen[base] = true
			files = append(files, base)
		}
	}

	var connType, connParam, connImport string
	switch {
	case isScylla:
		connImport = "import com.datastax.oss.driver.api.core.CqlSession\n"
		connType = "CqlSession"
		connParam = "session"
	case driver == "exposed":
		connImport = "import org.jetbrains.exposed.sql.Database\n"
		connType = "Database"
		connParam = "db"
	case driver == "r2dbc":
		connImport = "import io.r2dbc.spi.Connection\n"
		connType = "Connection"
		connParam = "conn"
	default: // jdbc
		connImport = "import java.sql.Connection\n"
		connType = "Connection"
		connParam = "conn"
	}

	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	// Scan all queries for types needing imports
	needsUUID, needsLDT, needsInstant := false, false, false
	for _, q := range queries {
		for _, p := range q.Params {
			kt := g.sqlTypeToKotlin(p.Type, false)
			if strings.Contains(kt, "UUID") {
				needsUUID = true
			}
			if strings.Contains(kt, "LocalDateTime") {
				needsLDT = true
			}
			if strings.Contains(kt, "Instant") {
				needsInstant = true
			}
		}
	}
	if needsUUID {
		w.WriteString("import java.util.UUID\n")
	}
	if needsLDT {
		w.WriteString("import java.time.LocalDateTime\n")
	}
	if needsInstant {
		w.WriteString("import java.time.Instant\n")
	}
	w.WriteString(connImport + "\n")
	w.WriteString("/**\n * Unified query interface. Use `Queries.newq(conn)` to obtain an instance.\n */\n")
	w.WriteString("class Queries(private val " + connParam + ": " + connType + ") {\n\n")

	// Delegate fields — one per query file class
	for _, base := range files {
		className := utils.ToPascalCase(base) + "Queries"
		w.WriteString(fmt.Sprintf("    private val %s = %s(%s)\n", base, className, connParam))
	}
	w.WriteString("\n")

	// companion object with newq factory
	w.WriteString("    companion object {\n")
	w.WriteString(fmt.Sprintf("        fun newq(%s: %s): Queries = Queries(%s)\n", connParam, connType, connParam))
	w.WriteString("    }\n\n")

	// Proxy every query method
	for _, q := range queries {
		src := q.SourceFile
		if src == "" {
			src = "queries"
		}
		base := strings.TrimSuffix(src, ".sql")
		columns := g.expandWildcardColumns(q)
		cmd := strings.ToLower(q.Cmd)
		methodName := gencommon.ToCamelCase(q.Name)

		rowType := gencommon.QueryPascal(q.Name) + "Row"
		if mt := g.modelTypeForQuery(q, columns); mt != "" {
			rowType = mt
		}

		var retType string
		switch cmd {
		case ":one":
			if len(columns) == 1 {
				retType = g.sqlTypeToKotlin(columns[0].Type, true)
			} else if len(columns) > 1 {
				retType = rowType + "?"
			} else {
				retType = "Unit"
			}
		case ":many":
			if len(columns) == 1 {
				retType = fmt.Sprintf("List<%s>", g.sqlTypeToKotlin(columns[0].Type, false))
			} else if len(columns) > 1 {
				retType = fmt.Sprintf("List<%s>", rowType)
			} else {
				retType = "List<Map<String, Any?>>"
			}
		case ":execresult":
			retType = "Long"
		default:
			retType = "Unit"
		}

		params := make([]string, len(q.Params))
		args := make([]string, len(q.Params))
		useStructParams := len(q.Params) > 2
		var proxyArgStr string
		for i, p := range q.Params {
			params[i] = fmt.Sprintf("%s: %s", gencommon.ToCamelCase(p.Name), g.sqlTypeToKotlin(p.Type, p.Nullable))
			args[i] = gencommon.ToCamelCase(p.Name)
		}

		if useStructParams && len(q.Params) > 0 {
			proxyName := gencommon.QueryPascal(q.Name) + "Params"
			params = []string{fmt.Sprintf("args: %s", proxyName)}
			proxyArgStr = "args"
		} else {
			proxyArgStr = strings.Join(args, ", ")
		}

		retStmt := ""
		if retType != "Unit" {
			retStmt = "return "
		}
		w.WriteString(fmt.Sprintf("    fun %s(%s): %s =\n", methodName, strings.Join(params, ", "), retType))
		w.WriteString(fmt.Sprintf("        %s.%s(%s)\n\n", base, methodName, proxyArgStr))
		_ = retStmt
	}

	// close for JDBC
	if !isScylla && driver != "exposed" && driver != "r2dbc" {
		w.WriteString("    fun close() {\n")
		for _, base := range files {
			w.WriteString(fmt.Sprintf("        %s.close()\n", base))
		}
		w.WriteString("    }\n")
	}
	w.WriteString("}\n")

	queriesPath := filepath.Join(g.Config.Gen.Kotlin.Out, "Queries.kt")
	if err := os.WriteFile(queriesPath, []byte(w.String()), 0644); err != nil {
		return err
	}
	if genHash, err := gencommon.ComputeFileChecksum(queriesPath); err == nil {
		g.cache.UpdateGeneratedFileChecksum(queriesPath, genHash)
	}
	return nil
}

// isPrimitiveKtType returns true for Kotlin types that can never be null from JDBC
// (Int, Long, Double, Float, Boolean — returned as primitives by typed getters).

func (g *Generator) generateQueryMethod(w *strings.Builder, query *parser.Query) {
	methodName := gencommon.ToCamelCase(query.Name)
	columns := g.expandWildcardColumns(query)
	cmd := strings.ToLower(query.Cmd)
	driver := g.Config.Gen.Kotlin.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	// Row type
	rowType := gencommon.QueryPascal(query.Name) + "Row"
	if mt := g.modelTypeForQuery(query, columns); mt != "" {
		rowType = mt
	}

	// Build param list
	params := make([]string, len(query.Params))
	for i, p := range query.Params {
		params[i] = fmt.Sprintf("%s: %s", gencommon.ToCamelCase(p.Name), g.sqlTypeToKotlin(p.Type, p.Nullable))
	}

	// Return type
	var retType string
	switch cmd {
	case ":one":
		if len(columns) == 1 {
			retType = g.sqlTypeToKotlin(columns[0].Type, true)
		} else if len(columns) > 1 {
			retType = rowType + "?"
		} else {
			retType = "Unit"
		}
	case ":many":
		if len(columns) == 1 {
			retType = fmt.Sprintf("List<%s>", g.sqlTypeToKotlin(columns[0].Type, false))
		} else if len(columns) > 1 {
			retType = fmt.Sprintf("List<%s>", rowType)
		} else {
			retType = "List<Map<String, Any?>>"
		}
	case ":execresult":
		retType = "Long"
	default:
		retType = "Unit"
	}

	paramStr := strings.Join(params, ", ")
	useStructParams := len(query.Params) > 2
	var paramStructName string
	if useStructParams && len(query.Params) > 0 {
		paramStructName = gencommon.QueryPascal(query.Name) + "Params"
		paramStr = fmt.Sprintf("args: %s", paramStructName)
	}
	w.WriteString(fmt.Sprintf("    fun %s(%s): %s {\n", methodName, paramStr, retType))

	// Unpack struct params into local variables so body functions don't need changes
	if useStructParams {
		for _, p := range query.Params {
			w.WriteString(fmt.Sprintf("        val %s = args.%s\n",
				gencommon.ToCamelCase(p.Name), gencommon.ToCamelCase(p.Name)))
		}
	}

	// SQL constant
	sql := strings.TrimSpace(query.SQL)
	if isScylla || driver == "" || driver == "jdbc" || driver == "default" {
		// Convert PostgreSQL $N to ? for JDBC/CQL
		for i := 20; i >= 1; i-- {
			sql = strings.ReplaceAll(sql, fmt.Sprintf("$%d", i), "?")
		}
	}
	w.WriteString(fmt.Sprintf("        val sql = \"\"\"%s\"\"\"\n", sql))

	if isScylla {
		g.generateScyllaBody(w, query, columns, cmd, rowType)
	} else if driver == "r2dbc" {
		g.generateR2DBCBody(w, query, columns, cmd, rowType)
	} else if driver == "exposed" {
		g.generateExposedBody(w, query, columns, cmd, rowType)
	} else {
		g.generateJDBCBody(w, query, columns, cmd, rowType)
	}

	w.WriteString("    }\n\n")
}

// ktColumnGetter returns the getter expression for a column, handling @json typed columns.
func (g *Generator) ktColumnGetter(col *parser.QueryColumn) string {
	if col.JsonDef != nil {
		// Uses the generated companion fromJson method (backed by Gson in JsonTypes.kt)
		return fmt.Sprintf("%s.fromJson(rs.getString(\"%s\"))", col.JsonDef.Name, col.Name)
	}
	return g.ktTypedGetter(col.Name, col.Type, col.Nullable)
}

// ktTypedGetter returns the typed Kotlin ResultSet getter by column name.
func (g *Generator) ktTypedGetter(colName, sqlType string, nullable bool) string {
	sl := strings.ToLower(sqlType)
	// Check schema enums first
	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sl {
				ktType := utils.ToPascalCase(enum.Name)
				if nullable {
					return fmt.Sprintf("rs.getString(\"%s\")?.let { %s.valueOf(it) }", colName, ktType)
				}
				return fmt.Sprintf("%s.valueOf(rs.getString(\"%s\"))", ktType, colName)
			}
		}
	}
	switch {
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "uint64":
		return fmt.Sprintf("rs.getLong(\"%s\")", colName)
	case strings.Contains(sl, "int") || strings.Contains(sl, "serial") || sl == "uint8" || sl == "uint16" || sl == "uint32":
		return fmt.Sprintf("rs.getInt(\"%s\")", colName)
	case sl == "float32":
		return fmt.Sprintf("rs.getFloat(\"%s\")", colName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "numeric") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("rs.getDouble(\"%s\")", colName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("rs.getBoolean(\"%s\")", colName)
	case sl == "timeuuid" || strings.Contains(sl, "uuid"):
		return fmt.Sprintf("rs.getObject(\"%s\", UUID::class.java)", colName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		if nullable {
			return fmt.Sprintf("rs.getTimestamp(\"%s\")?.toLocalDateTime()", colName)
		}
		return fmt.Sprintf("rs.getTimestamp(\"%s\")!!.toLocalDateTime()", colName)
	case sl == "bytea" || strings.Contains(sl, "blob"):
		return fmt.Sprintf("rs.getBytes(\"%s\")", colName)
	case strings.HasSuffix(sl, "[]") || strings.HasPrefix(sl, "set<") || strings.HasPrefix(sl, "list<"):
		return fmt.Sprintf("(rs.getArray(\"%s\")?.array as? Array<*>)?.map { it.toString() }", colName)
	case strings.Contains(sl, "json"):
		return fmt.Sprintf("rs.getString(\"%s\")", colName)
	default:
		return fmt.Sprintf("rs.getString(\"%s\")", colName)
	}
}

// ktTypedSetter returns a typed Kotlin PreparedStatement setter.
func ktTypedSetter(idx int, paramName, sqlType string) string {
	sl := strings.ToLower(sqlType)
	// @json: typed param → serialize with .toJson()
	if strings.HasPrefix(sqlType, "@json:") {
		return fmt.Sprintf("stmt.setString(%d, %s.toJson())", idx, paramName)
	}
	// Any SQL array type → createArrayOf
	if before, ok := strings.CutSuffix(sl, "[]"); ok {
		baseType := before
		pgType := "text"
		switch {
		case strings.Contains(baseType, "int") || strings.Contains(baseType, "serial"):
			pgType = "integer"
		case strings.Contains(baseType, "uuid"):
			pgType = "uuid"
		case strings.Contains(baseType, "bool"):
			pgType = "boolean"
		case strings.Contains(baseType, "float") || strings.Contains(baseType, "real") || strings.Contains(baseType, "double"):
			pgType = "float8"
		}
		return fmt.Sprintf("stmt.setArray(%d, conn.createArrayOf(\"%s\", %s.toTypedArray()))", idx, pgType, paramName)
	}
	switch {
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "uint64":
		return fmt.Sprintf("stmt.setLong(%d, %s)", idx, paramName)
	case strings.Contains(sl, "int") || strings.Contains(sl, "serial") || sl == "uint8" || sl == "uint16" || sl == "uint32":
		return fmt.Sprintf("stmt.setInt(%d, %s)", idx, paramName)
	case sl == "float32":
		return fmt.Sprintf("stmt.setFloat(%d, %s)", idx, paramName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "numeric") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("stmt.setDouble(%d, %s)", idx, paramName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("stmt.setBoolean(%d, %s)", idx, paramName)
	case sl == "bytea" || strings.Contains(sl, "blob"):
		return fmt.Sprintf("stmt.setBytes(%d, %s)", idx, paramName)
	case strings.Contains(sl, "uuid") || sl == "timeuuid":
		return fmt.Sprintf("stmt.setObject(%d, %s)", idx, paramName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("stmt.setObject(%d, java.sql.Timestamp.valueOf(%s))", idx, paramName)
	case strings.Contains(sl, "varchar") || strings.Contains(sl, "text") || strings.Contains(sl, "char"):
		return fmt.Sprintf("stmt.setString(%d, %s)", idx, paramName)
	default:
		// enums, json, arrays — setObject handles all; no .toString() needed
		return fmt.Sprintf("stmt.setObject(%d, %s)", idx, paramName)
	}
}

// cqlKtGetter returns DataStax typed getter by column name for Kotlin.
func cqlKtGetter(colName, sqlType string, nullable bool) string {
	sl := strings.ToLower(sqlType)
	// Primitives (Int, Long, Double, Float, Boolean) are never null from getXxx()
	// Reference types (UUID, String, Instant, Set, List, Map) return nullable from driver
	nn := ""
	if !nullable {
		nn = "!!"
	}
	switch {
	case sl == "uuid" || sl == "timeuuid":
		return fmt.Sprintf("row.getUuid(\"%s\")%s", colName, nn)
	case strings.Contains(sl, "bigint") || sl == "int8" || sl == "varint" || sl == "counter":
		return fmt.Sprintf("row.getLong(\"%s\")", colName)
	case strings.Contains(sl, "int"):
		return fmt.Sprintf("row.getInt(\"%s\")", colName)
	case sl == "float32":
		return fmt.Sprintf("row.getFloat(\"%s\")", colName)
	case sl == "float64" || strings.Contains(sl, "double") || strings.Contains(sl, "decimal"):
		return fmt.Sprintf("row.getDouble(\"%s\")", colName)
	case strings.Contains(sl, "bool"):
		return fmt.Sprintf("row.getBoolean(\"%s\")", colName)
	case strings.Contains(sl, "timestamp") || strings.Contains(sl, "date") || strings.Contains(sl, "time"):
		return fmt.Sprintf("row.getInstant(\"%s\")%s", colName, nn)
	case strings.HasPrefix(sl, "set<"):
		inner, _ := gencommon.ParseCQLInner(sl)
		return fmt.Sprintf("row.getSet(\"%s\", %s::class.java)%s", colName, cqlInnerKtClass(inner), nn)
	case strings.HasPrefix(sl, "list<"):
		inner, _ := gencommon.ParseCQLInner(sl)
		return fmt.Sprintf("row.getList(\"%s\", %s::class.java)%s", colName, cqlInnerKtClass(inner), nn)
	case strings.HasPrefix(sl, "map<"):
		k, v := gencommon.ParseCQLInner(sl)
		return fmt.Sprintf("row.getMap(\"%s\", %s::class.java, %s::class.java)%s", colName, cqlInnerKtClass(k), cqlInnerKtClass(v), nn)
	default:
		return fmt.Sprintf("row.getString(\"%s\")%s", colName, nn)
	}
}

// cqlInnerKtClass maps a CQL element type to its Kotlin class reference.
func cqlInnerKtClass(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "uuid", "timeuuid":
		return "UUID"
	case "bigint", "counter", "varint", "int8":
		return "Long"
	case "int":
		return "Int"
	case "float":
		return "Float"
	case "double", "decimal":
		return "Double"
	case "boolean":
		return "Boolean"
	case "timestamp", "date", "time":
		return "java.time.Instant"
	default:
		return "String"
	}
}

func (g *Generator) generateJDBCBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	methodName := gencommon.ToCamelCase(query.Name)
	key := fmt.Sprintf("\"%s\"", methodName)

	w.WriteString(fmt.Sprintf("        val stmt = stmts.getOrPut(%s) { conn.prepareStatement(sql) }\n", key))

	for i, p := range query.Params {
		w.WriteString(fmt.Sprintf("        %s\n", ktTypedSetter(i+1, gencommon.ToCamelCase(p.Name), p.Type)))
	}

	switch cmd {

	case ":one":
		w.WriteString("        stmt.executeQuery().use { rs ->\n")
		if len(columns) == 0 {
			w.WriteString("            return\n")
		} else if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("            return if (rs.next()) %s else null\n", g.ktColumnGetter(columns[0])))
		} else {
			w.WriteString(fmt.Sprintf("            return if (rs.next()) %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("                %s%s\n", g.ktColumnGetter(col), comma))
			}
			w.WriteString("            ) else null\n")
		}
		w.WriteString("        }\n")
	case ":many":
		w.WriteString(fmt.Sprintf("        val items = mutableListOf<%s>()\n", func() string {
			if len(columns) == 1 {
				return g.sqlTypeToKotlin(columns[0].Type, false)
			}
			return rowType
		}()))
		w.WriteString("        stmt.executeQuery().use { rs ->\n")
		if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("            while (rs.next()) items.add(%s)\n", g.ktColumnGetter(columns[0])))
		} else if len(columns) > 1 {
			w.WriteString("            while (rs.next()) items.add(\n")
			w.WriteString(fmt.Sprintf("                %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("                    %s%s\n", g.ktColumnGetter(col), comma))
			}
			w.WriteString("                )\n            )\n")
		}
		w.WriteString("        }\n")
		w.WriteString("        return items\n")
	case ":execresult":
		w.WriteString("        stmt.executeUpdate()\n")
		w.WriteString("        return stmt.generatedKeys?.use { if (it.next()) it.getLong(1) else 0L } ?: 0L\n")
	default:
		w.WriteString("        stmt.executeUpdate()\n")
	}
}

func (g *Generator) generateScyllaBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	args := make([]string, len(query.Params))
	for i, p := range query.Params {
		args[i] = gencommon.ToCamelCase(p.Name)
	}

	execLine := "        session.execute(sql)\n"
	rsLine := "        val rs = session.execute(sql)\n"
	if len(args) > 0 {
		argsStr := strings.Join(args, ", ")
		execLine = fmt.Sprintf("        session.execute(com.datastax.oss.driver.api.core.cql.SimpleStatement.newInstance(sql, %s))\n", argsStr)
		rsLine = fmt.Sprintf("        val rs = session.execute(com.datastax.oss.driver.api.core.cql.SimpleStatement.newInstance(sql, %s))\n", argsStr)
	}

	switch cmd {
	case ":exec", ":execresult":
		w.WriteString(execLine)
	case ":one":
		w.WriteString(rsLine)
		w.WriteString("        val row = rs.one() ?: return null\n")
		if len(columns) == 1 {
			w.WriteString(fmt.Sprintf("        return %s\n", cqlKtGetter(columns[0].Name, columns[0].Type, columns[0].Nullable)))
		} else if len(columns) > 1 {
			w.WriteString(fmt.Sprintf("        return %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("            %s%s\n", cqlKtGetter(col.Name, col.Type, col.Nullable), comma))
			}
			w.WriteString("        )\n")
		}
	case ":many":
		w.WriteString(rsLine)
		if len(columns) == 1 {
			kt := g.sqlTypeToKotlin(columns[0].Type, false)
			w.WriteString(fmt.Sprintf("        val items = mutableListOf<%s>()\n", kt))
			w.WriteString(fmt.Sprintf("        for (row in rs) items.add(%s)\n", cqlKtGetter(columns[0].Name, columns[0].Type, columns[0].Nullable)))
			w.WriteString("        return items\n")
		} else if len(columns) > 1 {
			w.WriteString(fmt.Sprintf("        return rs.map { row -> %s(\n", rowType))
			for i, col := range columns {
				comma := ","
				if i == len(columns)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("            %s%s\n", cqlKtGetter(col.Name, col.Type, col.Nullable), comma))
			}
			w.WriteString("        ) }.toList()\n")
		} else {
			w.WriteString("        return emptyList()\n")
		}
	}
}

func (g *Generator) generateR2DBCBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	w.WriteString("        // R2DBC: use reactive execute, this is a blocking stub\n")
	w.WriteString("        val stmt = conn.createStatement(sql)\n")
	for i, p := range query.Params {
		w.WriteString(fmt.Sprintf("        stmt.bind(%d, %s)\n", i, gencommon.ToCamelCase(p.Name)))
	}
	w.WriteString("        // TODO: subscribe to stmt.execute() with your reactor/coroutine bridge\n")
	if cmd == ":one" || cmd == ":many" {
		w.WriteString(fmt.Sprintf("        return null // replace with reactive mapping to %s\n", rowType))
	}
}

func (g *Generator) generateExposedBody(w *strings.Builder, query *parser.Query, columns []*parser.QueryColumn, cmd, rowType string) {
	w.WriteString("        // Exposed: wrap in transaction { ... }\n")
	w.WriteString("        return org.jetbrains.exposed.sql.transactions.transaction(db) {\n")
	if len(query.Params) > 0 {
		args := make([]string, len(query.Params))
		for i, p := range query.Params {
			args[i] = gencommon.ToCamelCase(p.Name)
		}
		w.WriteString(fmt.Sprintf("            exec(sql, args = listOf(%s)) { rs ->\n", strings.Join(args, ", ")))
	} else {
		w.WriteString("            exec(sql) { rs ->\n")
	}
	if cmd == ":one" && len(columns) > 1 {
		w.WriteString(fmt.Sprintf("                if (rs.next()) %s(\n", rowType))
		for i, col := range columns {
			comma := ","
			if i == len(columns)-1 {
				comma = ""
			}
			w.WriteString(fmt.Sprintf("                    rs.getObject(%d) as %s%s\n", i+1, g.sqlTypeToKotlin(col.Type, col.Nullable), comma))
		}
		w.WriteString("                ) else null\n")
	} else {
		w.WriteString("                rs.next()\n")
	}
	w.WriteString("            }\n")
	w.WriteString("        }\n")
}

// cqlInnerKtType maps a CQL element type to its Kotlin type name (for generics).
func cqlInnerKtType(t string) string {
	switch strings.ToLower(strings.TrimSpace(t)) {
	case "uuid", "timeuuid":
		return "UUID"
	case "bigint", "counter", "varint", "int8":
		return "Long"
	case "int":
		return "Int"
	case "float":
		return "Float"
	case "double", "decimal":
		return "Double"
	case "boolean":
		return "Boolean"
	case "timestamp", "date", "time":
		return "java.time.Instant"
	default:
		return "String"
	}
}

// nullable_ appends "?" to a Kotlin type when nullable.
func nullable_(t string, nullable bool) string {
	if nullable {
		return t + "?"
	}
	return t
}

func (g *Generator) sqlTypeToKotlin(sqlType string, nullable bool) string {
	// Handle @json: type prefix — generated JSON type class for params
	if after, ok := strings.CutPrefix(sqlType, "@json:"); ok {
		typeName := after
		if nullable {
			return typeName + "?"
		}
		return typeName
	}

	sqlLower := strings.ToLower(sqlType)

	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sqlLower {
				t := utils.ToPascalCase(enum.Name)
				if nullable {
					return t + "?"
				}
				return t
			}
		}
	}

	var kt string
	switch {
	// CQL collections — must be before contains("int") / contains("map")
	case strings.HasPrefix(sqlLower, "set<"):
		inner, _ := gencommon.ParseCQLInner(sqlLower)
		return nullable_(fmt.Sprintf("Set<%s>", cqlInnerKtType(inner)), nullable)
	case strings.HasPrefix(sqlLower, "list<"):
		inner, _ := gencommon.ParseCQLInner(sqlLower)
		return nullable_(fmt.Sprintf("List<%s>", cqlInnerKtType(inner)), nullable)
	case strings.HasPrefix(sqlLower, "map<"):
		k, v := gencommon.ParseCQLInner(sqlLower)
		return nullable_(fmt.Sprintf("Map<%s, %s>", cqlInnerKtType(k), cqlInnerKtType(v)), nullable)
	case strings.HasPrefix(sqlLower, "frozen<"), strings.HasPrefix(sqlLower, "tuple<"):
		kt = "String"
	// SQL array types — must be before contains("int"), contains("uuid"), etc.
	case strings.HasSuffix(sqlLower, "[]"):
		inner := g.sqlTypeToKotlin(strings.TrimSuffix(sqlLower, "[]"), false)
		kt = fmt.Sprintf("List<%s>", inner)
	// ClickHouse exact unsigned — before contains("int")
	case sqlLower == "uint8" || sqlLower == "uint16" || sqlLower == "uint32" || sqlLower == "uint64":
		kt = "Long"
	// ClickHouse exact float — before contains("float")
	case sqlLower == "float32":
		kt = "Float"
	case sqlLower == "float64":
		kt = "Double"
	case sqlLower == "string" || strings.HasPrefix(sqlLower, "fixedstring"):
		kt = "String"
	// timeuuid is a UUID variant — must be before contains("time")
	case sqlLower == "timeuuid":
		kt = "UUID"
	// Generic SQL types
	case strings.Contains(sqlLower, "bigint") || sqlLower == "int8":
		kt = "Long"
	case strings.Contains(sqlLower, "int") || strings.Contains(sqlLower, "serial"):
		kt = "Int"
	case strings.Contains(sqlLower, "float"):
		kt = "Float"
	case strings.Contains(sqlLower, "double") || strings.Contains(sqlLower, "numeric") || strings.Contains(sqlLower, "decimal"):
		kt = "Double"
	case strings.Contains(sqlLower, "bool"):
		kt = "Boolean"
	case strings.Contains(sqlLower, "timestamp") || strings.Contains(sqlLower, "date") || strings.Contains(sqlLower, "time"):
		provider := g.Config.Database.Provider
		if provider == "scylla" || provider == "scylladb" || provider == "cassandra" {
			kt = "Instant"
		} else {
			kt = "LocalDateTime"
		}
	case strings.Contains(sqlLower, "uuid"):
		kt = "UUID"
	case strings.Contains(sqlLower, "json"):
		kt = "String" // raw JSON string
	case sqlLower == "bytea" || strings.Contains(sqlLower, "blob"):
		kt = "ByteArray"
	// ─── PostgreSQL Extension Types ───────────────────────────────────────
	case sqlLower == "vector" || strings.HasPrefix(sqlLower, "vector(") ||
		sqlLower == "halfvec" || strings.HasPrefix(sqlLower, "halfvec("):
		kt = "List<Float>" // pgvector
	case sqlLower == "hstore":
		kt = "Map<String, String>"
	case sqlLower == "interval":
		kt = "String"
	case sqlLower == "tsvector", sqlLower == "tsquery":
		kt = "String"
	case sqlLower == "ltree", sqlLower == "lquery", sqlLower == "ltxtquery":
		kt = "String"
	case sqlLower == "money":
		kt = "String"
	case sqlLower == "xml":
		kt = "String"
	case sqlLower == "pg_lsn":
		kt = "String"
	case sqlLower == "bit" || strings.HasPrefix(sqlLower, "bit(") ||
		sqlLower == "varbit" || strings.HasPrefix(sqlLower, "varbit(") ||
		strings.HasPrefix(sqlLower, "bit varying"):
		kt = "String"
	case sqlLower == "inet", sqlLower == "cidr":
		kt = "String"
	case sqlLower == "macaddr", sqlLower == "macaddr8":
		kt = "String"
	case sqlLower == "point", sqlLower == "line", sqlLower == "lseg",
		sqlLower == "box", sqlLower == "path", sqlLower == "polygon", sqlLower == "circle":
		kt = "String"
	case sqlLower == "geometry" || strings.HasPrefix(sqlLower, "geometry(") ||
		sqlLower == "geography" || strings.HasPrefix(sqlLower, "geography("):
		kt = "String" // PostGIS
	case strings.HasSuffix(sqlLower, "range") || strings.HasSuffix(sqlLower, "multirange"):
		kt = "String"
	default:
		kt = "String"
	}
	if nullable {
		return kt + "?"
	}
	return kt
}

func (g *Generator) expandWildcardColumns(query *parser.Query) []*parser.QueryColumn {
	if g.expander == nil {
		g.expander = gencommon.NewSchemaExpander(g.schema)
	}
	cols := g.expander.ExpandWildcardColumns(query)
	return cols
}

func (g *Generator) modelTypeForQuery(query *parser.Query, columns []*parser.QueryColumn) string {
	if g.expander == nil {
		g.expander = gencommon.NewSchemaExpander(g.schema)
	}
	return g.expander.ModelTypeForQuery(query, columns)
}

// toKotlinPackage returns the package name: config value takes priority over dir name.
func toKotlinPackage(cfg *config.KotlinGen) string {
	if cfg.Package != "" {
		return cfg.Package
	}
	base := filepath.Base(cfg.Out)
	return strings.ReplaceAll(strings.ToLower(base), "-", "_")
}

// generateJsonTypes creates a shared JsonTypes.kt file with all @json data classes.
// Uses Gson for JSON serialization (standard in Kotlin/JVM projects).
// Includes a `rawJson` field so users can access fields not defined in the type.
func (g *Generator) generateJsonTypes(queries []*parser.Query) error {
	emitted := make(map[string]*parser.JsonType)
	for _, q := range queries {
		for _, jt := range q.JsonTypes {
			if _, ok := emitted[jt.Name]; !ok {
				emitted[jt.Name] = jt
			}
		}
	}

	if len(emitted) == 0 {
		jsonTypesPath := filepath.Join(g.Config.Gen.Kotlin.Out, "JsonTypes.kt")
		os.Remove(jsonTypesPath)
		return nil
	}

	var w strings.Builder
	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	w.WriteString("import com.google.gson.Gson\nimport com.google.gson.JsonObject\nimport com.google.gson.JsonParser\nimport com.google.gson.reflect.TypeToken\n\n")
	w.WriteString("private val gson = Gson()\n\n")

	for _, jt := range emitted {
		w.WriteString(fmt.Sprintf("/**\n * JSON type for column '%s'.\n", jt.Column))
		w.WriteString(" * Fields not listed here are still accessible via `raw` (the full JsonObject).\n")
		w.WriteString(" * Example: obj.raw?.get(\"some_other_field\")?.asString\n */\n")
		w.WriteString(fmt.Sprintf("data class %s(\n", jt.Name))
		for _, field := range jt.Fields {
			kt := jsonFieldToKotlinType(field)
			w.WriteString(fmt.Sprintf("    val %s: %s,\n", gencommon.ToCamelCase(field.Name), kt))
		}
		// Add raw field for accessing unmentioned fields
		w.WriteString("    val raw: JsonObject? = null\n")
		w.WriteString(") {\n")
		w.WriteString("    /** Get any field not defined in this type by key */\n")
		w.WriteString("    fun get(key: String): String? = raw?.get(key)?.let { if (it.isJsonNull) null else it.asString }\n\n")
		w.WriteString("    fun toJson(): String = raw?.toString() ?: gson.toJson(this)\n\n")
		w.WriteString("    companion object {\n")
		w.WriteString(fmt.Sprintf("        fun fromJson(json: String?): %s? {\n", jt.Name))
		w.WriteString("            if (json == null) return null\n")
		w.WriteString("            val obj = JsonParser.parseString(json).asJsonObject\n")
		w.WriteString(fmt.Sprintf("            return %s(\n", jt.Name))
		for _, field := range jt.Fields {
			getter := jsonFieldKotlinGsonGetter("obj", field)
			w.WriteString(fmt.Sprintf("                %s,\n", getter))
		}
		w.WriteString("                raw = obj\n")
		w.WriteString("            )\n")
		w.WriteString("        }\n")
		w.WriteString("    }\n")
		w.WriteString("}\n\n")
	}

	jsonTypesPath := filepath.Join(g.Config.Gen.Kotlin.Out, "JsonTypes.kt")
	return os.WriteFile(jsonTypesPath, []byte(w.String()), 0644)
}

// jsonFieldKotlinGsonGetter generates a Gson-based getter for a field from JsonObject.
func jsonFieldKotlinGsonGetter(objVar string, field *parser.JsonField) string {
	key := field.Name
	switch field.Type {
	case "string":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.get(\"%s\").asString else null",
			objVar, key, objVar, key, objVar, key)
	case "int":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.get(\"%s\").asInt else null",
			objVar, key, objVar, key, objVar, key)
	case "float":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.get(\"%s\").asDouble else null",
			objVar, key, objVar, key, objVar, key)
	case "boolean":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.get(\"%s\").asBoolean else null",
			objVar, key, objVar, key, objVar, key)
	case "string[]":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.getAsJsonArray(\"%s\").map { it.asString } else null",
			objVar, key, objVar, key, objVar, key)
	case "int[]":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.getAsJsonArray(\"%s\").map { it.asInt } else null",
			objVar, key, objVar, key, objVar, key)
	case "float[]":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.getAsJsonArray(\"%s\").map { it.asDouble } else null",
			objVar, key, objVar, key, objVar, key)
	case "boolean[]":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.getAsJsonArray(\"%s\").map { it.asBoolean } else null",
			objVar, key, objVar, key, objVar, key)
	case "any":
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.get(\"%s\") else null",
			objVar, key, objVar, key, objVar, key)
	default:
		return fmt.Sprintf("if (%s.has(\"%s\") && !%s.get(\"%s\").isJsonNull) %s.get(\"%s\").asString else null",
			objVar, key, objVar, key, objVar, key)
	}
}

func (g *Generator) generateCacheFiles(queries []*parser.Query) error {
	pkgName := g.Config.Gen.Kotlin.Package
	if pkgName == "" {
		pkgName = "flashgen"
	}

	// Generate FlashCache.kt
	cacheCode := cachegen.GenerateKotlinCache(&g.Config.Cache, pkgName)
	cachePath := filepath.Join(g.Config.Gen.Kotlin.Out, "FlashCache.kt")
	if err := os.WriteFile(cachePath, []byte(cacheCode), 0644); err != nil {
		return fmt.Errorf("failed to write FlashCache.kt: %w", err)
	}

	// Resolve cache annotations
	caches := cachegen.ResolveCacheQueries(queries, &g.Config.Cache)

	// Validate dep references
	if warnings := cachegen.ValidateDeps(caches, queries); len(warnings) > 0 {
		for _, w := range warnings {
			fmt.Printf("⚠️  %s\n", w)
		}
	}

	// Generate CacheAccessors.kt
	accessorCode := cachegen.GenerateKotlinCacheAccessors(caches, pkgName)
	if accessorCode == "" {
		accessorCode = fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\npackage %s\n\n// No @cache annotations found.\n", pkgName)
	}
	accessorPath := filepath.Join(g.Config.Gen.Kotlin.Out, "CacheAccessors.kt")
	if err := os.WriteFile(accessorPath, []byte(accessorCode), 0644); err != nil {
		return fmt.Errorf("failed to write CacheAccessors.kt: %w", err)
	}

	// Generate CachedQueries.kt
	cachedCode := g.generateCachedQueries(queries, caches, pkgName)
	cachedPath := filepath.Join(g.Config.Gen.Kotlin.Out, "CachedQueries.kt")
	if err := os.WriteFile(cachedPath, []byte(cachedCode), 0644); err != nil {
		return fmt.Errorf("failed to write CachedQueries.kt: %w", err)
	}

	return nil
}

func (g *Generator) generateCachedQueries(queries []*parser.Query, caches []*cachegen.CacheInfo, pkgName string) string {
	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	w.WriteString("import java.sql.Connection\n\n")

	w.WriteString("/**\n * Cache-wrapped queries and auto-purge mutations.\n */\n")
	w.WriteString("class CachedQueries(private val conn: Connection) {\n")
	w.WriteString("    private val queries = Queries.newq(conn)\n\n")

	hasContent := false
	for _, q := range queries {
		if cachegen.IsCachedQuery(q) && !cachegen.IsMutationQuery(q) {
			g.writeKtCachedQuery(&w, q, caches)
			hasContent = true
		} else if cachegen.IsMutationQuery(q) {
			purges := cachegen.ResolveDependencyPurges(q.Name, caches, q.Params)
			if len(purges) > 0 {
				g.writeKtPurgingMutation(&w, q, purges)
				hasContent = true
			}
		}
	}

	w.WriteString("}\n")

	if !hasContent {
		return fmt.Sprintf("// Code generated by FlashORM. DO NOT EDIT.\npackage %s\n\n// No cached queries or auto-purge mutations.\n", pkgName)
	}
	return w.String()
}

func (g *Generator) writeKtCachedQuery(w *strings.Builder, q *parser.Query, caches []*cachegen.CacheInfo) {
	cacheInfo := cachegen.GetCacheInfoForQuery(q.Name, caches)
	if cacheInfo == nil {
		return
	}
	ttlSec := cachegen.ParseTTL(cacheInfo.TTL)

	var params []string
	for _, p := range q.Params {
		params = append(params, fmt.Sprintf("%s: Any", p.Name))
	}
	paramStr := strings.Join(params, ", ")

	var keyParts []string
	for _, p := range q.Params {
		keyParts = append(keyParts, fmt.Sprintf("$%s", p.Name))
	}
	var keyExpr string
	if len(keyParts) == 0 {
		keyExpr = fmt.Sprintf("\"%s\"", cacheInfo.CacheName)
	} else {
		keyExpr = fmt.Sprintf("\"%s:%s\"", cacheInfo.CacheName, strings.Join(keyParts, ":"))
	}

	tagsLiteral := "emptyList()"
	if len(cacheInfo.Tags) > 0 {
		quoted := make([]string, len(cacheInfo.Tags))
		for i, t := range cacheInfo.Tags {
			quoted[i] = fmt.Sprintf("\"%s\"", t)
		}
		tagsLiteral = fmt.Sprintf("listOf(%s)", strings.Join(quoted, ", "))
	}

	fnName := q.Name + "Cached"
	w.WriteString(fmt.Sprintf("    /** %s (cached, TTL: %s) */\n", q.Name, cacheInfo.TTL))
	w.WriteString(fmt.Sprintf("    fun <T> %s(%s, clazz: Class<T>): T? {\n", fnName, paramStr))
	w.WriteString(fmt.Sprintf("        val key = %s\n", keyExpr))
	w.WriteString("        val cached = FlashCache.get(key, clazz)\n")
	w.WriteString("        if (cached != null) return cached\n\n")

	var callArgs []string
	for _, p := range q.Params {
		callArgs = append(callArgs, p.Name)
	}
	w.WriteString(fmt.Sprintf("        val result = queries.%s(%s)\n", q.Name, strings.Join(callArgs, ", ")))
	w.WriteString(fmt.Sprintf("        FlashCache.set(key, result, %d, %s)\n", ttlSec, tagsLiteral))
	w.WriteString("        @Suppress(\"UNCHECKED_CAST\")\n")
	w.WriteString("        return result as? T\n")
	w.WriteString("    }\n\n")
}

func (g *Generator) writeKtPurgingMutation(w *strings.Builder, q *parser.Query, purges []cachegen.DependencyPurge) {
	var params []string
	for _, p := range q.Params {
		params = append(params, fmt.Sprintf("%s: Any", p.Name))
	}
	paramStr := strings.Join(params, ", ")

	fnName := q.Name + "AndPurge"
	w.WriteString(fmt.Sprintf("    /** %s (auto-purges dependent caches) */\n", q.Name))
	w.WriteString(fmt.Sprintf("    fun %s(%s) {\n", fnName, paramStr))

	var callArgs []string
	for _, p := range q.Params {
		callArgs = append(callArgs, p.Name)
	}
	w.WriteString(fmt.Sprintf("        queries.%s(%s)\n\n", q.Name, strings.Join(callArgs, ", ")))
	w.WriteString("        // Auto-purge dependent caches\n")
	for _, purge := range purges {
		if purge.PurgePrefix {
			w.WriteString(fmt.Sprintf("        FlashCache.purgeByPrefix(\"%s:\")\n", purge.CacheName))
		} else {
			w.WriteString(fmt.Sprintf("        FlashCache.del(\"%s:$%s\")\n", purge.CacheName, purge.KeyParam))
		}
	}
	w.WriteString("    }\n\n")
}
