package kotlingen

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

func (g *Generator) generateQueriesIncremental(queries []*parser.Query, fullRegen bool) error {
	queryGroups := make(map[string][]*parser.Query)
	for _, query := range queries {
		src := query.SourceFile
		if src == "" {
			src = "queries"
		}
		queryGroups[src] = append(queryGroups[src], query)
	}

	type fileGroup struct {
		src     string
		queries []*parser.Query
	}
	groups := make([]fileGroup, 0, len(queryGroups))
	for src, qs := range queryGroups {
		groups = append(groups, fileGroup{src, qs})
	}

	usedNames := make(map[string]int)
	var mu sync.Mutex

	numWorkers := min(runtime.NumCPU(), len(groups))

	workCh := make(chan fileGroup, len(groups))
	errCh := make(chan error, len(groups))
	var wg sync.WaitGroup

	for i := 0; i < numWorkers; i++ {
		wg.Go(func() {
			for fg := range workCh {
				errCh <- g.generateSingleKtFile(fg.src, fg.queries, fullRegen, &mu, usedNames)
			}
		})
	}
	for _, fg := range groups {
		workCh <- fg
	}
	close(workCh)
	go func() { wg.Wait(); close(errCh) }()
	for err := range errCh {
		if err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateSingleKtFile(src string, queries []*parser.Query, fullRegen bool, mu *sync.Mutex, usedNames map[string]int) error {
	queryFile := filepath.Join(g.Config.Queries, src+".sql")
	currentHash, _ := gencommon.ComputeFileChecksum(queryFile)

	// The skip decision must consider this generator's own output file so a
	// shared cache entry from another language cannot suppress generation.
	primaryOutput := filepath.Join(g.Config.Gen.Kotlin.Out, utils.ToPascalCase(strings.TrimSuffix(src, ".sql"))+".kt")
	if !gencommon.ShouldRegenerateFileForOutput(g.cache, queryFile, currentHash, fullRegen, primaryOutput) {
		gencommon.PrintSkipMessage(src, ".kt")
		return nil
	}
	gencommon.PrintGenerateMessage(src, ".kt")

	w := gencommon.GetBuilder()
	defer gencommon.PutBuilder(w)

	pkg := toKotlinPackage(&g.Config.Gen.Kotlin)
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	// Collect imports
	needsUUID, needsLDT, needsInstant := false, false, false
	for _, q := range queries {
		for _, col := range q.Columns {
			kt := g.sqlTypeToKotlin(col.Type, false)
			if strings.Contains(kt, "UUID") {
				needsUUID = true
			}
			if strings.Contains(kt, "LocalDateTime") {
				needsLDT = true
			}
			if strings.Contains(kt, "Instant") {
				needsInstant = true
			}
		}
		for _, param := range q.Params {
			kt := g.sqlTypeToKotlin(param.Type, false)
			if strings.Contains(kt, "UUID") {
				needsUUID = true
			}
			if strings.Contains(kt, "LocalDateTime") {
				needsLDT = true
			}
			if strings.Contains(kt, "Instant") {
				needsInstant = true
			}
		}
	}
	if needsUUID {
		w.WriteString("import java.util.UUID\n")
	}
	if needsLDT {
		w.WriteString("import java.time.LocalDateTime\n")
	}
	if needsInstant {
		w.WriteString("import java.time.Instant\n")
	}
	if needsUUID || needsLDT || needsInstant {
		w.WriteString("\n")
	}

	driver := g.Config.Gen.Kotlin.Driver
	provider := g.Config.Database.Provider
	isScylla := provider == "scylla" || provider == "scylladb" || provider == "cassandra"

	switch {
	case isScylla:
		w.WriteString("import com.datastax.oss.driver.api.core.CqlSession\n\n")
	case driver == "r2dbc":
		w.WriteString("import io.r2dbc.spi.Connection\n\n")
	case driver == "exposed":
		w.WriteString("import org.jetbrains.exposed.sql.Database\n\n")
	default:
		w.WriteString("import java.sql.Connection\n\n")
	}

	// JSON types are generated in a shared JsonTypes.kt file (see generateJsonTypes).
	// Add Gson import for query files that use @json (for fromJson/toJson calls).
	hasJsonTypes := false
	for _, q := range queries {
		if len(q.JsonTypes) > 0 {
			hasJsonTypes = true
			break
		}
	}
	_ = hasJsonTypes

	paramName := "conn"
	var connType string
	switch {
	case isScylla:
		paramName = "session"
		connType = "CqlSession"
	case driver == "exposed":
		paramName = "db"
		connType = "Database"
	default:
		connType = "Connection"
	}

	for _, q := range queries {
		// Emit Row data classes at top level (before the class body)
		columns := g.expandWildcardColumns(q)
		cmd := strings.ToLower(q.Cmd)
		rowType := gencommon.QueryPascal(q.Name) + "Row"
		if mt := g.modelTypeForQuery(q, columns); mt != "" {
			rowType = mt
		}
		if (cmd == ":one" || cmd == ":many") && len(columns) > 1 && rowType == gencommon.QueryPascal(q.Name)+"Row" {
			w.WriteString(fmt.Sprintf("data class %s(\n", rowType))
			ktCols := make([]*parser.QueryColumn, 0, len(columns))
			for _, col := range columns {
				if col.Name != "*" {
					ktCols = append(ktCols, col)
				}
			}
			for i, col := range ktCols {
				// Use col.Nullable directly — it's already set correctly by the parser
				// (schema defaults + @required annotation override)
				nullable := col.Nullable || col.IsComputed
				kt := g.sqlTypeToKotlin(col.Type, nullable)
				// Use typed JSON class if @json annotation exists for this column
				if col.JsonDef != nil {
					kt = col.JsonDef.Name + "?"
				}
				comma := ","
				if i == len(ktCols)-1 {
					comma = ""
				}
				w.WriteString(fmt.Sprintf("    val %s: %s%s\n", gencommon.ToCamelCase(col.Name), kt, comma))
			}
			w.WriteString(")\n\n")
		}
	}

	// Emit Args data classes top-level (before the class body)
	emittedArgs := make(map[string]bool)
	for _, q := range queries {
		if len(q.Params) > 2 {
			argsName := gencommon.QueryPascal(q.Name) + "Params"
			if !emittedArgs[argsName] {
				emittedArgs[argsName] = true
				w.WriteString(fmt.Sprintf("data class %s(\n", argsName))
				for i, p := range q.Params {
					comma := ","
					if i == len(q.Params)-1 {
						comma = ""
					}
					w.WriteString(fmt.Sprintf("    val %s: %s%s\n",
						gencommon.ToCamelCase(p.Name), g.sqlTypeToKotlin(p.Type, p.Nullable), comma))
				}
				w.WriteString(")\n\n")
			}
		}
	}

	w.WriteString("@Suppress(\"DuplicatedCode\")\n")
	w.WriteString(fmt.Sprintf("class %sQueries(private val %s: %s) {\n",
		utils.ToPascalCase(strings.TrimSuffix(src, ".sql")), paramName, connType))

	if driver != "exposed" && driver != "r2dbc" && !isScylla {
		w.WriteString("    private val stmts = mutableMapOf<String, java.sql.PreparedStatement>()\n\n")
		w.WriteString("    fun close() { stmts.values.forEach { it.close() }; stmts.clear() }\n\n")
	}

	for _, q := range queries {
		g.generateQueryMethod(w, q)
	}
	w.WriteString("}\n")

	baseName := strings.TrimSuffix(src, ".sql")

	mu.Lock()
	outputFile := utils.ToPascalCase(baseName) + ".kt"
	if count, exists := usedNames[baseName]; exists {
		usedNames[baseName] = count + 1
		outputFile = fmt.Sprintf("%s_%d.kt", utils.ToPascalCase(baseName), count+1)
	} else {
		usedNames[baseName] = 1
	}
	mu.Unlock()

	path := filepath.Join(g.Config.Gen.Kotlin.Out, outputFile)
	if err := os.WriteFile(path, []byte(w.String()), 0644); err != nil {
		return err
	}

	deps := gencommon.ExtractTableDependencies(queries)
	gencommon.UpdateCacheForFile(g.cache, queryFile, currentHash, deps, path)
	return nil
}

// jsonFieldToKotlinType converts a JsonField type to its Kotlin representation.
// All JSON fields are nullable since JSON values can be null.
func jsonFieldToKotlinType(field *parser.JsonField) string {
	var kt string
	switch field.Type {
	case "string":
		kt = "String"
	case "int":
		kt = "Int"
	case "float":
		kt = "Double"
	case "boolean":
		kt = "Boolean"
	case "string[]":
		kt = "List<String>"
	case "int[]":
		kt = "List<Int>"
	case "float[]":
		kt = "List<Double>"
	case "boolean[]":
		kt = "List<Boolean>"
	case "any":
		kt = "Any"
	default:
		// Could be a nested object type (PascalCase name)
		kt = field.Type
	}
	if field.Nullable {
		return kt + "?"
	}
	return kt
}
