package pygen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/cachegen"
	"github.com/Lumos-Labs-HQ/flash/internal/config"
	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

type Generator struct {
	Config       *config.Config
	schema       *parser.Schema
	schemaParser *parser.SchemaParser
	queryParser  *parser.QueryParser
	cache        *gencommon.GenerationCache
	expander     *gencommon.SchemaExpander
}

func New(cfg *config.Config) *Generator {
	return &Generator{
		Config:       cfg,
		schemaParser: parser.NewSchemaParser(cfg),
		queryParser:  parser.NewQueryParser(cfg),
		cache:        gencommon.NewGenerationCacheWithDir(cfg.Gen.Python.Out),
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Config.Gen.Python.Out, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	schema, err := g.schemaParser.Parse()
	if err != nil {
		return fmt.Errorf("failed to parse schema: %w", err)
	}
	g.schema = schema
	g.expander = gencommon.NewSchemaExpander(schema)

	// Compute checksums for incremental generation
	schemaHash, _ := g.cache.ComputeSchemaChecksum(g.Config.SchemaDir)
	configStr := fmt.Sprintf("%s|%s|%v|%s", g.Config.Database.Provider, g.Config.Gen.Python.Out, g.Config.Gen.Python.Async, g.Config.Gen.Python.Driver)
	configHash := fmt.Sprintf("%x", []byte(configStr))
	fullRegen := g.Config.ForceRegen || g.cache.ShouldRegenerateAll(schemaHash, configHash)

	queries, err := g.queryParser.Parse(schema)
	if err != nil {
		return fmt.Errorf("failed to parse queries: %w", err)
	}

	// Remove cache entries and generated files for query sources that no
	// longer exist (deleted or renamed .sql/.cql files), mirroring gogen.
	pruned := g.cache.PruneStaleQueryEntries(g.Config.Queries)
	for _, source := range pruned {
		base := strings.TrimSuffix(filepath.Base(source), filepath.Ext(source))
		orphan := filepath.Join(g.Config.Gen.Python.Out, base+".py")
		if err := os.Remove(orphan); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove orphaned output %s: %w", orphan, err)
		}
	}

	// A shared cache file (same out dir, multiple languages) can carry a
	// matching schema checksum from another generator — force regen when our
	// own canonical outputs are missing.
	if _, err := os.Stat(filepath.Join(g.Config.Gen.Python.Out, "models.py")); os.IsNotExist(err) {
		fullRegen = true
	}
	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateModels(schema); err != nil {
			return err
		}
	}

	if err := g.generateQueriesIncremental(queries, fullRegen); err != nil {
		return err
	}
	if err := g.generateMigrations(); err != nil {
		return err
	}

	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateDatabase(queries); err != nil {
			return err
		}

		if err := g.generateInit(); err != nil {
			return err
		}
	}

	// Always generate .pyi stub file for IDE autocomplete (needs all query info)
	if err := g.generateTypingStub(queries); err != nil {
		return err
	}

	// Generate cache layer if enabled
	if g.Config.Cache.Enabled {
		if err := g.generateCacheFiles(queries); err != nil {
			return err
		}
	}

	g.cache.UpdateSchemaChecksum(schemaHash)
	g.cache.UpdateConfigChecksum(configHash)
	g.cache.MarkGeneration()
	_ = g.cache.Save()

	return nil
}

func (g *Generator) generateCacheFiles(queries []*parser.Query) error {
	// Generate cache.py
	cacheCode := cachegen.GeneratePythonCache(&g.Config.Cache)
	cachePath := filepath.Join(g.Config.Gen.Python.Out, "cache.py")
	if err := os.WriteFile(cachePath, []byte(cacheCode), 0644); err != nil {
		return fmt.Errorf("failed to write cache.py: %w", err)
	}

	// Resolve cache annotations
	caches := cachegen.ResolveCacheQueries(queries, &g.Config.Cache)

	// Validate dep references
	if warnings := cachegen.ValidateDeps(caches, queries); len(warnings) > 0 {
		for _, w := range warnings {
			fmt.Printf("⚠️  %s\n", w)
		}
	}

	// Generate cache_accessors.py
	accessorCode := cachegen.GeneratePythonCacheAccessors(caches)
	if accessorCode == "" {
		accessorCode = "# Code generated by FlashORM. DO NOT EDIT.\n# No @cache annotations found.\n"
	}
	accessorPath := filepath.Join(g.Config.Gen.Python.Out, "cache_accessors.py")
	if err := os.WriteFile(accessorPath, []byte(accessorCode), 0644); err != nil {
		return fmt.Errorf("failed to write cache_accessors.py: %w", err)
	}

	// Generate cached_queries.py
	cachedCode := g.generateCachedQueries(queries, caches)
	cachedPath := filepath.Join(g.Config.Gen.Python.Out, "cached_queries.py")
	if err := os.WriteFile(cachedPath, []byte(cachedCode), 0644); err != nil {
		return fmt.Errorf("failed to write cached_queries.py: %w", err)
	}

	return nil
}

func (g *Generator) generateCachedQueries(queries []*parser.Query, caches []*cachegen.CacheInfo) string {
	var w strings.Builder
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("from .cache import cache\n\n")

	hasContent := false
	for _, q := range queries {
		if cachegen.IsCachedQuery(q) && !cachegen.IsMutationQuery(q) {
			g.writePyCachedQuery(&w, q, caches)
			hasContent = true
		} else if cachegen.IsMutationQuery(q) {
			purges := cachegen.ResolveDependencyPurges(q.Name, caches, q.Params)
			if len(purges) > 0 {
				g.writePyPurgingMutation(&w, q, purges)
				hasContent = true
			}
		}
	}

	if !hasContent {
		return "# Code generated by FlashORM. DO NOT EDIT.\n# No cached queries or auto-purge mutations.\n"
	}
	return w.String()
}

func (g *Generator) writePyCachedQuery(w *strings.Builder, q *parser.Query, caches []*cachegen.CacheInfo) {
	cacheInfo := cachegen.GetCacheInfoForQuery(q.Name, caches)
	if cacheInfo == nil {
		return
	}
	ttlSec := cachegen.ParseTTL(cacheInfo.TTL)

	var params []string
	for _, p := range q.Params {
		params = append(params, p.Name)
	}
	paramStr := strings.Join(params, ", ")

	var keyExpr string
	if len(params) == 0 {
		keyExpr = fmt.Sprintf("f\"%s\"", cacheInfo.CacheName)
	} else {
		keyExpr = fmt.Sprintf("f\"%s:{%s}\"", cacheInfo.CacheName, strings.Join(params, "}:{"))
	}

	tagsLiteral := "[]"
	if len(cacheInfo.Tags) > 0 {
		quoted := make([]string, len(cacheInfo.Tags))
		for i, t := range cacheInfo.Tags {
			quoted[i] = fmt.Sprintf("\"%s\"", t)
		}
		tagsLiteral = fmt.Sprintf("[%s]", strings.Join(quoted, ", "))
	}

	fnName := fmt.Sprintf("%s_cached", strings.ToLower(q.Name))
	w.WriteString(fmt.Sprintf("async def %s(queries, %s):\n", fnName, paramStr))
	w.WriteString(fmt.Sprintf("    \"\"\"Cached %s (TTL: %s)\"\"\"\n", q.Name, cacheInfo.TTL))
	w.WriteString(fmt.Sprintf("    key = %s\n", keyExpr))
	w.WriteString("    cached = cache.get(key)\n")
	w.WriteString("    if cached is not None:\n")
	w.WriteString("        return cached\n\n")
	w.WriteString(fmt.Sprintf("    result = await queries.%s(%s)\n", strings.ToLower(q.Name), paramStr))
	w.WriteString(fmt.Sprintf("    cache.set(key, result, %d, %s)\n", ttlSec, tagsLiteral))
	w.WriteString("    return result\n\n\n")
}

func (g *Generator) writePyPurgingMutation(w *strings.Builder, q *parser.Query, purges []cachegen.DependencyPurge) {
	var params []string
	for _, p := range q.Params {
		params = append(params, p.Name)
	}
	paramStr := strings.Join(params, ", ")

	fnName := fmt.Sprintf("%s_and_purge", strings.ToLower(q.Name))
	w.WriteString(fmt.Sprintf("async def %s(queries, %s):\n", fnName, paramStr))
	w.WriteString(fmt.Sprintf("    \"\"\"%s with auto-purge\"\"\"\n", q.Name))
	w.WriteString(fmt.Sprintf("    result = await queries.%s(%s)\n\n", strings.ToLower(q.Name), paramStr))
	w.WriteString("    # Auto-purge dependent caches\n")
	for _, purge := range purges {
		if purge.PurgePrefix {
			w.WriteString(fmt.Sprintf("    cache.purge_by_prefix(\"%s:\")\n", purge.CacheName))
		} else {
			w.WriteString(fmt.Sprintf("    cache.delete(f\"%s:{%s}\")\n", purge.CacheName, purge.KeyParam))
		}
	}
	w.WriteString("\n    return result\n\n\n")
}

func (g *Generator) generateModels(schema *parser.Schema) error {
	var w strings.Builder
	// Pre-allocate: header + ~150 bytes per table
	estimatedSize := 200 + (len(schema.Tables) * 150)
	w.Grow(estimatedSize)
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("from dataclasses import dataclass\n")
	w.WriteString("from typing import Optional, List, Literal\n")
	w.WriteString("from datetime import datetime, timedelta\n")
	w.WriteString("from decimal import Decimal\n")

	// Add UUID import if any column uses UUID type
	needsUUID := false
	for _, table := range schema.Tables {
		for _, col := range table.Columns {
			if strings.Contains(strings.ToLower(col.Type), "uuid") {
				needsUUID = true
			}
		}
	}
	if needsUUID {
		w.WriteString("from uuid import UUID\n")
	}
	w.WriteString("\n")

	for _, table := range schema.Tables {
		w.WriteString("@dataclass\n")
		w.WriteString(fmt.Sprintf("class %s:\n", utils.Capitalize(table.Name)))
		for _, col := range table.Columns {
			pyType := g.sqlTypeToPython(col.Type, col.Nullable)
			w.WriteString(fmt.Sprintf("    %s: %s\n", col.Name, pyType))
		}
		w.WriteString("\n")
	}

	path := filepath.Join(g.Config.Gen.Python.Out, "models.py")
	return os.WriteFile(path, []byte(w.String()), 0644)
}

func (g *Generator) generateQueryMethod(w *strings.Builder, query *parser.Query) {
	methodName := utils.ToSnakeCase(query.Name)
	sql := g.convertSQL(query.SQL)
	sql = strings.ReplaceAll(sql, "\"", "\\\"")

	paramNames := make([]string, len(query.Params))
	paramTypes := make([]string, len(query.Params))
	for i, param := range query.Params {
		paramName := param.Name
		if paramName == "" {
			paramName = fmt.Sprintf("p%d", i+1)
		}
		paramNames[i] = paramName
		paramTypes[i] = fmt.Sprintf("%s: %s", paramName, g.sqlTypeToPython(param.Type, param.Nullable))
	}

	returnType := g.getReturnType(query)

	useStructParams := len(query.Params) > 2
	var paramStr string
	var execParamNames []string

	if useStructParams {
		argsClass := gencommon.QueryPascal(query.Name) + "Params"
		// Emit the TypedDict class before the method
		w.WriteString(fmt.Sprintf("class %s(TypedDict):\n", argsClass))
		for _, pt := range paramTypes {
			w.WriteString(fmt.Sprintf("    %s\n", pt))
		}
		w.WriteString("\n")
		paramStr = fmt.Sprintf(", args: %s", argsClass)
		// execution bodies use args["param"]
		execParamNames = make([]string, len(paramNames))
		for i, n := range paramNames {
			execParamNames[i] = fmt.Sprintf("args[\"%s\"]", n)
		}
	} else {
		if len(paramTypes) > 0 {
			paramStr = ", " + strings.Join(paramTypes, ", ")
		}
		execParamNames = paramNames
	}

	// Generate async or sync method based on config
	if g.Config.Gen.Python.Async {
		w.WriteString(fmt.Sprintf("    async def %s(self%s) -> %s:\n",
			methodName, paramStr, returnType))
	} else {
		w.WriteString(fmt.Sprintf("    def %s(self%s) -> %s:\n",
			methodName, paramStr, returnType))
	}

	// Use statement caching for better performance
	w.WriteString(fmt.Sprintf("        _key = '%s'\n", methodName))
	w.WriteString("        if _key not in self._stmts:\n")
	w.WriteString(fmt.Sprintf("            self._stmts[_key] = \"\"\"%s\"\"\"\n", sql))
	w.WriteString("        stmt = self._stmts[_key]\n")

	provider := g.Config.Database.Provider
	driver := g.Config.Gen.Python.Driver
	switch provider {
	case "scylla", "scylladb", "cassandra":
		g.generateScyllaExecution(w, execParamNames, query)
	case "sqlite", "sqlite3":
		if driver == "sqlite3" {
			g.generateSQLite3Execution(w, execParamNames, query)
		} else {
			g.generateSQLiteExecution(w, execParamNames, query)
		}
	case "mysql":
		if driver == "pymysql" {
			g.generatePyMySQLExecution(w, execParamNames, query)
		} else {
			g.generateMySQLExecution(w, execParamNames, query)
		}
	default:
		if driver == "psycopg3" {
			g.generatePsycopg3Execution(w, execParamNames, query)
		} else {
			g.generatePostgreSQLExecution(w, execParamNames, query)
		}
	}

	w.WriteString("\n")
}

func (g *Generator) generatePostgreSQLExecution(w *strings.Builder, paramNames []string, query *parser.Query) {
	hasColumns := len(query.Columns) > 0
	isSingleColumn := len(query.Columns) == 1
	isAsync := g.Config.Gen.Python.Async

	if query.Cmd == ":exec" {
		if isAsync {
			if len(paramNames) > 0 {
				w.WriteString(fmt.Sprintf("        await self.db.execute(stmt, %s)\n", strings.Join(paramNames, ", ")))
			} else {
				w.WriteString("        await self.db.execute(stmt)\n")
			}
		} else {
			if len(paramNames) > 0 {
				w.WriteString(fmt.Sprintf("        self.db.execute(stmt, (%s,))\n", strings.Join(paramNames, ", ")))
			} else {
				w.WriteString("        self.db.execute(stmt)\n")
			}
		}
		w.WriteString("        return 1\n")
		return
	}

	if isAsync {
		if len(paramNames) > 0 {
			w.WriteString(fmt.Sprintf("        result = await self.db.fetch(stmt, %s)\n", strings.Join(paramNames, ", ")))
		} else {
			w.WriteString("        result = await self.db.fetch(stmt)\n")
		}
	} else {
		if len(paramNames) > 0 {
			w.WriteString(fmt.Sprintf("        result = self.db.execute(stmt, (%s,)).fetchall()\n", strings.Join(paramNames, ", ")))
		} else {
			w.WriteString("        result = self.db.execute(stmt).fetchall()\n")
		}
	}

	isSingleNonWildcard := isSingleColumn && query.Columns[0].Name != "*"
	needsResultClass := g.needsResultClass(query)

	if hasColumns {
		if query.Cmd == ":one" {
			if isSingleNonWildcard {
				// Direct column access - fastest path
				w.WriteString(fmt.Sprintf("        return result[0]['%s'] if result else None\n", query.Columns[0].Name))
			} else if needsResultClass {
				className := gencommon.QueryPascal(query.Name) + "Row"
				// asyncpg Records support key access directly - use _make_fast
				w.WriteString(fmt.Sprintf("        return %s._make_fast(result[0]) if result else None\n", className))
			} else {
				// Direct Record access for asyncpg (faster than dict())
				w.WriteString("        return result[0] if result else None\n")
			}
		} else {
			if isSingleNonWildcard {
				// Direct column access in list comprehension
				w.WriteString(fmt.Sprintf("        return [row['%s'] for row in result]\n", query.Columns[0].Name))
			} else if needsResultClass {
				className := gencommon.QueryPascal(query.Name) + "Row"
				w.WriteString(fmt.Sprintf("        return [%s._make_fast(row) for row in result]\n", className))
			} else {
				// Return Records directly (asyncpg Records are dict-like)
				w.WriteString("        return list(result)\n")
			}
		}
	} else {
		switch query.Cmd {
		case ":one":
			w.WriteString("        return dict(result[0]) if result else None\n")
		case ":many":
			w.WriteString("        return [dict(row) for row in result]\n")
		default:
			w.WriteString("        return len(result)\n")
		}
	}
}

func (g *Generator) generateMySQLExecution(w *strings.Builder, paramNames []string, query *parser.Query) {
	returnType := gencommon.QueryPascal(query.Name) + "Row"
	isSingleColumn := len(query.Columns) == 1
	isSingleNonWildcard := isSingleColumn && query.Columns[0].Name != "*"
	needsResultClass := g.needsResultClass(query)

	isAsync := g.Config.Gen.Python.Async

	if isAsync {
		w.WriteString("        async with self._get_conn() as conn:\n")
		w.WriteString("            async with conn.cursor() as cursor:\n")
	} else {
		w.WriteString("        with self.db.cursor() as cursor:\n")
	}

	indent := "            "
	if !isAsync {
		indent = "        "
	}

	if len(paramNames) > 0 {
		if isAsync {
			w.WriteString(fmt.Sprintf("                await cursor.execute(stmt, (%s,))\n", strings.Join(paramNames, ", ")))
		} else {
			w.WriteString(fmt.Sprintf("%s    cursor.execute(stmt, (%s,))\n", indent, strings.Join(paramNames, ", ")))
		}
	} else {
		if isAsync {
			w.WriteString("                await cursor.execute(stmt)\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    cursor.execute(stmt)\n", indent))
		}
	}

	switch query.Cmd {
	case ":one":
		if isAsync {
			w.WriteString("                result = await cursor.fetchone()\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    result = cursor.fetchone()\n", indent))
		}

		if isSingleNonWildcard {
			w.WriteString(fmt.Sprintf("%s    return result['%s'] if result else None\n", indent, query.Columns[0].Name))
		} else {
			w.WriteString(fmt.Sprintf("%s    if result:\n", indent))
			w.WriteString(fmt.Sprintf("%s        row_dict = dict(result) if hasattr(result, 'keys') else {desc[0]: result[i] for i, desc in enumerate(cursor.description)}\n", indent))
			if needsResultClass {
				w.WriteString(fmt.Sprintf("%s        return %s._make_fast(row_dict)\n", indent, returnType))
			} else {
				w.WriteString(fmt.Sprintf("%s        return row_dict\n", indent))
			}
			w.WriteString(fmt.Sprintf("%s    return None\n", indent))
		}
	case ":many":
		if isAsync {
			w.WriteString("                result = await cursor.fetchall()\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    result = cursor.fetchall()\n", indent))
		}

		if isSingleNonWildcard {
			w.WriteString(fmt.Sprintf("%s    return [row['%s'] for row in result]\n", indent, query.Columns[0].Name))
		} else {
			w.WriteString(fmt.Sprintf("%s    rows = [dict(row) if hasattr(row, 'keys') else {cursor.description[i][0]: row[i] for i in range(len(row))} for row in result]\n", indent))
			if needsResultClass {
				w.WriteString(fmt.Sprintf("%s    return [%s._make_fast(row) for row in rows]\n", indent, returnType))
			} else {
				w.WriteString(fmt.Sprintf("%s    return rows\n", indent))
			}
		}
	case ":execresult":
		if isAsync {
			w.WriteString("                await conn.commit()\n")
			w.WriteString("                return cursor.lastrowid\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    self.db.commit()\n", indent))
			w.WriteString(fmt.Sprintf("%s    return cursor.lastrowid\n", indent))
		}
	default:
		if isAsync {
			w.WriteString("                await conn.commit()\n")
			w.WriteString("                return cursor.rowcount\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    self.db.commit()\n", indent))
			w.WriteString(fmt.Sprintf("%s    return cursor.rowcount\n", indent))
		}
	}
}

func (g *Generator) generateSQLiteExecution(w *strings.Builder, paramNames []string, query *parser.Query) {
	returnType := gencommon.QueryPascal(query.Name) + "Row"
	isSingleColumn := len(query.Columns) == 1
	isSingleNonWildcard := isSingleColumn && query.Columns[0].Name != "*"
	needsResultClass := g.needsResultClass(query)
	isAsync := g.Config.Gen.Python.Async

	if isAsync {
		w.WriteString("        async with self.db.execute(stmt")
		if len(paramNames) > 0 {
			w.WriteString(fmt.Sprintf(", (%s,)", strings.Join(paramNames, ", ")))
		}
		w.WriteString(") as cursor:\n")
	} else {
		w.WriteString("        cursor = self.db.execute(stmt")
		if len(paramNames) > 0 {
			w.WriteString(fmt.Sprintf(", (%s,)", strings.Join(paramNames, ", ")))
		}
		w.WriteString(")\n")
	}

	indent := "            "
	if !isAsync {
		indent = "        "
	}

	switch query.Cmd {
	case ":one":
		if isAsync {
			w.WriteString("            result = await cursor.fetchone()\n")
		} else {
			w.WriteString("        result = cursor.fetchone()\n")
		}
		if isSingleNonWildcard {
			w.WriteString(fmt.Sprintf("%sreturn result['%s'] if result else None\n", indent, query.Columns[0].Name))
		} else {
			w.WriteString(fmt.Sprintf("%sif result:\n", indent))
			if needsResultClass {
				w.WriteString(fmt.Sprintf("%s    row_dict = {k: result[k] for k in result.keys()}\n", indent))
				w.WriteString(fmt.Sprintf("%s    return %s._make_fast(row_dict)\n", indent, returnType))
			} else {
				w.WriteString(fmt.Sprintf("%s    return {k: result[k] for k in result.keys()}\n", indent))
			}
			w.WriteString(fmt.Sprintf("%sreturn None\n", indent))
		}
	case ":many":
		if isAsync {
			w.WriteString("            result = await cursor.fetchall()\n")
		} else {
			w.WriteString("        result = cursor.fetchall()\n")
		}
		if isSingleNonWildcard {
			w.WriteString(fmt.Sprintf("%sreturn [row['%s'] for row in result]\n", indent, query.Columns[0].Name))
		} else if needsResultClass {
			w.WriteString(fmt.Sprintf("%sreturn [%s._make_fast({k: row[k] for k in row.keys()}) for row in result]\n", indent, returnType))
		} else {
			w.WriteString(fmt.Sprintf("%sreturn [{k: row[k] for k in row.keys()} for row in result]\n", indent))
		}
	default:
		w.WriteString(fmt.Sprintf("%sreturn cursor.rowcount\n", indent))
	}

	if !isAsync {
		w.WriteString("        cursor.close()\n")
	}
}

func (g *Generator) generateSQLite3Execution(w *strings.Builder, paramNames []string, query *parser.Query) {
	saved := g.Config.Gen.Python.Async
	defer func() { g.Config.Gen.Python.Async = saved }()
	g.Config.Gen.Python.Async = false
	g.generateSQLiteExecution(w, paramNames, query)
}

func (g *Generator) generatePyMySQLExecution(w *strings.Builder, paramNames []string, query *parser.Query) {
	saved := g.Config.Gen.Python.Async
	defer func() { g.Config.Gen.Python.Async = saved }()
	g.Config.Gen.Python.Async = false
	g.generateMySQLExecution(w, paramNames, query)
}

func (g *Generator) generateScyllaExecution(w *strings.Builder, paramNames []string, query *parser.Query) {
	isAsync := g.Config.Gen.Python.Async
	isSingleColumn := len(query.Columns) == 1 && query.Columns[0].Name != "*"
	hasColumns := len(query.Columns) > 0
	prefix := "await "
	if !isAsync {
		prefix = ""
	}

	if query.Cmd == ":exec" {
		if len(paramNames) > 0 {
			w.WriteString(fmt.Sprintf("        %sself.db.session.execute(stmt, (%s,))\n", prefix, strings.Join(paramNames, ", ")))
		} else {
			w.WriteString(fmt.Sprintf("        %sself.db.session.execute(stmt)\n", prefix))
		}
		w.WriteString("        return 1\n")
		return
	}

	if len(paramNames) > 0 {
		w.WriteString(fmt.Sprintf("        %sresult = self.db.session.execute(stmt, (%s,))\n", prefix, strings.Join(paramNames, ", ")))
	} else {
		w.WriteString(fmt.Sprintf("        %sresult = self.db.session.execute(stmt)\n", prefix))
	}

	switch query.Cmd {
	case ":one":
		if hasColumns {
			w.WriteString("        return result.one() if result else None\n")
		} else {
			w.WriteString("        return result.one() if result else None\n")
		}
	case ":many":
		if isSingleColumn && hasColumns {
			w.WriteString(fmt.Sprintf("        return [r.%s for r in result]\n", query.Columns[0].Name))
		} else {
			w.WriteString("        return list(result)\n")
		}
	default:
		w.WriteString("        return result\n")
	}
}

func (g *Generator) generatePsycopg3Execution(w *strings.Builder, paramNames []string, query *parser.Query) {
	returnType := gencommon.QueryPascal(query.Name) + "Row"
	isSingleColumn := len(query.Columns) == 1
	isSingleNonWildcard := isSingleColumn && query.Columns[0].Name != "*"
	needsResultClass := g.needsResultClass(query)
	isAsync := g.Config.Gen.Python.Async

	if isAsync {
		w.WriteString("        async with self.db.cursor() as cur:\n")
	} else {
		w.WriteString("        with self.db.cursor() as cur:\n")
	}

	indent := "            "
	if !isAsync {
		indent = "        "
	}

	if len(paramNames) > 0 {
		if isAsync {
			w.WriteString(fmt.Sprintf("            await cur.execute(stmt, (%s,))\n", strings.Join(paramNames, ", ")))
		} else {
			w.WriteString(fmt.Sprintf("%s    cur.execute(stmt, (%s,))\n", indent, strings.Join(paramNames, ", ")))
		}
	} else {
		if isAsync {
			w.WriteString("            await cur.execute(stmt)\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    cur.execute(stmt)\n", indent))
		}
	}

	switch query.Cmd {
	case ":one":
		if isAsync {
			w.WriteString("            result = await cur.fetchone()\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    result = cur.fetchone()\n", indent))
		}

		if isSingleNonWildcard {
			w.WriteString(fmt.Sprintf("%s    return result['%s'] if result else None\n", indent, query.Columns[0].Name))
		} else {
			w.WriteString(fmt.Sprintf("%s    if result:\n", indent))
			w.WriteString(fmt.Sprintf("%s        row_dict = dict(result) if hasattr(result, 'keys') else {desc[0]: result[i] for i, desc in enumerate(cur.description)}\n", indent))
			if needsResultClass {
				w.WriteString(fmt.Sprintf("%s        return %s._make_fast(row_dict)\n", indent, returnType))
			} else {
				w.WriteString(fmt.Sprintf("%s        return row_dict\n", indent))
			}
			w.WriteString(fmt.Sprintf("%s    return None\n", indent))
		}
	case ":many":
		if isAsync {
			w.WriteString("            result = await cur.fetchall()\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    result = cur.fetchall()\n", indent))
		}

		if isSingleNonWildcard {
			w.WriteString(fmt.Sprintf("%s    return [row['%s'] for row in result]\n", indent, query.Columns[0].Name))
		} else {
			w.WriteString(fmt.Sprintf("%s    rows = [dict(row) if hasattr(row, 'keys') else {cur.description[i][0]: row[i] for i in range(len(row))} for row in result]\n", indent))
			if needsResultClass {
				w.WriteString(fmt.Sprintf("%s    return [%s._make_fast(row) for row in rows]\n", indent, returnType))
			} else {
				w.WriteString(fmt.Sprintf("%s    return rows\n", indent))
			}
		}
	case ":execresult":
		if isAsync {
			w.WriteString("            return cur.rowcount\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    return cur.rowcount\n", indent))
		}
	default:
		if isAsync {
			w.WriteString("            return cur.rowcount\n")
		} else {
			w.WriteString(fmt.Sprintf("%s    return cur.rowcount\n", indent))
		}
	}
}

func (g *Generator) generateDatabase(queries []*parser.Query) error {
	// Get unique source files
	sourceFiles := make(map[string]bool)
	filesList := []string{}
	for _, query := range queries {
		sourceFile := query.SourceFile
		if sourceFile == "" {
			sourceFile = "queries"
		}
		baseName := strings.TrimSuffix(sourceFile, ".sql")
		if !sourceFiles[baseName] {
			sourceFiles[baseName] = true
			filesList = append(filesList, baseName)
		}
	}

	var w strings.Builder
	w.Grow(512) // Pre-allocate for index file
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("from typing import Any\n")

	if len(filesList) == 1 {
		w.WriteString(fmt.Sprintf("from .%s import Queries\n\n", filesList[0]))
	} else {
		for _, baseName := range filesList {
			w.WriteString(fmt.Sprintf("from .%s import Queries as %sQueries\n",
				baseName, utils.Capitalize(baseName)))
		}
		w.WriteString("\n")

		w.WriteString("# Combine all query classes into one\n")
		w.WriteString("class Queries:\n")
		w.WriteString("    \"\"\"Unified query interface that delegates to individual query modules.\"\"\"\n")
		w.WriteString("    \n")
		w.WriteString("    def __init__(self, db):\n")
		w.WriteString("        self.db = db\n")

		for _, baseName := range filesList {
			className := utils.Capitalize(baseName)
			instanceName := fmt.Sprintf("_%s", baseName)
			w.WriteString(fmt.Sprintf("        self.%s = %sQueries(db)\n", instanceName, className))
		}

		w.WriteString("\n")
		w.WriteString("    def __getattr__(self, name):\n")
		w.WriteString("        \"\"\"Delegate attribute access to query modules.\"\"\"\n")

		for i, baseName := range filesList {
			instanceName := fmt.Sprintf("_%s", baseName)
			if i == 0 {
				w.WriteString(fmt.Sprintf("        if hasattr(self.%s, name):\n", instanceName))
				w.WriteString(fmt.Sprintf("            return getattr(self.%s, name)\n", instanceName))
			} else {
				w.WriteString(fmt.Sprintf("        elif hasattr(self.%s, name):\n", instanceName))
				w.WriteString(fmt.Sprintf("            return getattr(self.%s, name)\n", instanceName))
			}
		}

		w.WriteString("        raise AttributeError(f\"'{type(self).__name__}' object has no attribute '{name}'\")\n")
	}

	w.WriteString("\ndef newq(db: Any) -> Queries:\n")
	w.WriteString("    \"\"\"\n")
	w.WriteString("    Create a new database client.\n")
	w.WriteString("    \n")
	w.WriteString("    Args:\n")
	w.WriteString("        db: Database connection (asyncpg.Pool, psycopg3 Connection, aiomysql.Pool, PyMySQL connection, aiosqlite connection, or sqlite3 connection)\n")
	w.WriteString("    \n")
	w.WriteString("    Returns:\n")
	w.WriteString("        Queries: An instance of the Queries class\n")
	w.WriteString("    \"\"\"\n")
	w.WriteString("    return Queries(db)\n")

	path := filepath.Join(g.Config.Gen.Python.Out, "database.py")
	return os.WriteFile(path, []byte(w.String()), 0644)
}

func (g *Generator) generateInit() error {
	var w strings.Builder
	w.Grow(256) // Pre-allocate small buffer
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("from .database import newq\n")
	w.WriteString("from .migrations import FlashInitMigrate\n")
	w.WriteString("from .models import *\n")

	path := filepath.Join(g.Config.Gen.Python.Out, "__init__.py")
	return os.WriteFile(path, []byte(w.String()), 0644)
}

func (g *Generator) convertSQL(sql string) string {
	provider := g.Config.Database.Provider
	driver := g.Config.Gen.Python.Driver

	if driver == "psycopg3" {
		// psycopg3 uses %s placeholders
		for i := 20; i >= 1; i-- {
			sql = strings.ReplaceAll(sql, fmt.Sprintf("$%d", i), "%s")
		}
		return sql
	}

	switch provider {
	case "mysql":
		// MySQL uses %s placeholders for Python's cursor.execute
		for i := 20; i >= 1; i-- {
			sql = strings.ReplaceAll(sql, fmt.Sprintf("$%d", i), "%s")
		}
		placeholderCount := strings.Count(sql, "?")
		for range placeholderCount {
			sql = strings.Replace(sql, "?", "%s", 1)
		}
	case "sqlite", "sqlite3":
		// SQLite uses ? placeholders - convert PostgreSQL-style $1, $2 to ?
		for i := 20; i >= 1; i-- {
			sql = strings.ReplaceAll(sql, fmt.Sprintf("$%d", i), "?")
		}
	}
	// PostgreSQL uses $1, $2 style - no conversion needed
	return sql
}

func (g *Generator) sqlTypeToPython(sqlType string, nullable bool) string {
	sqlTypeLower := strings.ToLower(sqlType)
	var pyType string

	// Check for enum types
	if g.schema != nil {
		for _, enum := range g.schema.Enums {
			if strings.ToLower(enum.Name) == sqlTypeLower {
				quotedValues := make([]string, len(enum.Values))
				for i, v := range enum.Values {
					quotedValues[i] = fmt.Sprintf("'%s'", v)
				}
				pyType = fmt.Sprintf("Literal[%s]", strings.Join(quotedValues, ", "))
				if nullable {
					return fmt.Sprintf("Optional[%s]", pyType)
				}
				return pyType
			}
		}
	}

	switch {
	case strings.HasPrefix(sqlTypeLower, "enum("):
		values := parseMySQLEnumValues(sqlType)
		pyType = "Literal[" + strings.Join(values, ", ") + "]"
	case strings.Contains(sqlTypeLower, "[]"): // Array type
		if strings.Contains(sqlTypeLower, "int") {
			pyType = "List[int]"
		} else {
			pyType = "List[str]"
		}
	case strings.Contains(sqlTypeLower, "tinyint(1)"):
		pyType = "bool"
	case strings.Contains(sqlTypeLower, "bigint"), strings.Contains(sqlTypeLower, "int8"):
		pyType = "int"
	case strings.Contains(sqlTypeLower, "int"), strings.Contains(sqlTypeLower, "serial"), strings.Contains(sqlTypeLower, "smallint"):
		pyType = "int"
	case strings.Contains(sqlTypeLower, "numeric"), strings.Contains(sqlTypeLower, "decimal"):
		pyType = "Decimal"
	case strings.Contains(sqlTypeLower, "float"), strings.Contains(sqlTypeLower, "double"), strings.Contains(sqlTypeLower, "real"):
		pyType = "float"
	case strings.Contains(sqlTypeLower, "bool"):
		pyType = "bool"
	// CQL timeuuid must be checked before "time" — strings.Contains("timeuuid", "time") is true
	case sqlTypeLower == "timeuuid":
		pyType = "UUID"
	case strings.Contains(sqlTypeLower, "timestamp"), strings.Contains(sqlTypeLower, "date"):
		pyType = "datetime"
	case strings.Contains(sqlTypeLower, "time") && !strings.Contains(sqlTypeLower, "timestamp"):
		pyType = "datetime"
	case sqlTypeLower == "interval":
		pyType = "timedelta"
	case strings.Contains(sqlTypeLower, "json"):
		pyType = "dict"
	case strings.Contains(sqlTypeLower, "uuid"):
		pyType = "UUID"
	// ─── PostgreSQL Extension Types ───────────────────────────────────────
	case sqlTypeLower == "vector" || strings.HasPrefix(sqlTypeLower, "vector(") ||
		sqlTypeLower == "halfvec" || strings.HasPrefix(sqlTypeLower, "halfvec("):
		pyType = "List[float]" // pgvector
	case sqlTypeLower == "hstore":
		pyType = "Dict[str, str]"
	case sqlTypeLower == "tsvector", sqlTypeLower == "tsquery":
		pyType = "str"
	case sqlTypeLower == "ltree", sqlTypeLower == "lquery", sqlTypeLower == "ltxtquery":
		pyType = "str"
	case sqlTypeLower == "money":
		pyType = "Decimal"
	case sqlTypeLower == "xml":
		pyType = "str"
	case sqlTypeLower == "pg_lsn":
		pyType = "str"
	case sqlTypeLower == "bit" || strings.HasPrefix(sqlTypeLower, "bit(") ||
		sqlTypeLower == "varbit" || strings.HasPrefix(sqlTypeLower, "varbit(") ||
		strings.HasPrefix(sqlTypeLower, "bit varying"):
		pyType = "str"
	case sqlTypeLower == "inet", sqlTypeLower == "cidr":
		pyType = "str"
	case sqlTypeLower == "macaddr", sqlTypeLower == "macaddr8":
		pyType = "str"
	case sqlTypeLower == "point", sqlTypeLower == "line", sqlTypeLower == "lseg",
		sqlTypeLower == "box", sqlTypeLower == "path", sqlTypeLower == "polygon", sqlTypeLower == "circle":
		pyType = "str"
	case sqlTypeLower == "geometry" || strings.HasPrefix(sqlTypeLower, "geometry(") ||
		sqlTypeLower == "geography" || strings.HasPrefix(sqlTypeLower, "geography("):
		pyType = "str" // PostGIS WKT
	case strings.HasSuffix(sqlTypeLower, "range") || strings.HasSuffix(sqlTypeLower, "multirange"):
		pyType = "str"
	// ClickHouse-specific types
	case sqlTypeLower == "uint8", sqlTypeLower == "uint16", sqlTypeLower == "uint32", sqlTypeLower == "uint64",
		sqlTypeLower == "int16", sqlTypeLower == "int32", sqlTypeLower == "int64":
		pyType = "int"
	case sqlTypeLower == "float32", sqlTypeLower == "float64":
		pyType = "float"
	case sqlTypeLower == "string", strings.HasPrefix(sqlTypeLower, "fixedstring"):
		pyType = "str"
	case strings.HasPrefix(sqlTypeLower, "nullable("):
		inner := sqlTypeLower[9 : len(sqlTypeLower)-1]
		return g.sqlTypeToPython(inner, true)
	case strings.HasPrefix(sqlTypeLower, "array("):
		inner := sqlTypeLower[6 : len(sqlTypeLower)-1]
		elemType := g.sqlTypeToPython(inner, false)
		pyType = "List[" + elemType + "]"
	// ScyllaDB/Cassandra CQL types (non-uuid, checked after uuid above)
	case sqlTypeLower == "inet":
		pyType = "str"
	case sqlTypeLower == "varint", sqlTypeLower == "counter", sqlTypeLower == "duration":
		pyType = "int"
	case strings.HasPrefix(sqlTypeLower, "frozen<"), strings.HasPrefix(sqlTypeLower, "list<"),
		strings.HasPrefix(sqlTypeLower, "set<"), strings.HasPrefix(sqlTypeLower, "map<"),
		strings.HasPrefix(sqlTypeLower, "tuple<"):
		pyType = "Any"
	default:
		pyType = "str"
	}

	if nullable {
		return fmt.Sprintf("Optional[%s]", pyType)
	}
	return pyType
}

func (g *Generator) generateTypingStub(queries []*parser.Query) error {
	var w strings.Builder
	w.Grow(1024)

	w.WriteString("# Type stub for IDE autocomplete\n")
	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("from typing import Any, Optional, List, Literal, TypedDict\n")
	w.WriteString("from datetime import datetime, timedelta\n")
	w.WriteString("from decimal import Decimal\n")

	// Add UUID import if any query uses UUID type
	needsUUID := false
	for _, query := range queries {
		for _, col := range query.Columns {
			if strings.Contains(strings.ToLower(col.Type), "uuid") {
				needsUUID = true
				break
			}
		}
		if needsUUID {
			break
		}
	}
	if needsUUID {
		w.WriteString("from uuid import UUID\n")
	}

	// Import all result classes from all query files
	queryGroups := make(map[string][]*parser.Query)
	for _, query := range queries {
		sourceFile := query.SourceFile
		if sourceFile == "" {
			sourceFile = "queries"
		}
		queryGroups[sourceFile] = append(queryGroups[sourceFile], query)
	}

	// Collect all result class names for imports - use map to avoid duplicates
	allResultClasses := make(map[string]bool)
	for sourceFile, fileQueries := range queryGroups {
		baseName := strings.TrimSuffix(sourceFile, ".sql")
		var resultClasses []string

		for _, query := range fileQueries {
			if g.needsResultClass(query) {
				// Match the actual generated class name format
				className := gencommon.QueryPascal(query.Name) + "Row"
				resultClasses = append(resultClasses, className)
				allResultClasses[className] = true
			}
		}

		if len(resultClasses) > 0 {
			w.WriteString(fmt.Sprintf("from .%s import %s\n", baseName, strings.Join(resultClasses, ", ")))
		}
	}

	w.WriteString("\nclass Queries:\n")
	w.WriteString("    def __init__(self, db: Any) -> None: ...\n\n")

	// Generate method signatures for all queries
	seenMethods := make(map[string]bool)
	for _, query := range queries {
		methodName := utils.ToSnakeCase(query.Name)

		if seenMethods[methodName] {
			continue
		}
		seenMethods[methodName] = true

		// Build parameter list
		paramTypes := make([]string, len(query.Params))
		for i, param := range query.Params {
			paramName := param.Name
			if paramName == "" {
				paramName = fmt.Sprintf("p%d", i+1)
			}
			paramTypes[i] = fmt.Sprintf("%s: %s", paramName, g.sqlTypeToPython(param.Type, param.Nullable))
		}

		// Get return type
		returnType := g.getReturnType(query)

		// Build parameter string
		useStructParams := len(query.Params) > 2
		paramStr := ""
		if useStructParams {
			argsClass := gencommon.QueryPascal(query.Name) + "Params"
			// Emit TypedDict before the class block
			w.WriteString(fmt.Sprintf("class %s(TypedDict):\n", argsClass))
			for _, pt := range paramTypes {
				w.WriteString(fmt.Sprintf("    %s\n", pt))
			}
			w.WriteString("\n")
			paramStr = fmt.Sprintf(", args: %s", argsClass)
		} else if len(paramTypes) > 0 {
			paramStr = ", " + strings.Join(paramTypes, ", ")
		}

		// Generate method signature
		if g.Config.Gen.Python.Async {
			w.WriteString(fmt.Sprintf("    async def %s(self%s) -> %s: ...\n",
				methodName, paramStr, returnType))
		} else {
			w.WriteString(fmt.Sprintf("    def %s(self%s) -> %s: ...\n",
				methodName, paramStr, returnType))
		}
	}

	// Add new() function signature
	w.WriteString("\ndef newq(db: Any) -> Queries: ...\n")

	path := filepath.Join(g.Config.Gen.Python.Out, "database.pyi")
	return os.WriteFile(path, []byte(w.String()), 0644)
}

func (g *Generator) needsResultClass(query *parser.Query) bool {
	if len(query.Columns) == 0 {
		return false
	}

	if len(query.Columns) == 1 && query.Columns[0].Name != "*" {
		return false
	}

	return true
}

func (g *Generator) generateResultClass(w *strings.Builder, query *parser.Query) {
	className := gencommon.QueryPascal(query.Name) + "Row"

	columns := g.expandWildcardColumns(query)
	if len(columns) == 0 {
		return
	}

	// Filter out wildcard columns (e.g. u.* in SELECT u.*, published_posts FROM ...)
	realCols := make([]*parser.QueryColumn, 0, len(columns))
	for _, col := range columns {
		if col.Name != "*" && !strings.HasPrefix(col.Name, "/*") {
			realCols = append(realCols, col)
		}
	}
	if len(realCols) == 0 {
		return
	}

	w.WriteString("@dataclass\n")
	w.WriteString(fmt.Sprintf("class %s:\n", className))
	for _, col := range realCols {
		pyType := g.sqlTypeToPython(col.Type, col.Nullable)
		if col.JsonDef != nil {
			pyType = fmt.Sprintf("Optional[%s]", col.JsonDef.Name)
		}
		w.WriteString(fmt.Sprintf("    %s: %s\n", utils.ToSnakeCase(col.Name), pyType))
	}

	// Add optimized factory method for faster Record -> dataclass conversion
	w.WriteString("\n")
	w.WriteString("    @classmethod\n")
	w.WriteString("    def _make_fast(cls, record):\n")
	w.WriteString("        return cls(\n")
	for i, col := range realCols {
		colName := utils.ToSnakeCase(col.Name)
		if i < len(realCols)-1 {
			w.WriteString(fmt.Sprintf("            record['%s'],\n", colName))
		} else {
			w.WriteString(fmt.Sprintf("            record['%s']\n", colName))
		}
	}
	w.WriteString("        )\n")
	w.WriteString("\n")
}

func (g *Generator) expandWildcardColumns(query *parser.Query) []*parser.QueryColumn {
	if g.expander == nil {
		g.expander = gencommon.NewSchemaExpander(g.schema)
	}
	cols := g.expander.ExpandWildcardColumns(query)
	return cols
}

func (g *Generator) getReturnType(query *parser.Query) string {
	hasColumns := len(query.Columns) > 0
	isSingleColumn := len(query.Columns) == 1 && query.Columns[0].Name != "*"

	if hasColumns && isSingleColumn {
		pyType := g.sqlTypeToPython(query.Columns[0].Type, false)
		if query.Cmd == ":one" {
			return fmt.Sprintf("Optional[%s]", pyType)
		}
		return fmt.Sprintf("List[%s]", pyType)
	}

	if g.needsResultClass(query) {
		// Match the actual generated class name format: ToPascalCase(query.Name) + "Row"
		className := gencommon.QueryPascal(query.Name) + "Row"
		if query.Cmd == ":one" {
			return fmt.Sprintf("Optional[%s]", className)
		}
		return fmt.Sprintf("List[%s]", className)
	}

	switch query.Cmd {
	case ":one":
		return "Optional[dict]"
	case ":many":
		return "List[dict]"
	}
	return "int"
}

// parseMySQLEnumValues extracts quoted values from MySQL ENUM('a', 'b') syntax
func parseMySQLEnumValues(sqlType string) []string {
	start := strings.Index(sqlType, "(")
	end := strings.LastIndex(sqlType, ")")
	if start == -1 || end == -1 || end <= start {
		return nil
	}
	inner := sqlType[start+1 : end]
	var values []string
	var current strings.Builder
	inQuote := false
	quoteChar := rune(0)
	for _, ch := range inner {
		if !inQuote && (ch == '\'' || ch == '"') {
			inQuote = true
			quoteChar = ch
			current.Reset()
		} else if inQuote && ch == quoteChar {
			inQuote = false
			values = append(values, fmt.Sprintf("'%s'", current.String()))
			current.Reset()
		} else if inQuote {
			current.WriteRune(ch)
		}
	}
	return values
}
