package pygen

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

// generateQueriesIncremental generates Python queries with incremental support and parallel code generation
func (g *Generator) generateQueriesIncremental(queries []*parser.Query, fullRegen bool) error {
	queryGroups := make(map[string][]*parser.Query)
	for _, query := range queries {
		sourceFile := query.SourceFile
		if sourceFile == "" {
			sourceFile = "queries"
		}
		queryGroups[sourceFile] = append(queryGroups[sourceFile], query)
	}

	type fileGroup struct {
		sourceFile string
		queries    []*parser.Query
	}

	fileGroups := make([]fileGroup, 0, len(queryGroups))
	for sourceFile, fileQueries := range queryGroups {
		fileGroups = append(fileGroups, fileGroup{sourceFile, fileQueries})
	}

	usedNames := make(map[string]int)
	var usedNamesMu sync.Mutex

	numWorkers := min(runtime.NumCPU(), len(fileGroups))

	type generateResult struct {
		err error
	}

	workChan := make(chan fileGroup, len(fileGroups))
	resultChan := make(chan generateResult, len(fileGroups))

	var wg sync.WaitGroup
	for i := 0; i < numWorkers; i++ {
		wg.Go(func() {
			for fg := range workChan {
				err := g.generateSinglePyFile(fg.sourceFile, fg.queries, fullRegen, &usedNamesMu, usedNames)
				resultChan <- generateResult{err: err}
			}
		})
	}

	for _, fg := range fileGroups {
		workChan <- fg
	}
	close(workChan)

	go func() {
		wg.Wait()
		close(resultChan)
	}()

	for result := range resultChan {
		if result.err != nil {
			return result.err
		}
	}

	return nil
}

func (g *Generator) generateSinglePyFile(sourceFile string, fileQueries []*parser.Query, fullRegen bool, usedNamesMu *sync.Mutex, usedNames map[string]int) error {
	queryFile := filepath.Join(g.Config.Queries, sourceFile+".sql")
	currentHash, _ := gencommon.ComputeFileChecksum(queryFile)

	// The skip decision must consider this generator's own output file so a
	// shared cache entry from another language cannot suppress generation.
	primaryOutput := filepath.Join(g.Config.Gen.Python.Out, strings.TrimSuffix(sourceFile, ".sql")+".py")
	if !gencommon.ShouldRegenerateFileForOutput(g.cache, queryFile, currentHash, fullRegen, primaryOutput) {
		gencommon.PrintSkipMessage(sourceFile, ".py")
		return nil
	}

	gencommon.PrintGenerateMessage(sourceFile, ".py")

	w := gencommon.GetBuilder()
	defer gencommon.PutBuilder(w)

	w.WriteString("# Code generated by FlashORM. DO NOT EDIT.\n\n")

	// Check if any query needs TypedDict (struct params)
	needsTypedDict := false
	for _, query := range fileQueries {
		if len(query.Params) > 2 {
			needsTypedDict = true
			break
		}
	}
	if needsTypedDict {
		w.WriteString("from typing import Optional, List, Any, Literal, TypedDict\n")
	} else {
		w.WriteString("from typing import Optional, List, Any, Literal\n")
	}
	w.WriteString("from dataclasses import dataclass\n")
	w.WriteString("from datetime import datetime, timedelta\n")
	w.WriteString("from decimal import Decimal\n")

	// Add UUID import if any query column or param uses UUID
	needsUUID := false
	for _, query := range fileQueries {
		for _, col := range query.Columns {
			if strings.Contains(strings.ToLower(col.Type), "uuid") {
				needsUUID = true
			}
		}
		for _, param := range query.Params {
			if strings.Contains(strings.ToLower(param.Type), "uuid") {
				needsUUID = true
			}
		}
	}
	if needsUUID {
		w.WriteString("from uuid import UUID\n")
	}
	w.WriteString("\n")

	// Generate JSON type dataclasses from @json annotations
	emittedJsonTypes := make(map[string]bool)
	for _, query := range fileQueries {
		for _, jt := range query.JsonTypes {
			if emittedJsonTypes[jt.Name] {
				continue
			}
			emittedJsonTypes[jt.Name] = true
			w.WriteString("@dataclass\n")
			w.WriteString(fmt.Sprintf("class %s:\n", jt.Name))
			w.WriteString(fmt.Sprintf("    \"\"\"JSON type for column '%s'. Parse with: %s(**json.loads(row.%s))\"\"\"\n", jt.Column, jt.Name, jt.Column))
			for _, field := range jt.Fields {
				pyType := jsonFieldToPythonType(field)
				w.WriteString(fmt.Sprintf("    %s: %s\n", utils.ToSnakeCase(field.Name), pyType))
			}
			w.WriteString("\n")
		}
	}

	for _, query := range fileQueries {
		if g.needsResultClass(query) {
			g.generateResultClass(w, query)
		}
	}

	w.WriteString("class Queries:\n")
	w.WriteString("    def __init__(self, db):\n")
	w.WriteString("        self.db = db\n")
	w.WriteString("        self._stmts = {}\n")

	isAsync := g.Config.Gen.Python.Async
	provider := g.Config.Database.Provider
	if isAsync && provider == "mysql" {
		w.WriteString("\n")
		w.WriteString("    def _get_conn(self):\n")
		w.WriteString("        import contextlib\n")
		w.WriteString("        @contextlib.asynccontextmanager\n")
		w.WriteString("        async def _manager():\n")
		w.WriteString("            if hasattr(self.db, 'acquire'):\n")
		w.WriteString("                async with self.db.acquire() as conn:\n")
		w.WriteString("                    yield conn\n")
		w.WriteString("            else:\n")
		w.WriteString("                yield self.db\n")
		w.WriteString("        return _manager()\n")
	}
	w.WriteString("\n")

	for _, query := range fileQueries {
		g.generateQueryMethod(w, query)
	}

	baseName := strings.TrimSuffix(sourceFile, ".sql")

	usedNamesMu.Lock()
	outputFile := baseName + ".py"
	if count, exists := usedNames[baseName]; exists {
		usedNames[baseName] = count + 1
		outputFile = fmt.Sprintf("%s_%d.py", baseName, count+1)
	} else {
		usedNames[baseName] = 1
	}
	usedNamesMu.Unlock()

	path := filepath.Join(g.Config.Gen.Python.Out, outputFile)
	if err := os.WriteFile(path, []byte(w.String()), 0644); err != nil {
		return err
	}

	tableDeps := gencommon.ExtractTableDependencies(fileQueries)
	gencommon.UpdateCacheForFile(g.cache, queryFile, currentHash, tableDeps, path)

	return nil
}

// jsonFieldToPythonType converts a JsonField type to its Python type annotation.
func jsonFieldToPythonType(field *parser.JsonField) string {
	var pyType string
	switch field.Type {
	case "string":
		pyType = "str"
	case "int":
		pyType = "int"
	case "float":
		pyType = "float"
	case "boolean":
		pyType = "bool"
	case "string[]":
		pyType = "List[str]"
	case "int[]":
		pyType = "List[int]"
	case "float[]":
		pyType = "List[float]"
	case "boolean[]":
		pyType = "List[bool]"
	case "any":
		pyType = "Any"
	default:
		pyType = field.Type
	}
	if field.Nullable {
		return "Optional[" + pyType + "]"
	}
	return pyType
}
